// Real Core/durable jobs with synthetic executor outputs. No engine or model.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire,register} from 'node:module';
register(new URL('../../vendor/pi-desktop/apps/desktop/test/helpers/ts-import-hooks.mjs',import.meta.url));
const require=createRequire(import.meta.url),{CoreClient}=require('../../plugins/craftmine-world/core-client.cjs');
const {createHostRequests}=require('../../desktop/build/craftmine.world/host-requests.cjs');
const binary=process.env.CRAFTMINE_CORE_BIN;if(!binary)throw Error('CRAFTMINE_CORE_BIN required');
const hash=x=>createHash('sha256').update(x).digest('hex');
test('ordinary initialization retry creates a fresh task check; private continuation follows the actual Core contract',async t=>{
 const root=path.resolve(import.meta.dirname,'../..');fs.mkdirSync(path.join(root,'test-results'),{recursive:true});
 const out=fs.mkdtempSync(path.join(root,'test-results/initialization-retry-core-'));
 let core=new CoreClient(binary,path.join(out,'data'));t.after(()=>core.stop());await core.start();
 const call=async(method,args)=>{try{return await core.call(method,args);}catch(error){error.message=method+': '+error.message;throw error;}},domain=createHostRequests({call,start:()=>core.start()},{});
 const worldId='retry-world',context={projectId:'craftmine-world-initialization',sessionId:'create-retry-world',turnId:'first-turn'};
 const state={format:'craftmine.godot-progress/1',worldId,baseId:'first-person',baseVersion:'0.1.0',stateVersion:1,body:{worldId,position:[0,1,0]}};
 await call('world.create',{id:worldId,title:'Authored retry fixture',world:{build:{id:'base-fixture',scene:{format:'craftmine.godot-scene/1',baseId:'first-person'},godot:{}},snapshot:state,extensions:[]}});
 const workspace=await domain('turn.begin',{context,selectedWorld:worldId,request:{id:'initialize-'+worldId,text:'Initialize the selected authored base and confirm its first load.'}});
 const project=await call('godotProject.create',{context,worldId,toolCallId:'source',baseBuild:workspace.binding.baseBuild,baseId:'first-person',files:[{path:'project.godot',text:'config_version=5\n[application]\nconfig/name="Retry fixture"\n'}]});
 const evidenceHash=hash('synthetic executor; no engine');
 const registerExecutor=()=>call('godotExecutor.register',{executorId:'fixture-executor',attestation:{format:'craftmine.godot-executor/1',isolation:'appcontainer',evidenceHash,engineVersion:'4.7.2-stable',capabilities:{import:true,build:true,check:true}}});
 await registerExecutor();
 const request={context,worldId,toolCallId:'base-build-'+project.manifestHash,revision:project.revision,manifestHash:project.manifestHash,mode:'check'};
 const origin=await domain('godotBuild.start',request);
 const claim=await call('godotJob.claim',{jobId:origin.jobId,token:'fixture-token',executorId:'fixture-executor'});
 const failed=await call('godotJob.finish',{jobId:origin.jobId,token:'fixture-token',output:{format:'craftmine.godot-job-result/1',inputHash:claim.inputHash,passed:false,import:{passed:false,log:'Synthetic native failure'},compile:{passed:false,errors:['AUTHORED_FAILURE'],warnings:[]},check:{passed:false,assertions:[{id:'not-run',passed:false}]},artifacts:[],engine:{version:'4.7.2-stable',isolation:'appcontainer',evidenceHash}}});
 assert.equal(failed.status,'failed');
 // Same request replays the original terminal receipt; it cannot retry execution.
 assert.equal((await domain('godotBuild.start',request)).jobId,origin.jobId);
 await call('workspace.endTurn',{sessionId:context.sessionId,turnId:context.turnId,status:'error'});
 await core.stop();core=new CoreClient(binary,path.join(out,'data'));await core.start();await registerExecutor();
 const next={...context,turnId:'retry-turn'};
 const available=await call('task.recoverable',{projectId:next.projectId,worldId});
 const previous=available.items.find(item=>item.binding.sessionId===context.sessionId);assert.ok(previous);
 await domain('task.resume',{context:next,worldId,taskId:previous.taskId,generation:previous.generation});
 await domain('turn.begin',{context:next,selectedWorld:worldId,request:{id:'initialize-'+worldId,text:'Initialize the selected authored base and confirm its first load.'}});
 const nextRequest={...request,context:next},continued=await domain('godotBuild.start',nextRequest);
 assert.notEqual(continued.jobId,origin.jobId);assert.equal(continued.buildId,origin.buildId);assert.equal(continued.sourceRevision,project.revision);assert.equal(continued.status,'queued');
 assert.equal((await domain('godotBuild.start',nextRequest)).jobId,continued.jobId,'same retry invocation is idempotent');
 await assert.rejects(domain('godotJob.continue',{context:next,worldId,originJobId:continued.jobId,toolCallId:'cannot-continue-active'}),/GODOT_JOB_NOT_CONTINUABLE/);
 await assert.rejects(domain('godotJob.continue',{context:next,worldId:'other-world',originJobId:origin.jobId,toolCallId:'wrong-world'}),/PROJECT_WORLD_BINDING_MISMATCH/);
 await assert.rejects(domain('godotJob.continue',{jobId:origin.jobId,token:'forged'}),{name:'HarnessError'});
 const original=await call('godotBuild.read',{worldId,jobId:origin.jobId});assert.equal(original.status,'failed');assert.equal(original.outputHash,failed.outputHash);
 const changed=await call('godotProject.patch',{context:next,worldId,toolCallId:'changed-source',revision:project.revision,manifestHash:project.manifestHash,operations:[{op:'put',path:'actor.gd',expectedHash:null,text:'extends Node\n'}]});
 await assert.rejects(domain('godotJob.continue',{context:next,worldId,originJobId:origin.jobId,toolCallId:'stale-source'}),/GODOT_CONTINUATION_STALE/);
 const fresh=await domain('godotBuild.start',{...nextRequest,toolCallId:'base-build-'+changed.manifestHash,revision:changed.revision,manifestHash:changed.manifestHash});assert.notEqual(fresh.jobId,continued.jobId);assert.equal(fresh.manifestHash,changed.manifestHash);
 const claim2=await call('godotJob.claim',{jobId:fresh.jobId,token:'fixture-token-2',executorId:'fixture-executor'});
 await call('godotJob.finish',{jobId:fresh.jobId,token:'fixture-token-2',output:{format:'craftmine.godot-job-result/1',inputHash:claim2.inputHash,passed:false,import:{passed:false,log:'Synthetic failure'},compile:{passed:false,errors:['AUTHORED_FAILURE'],warnings:[]},check:{passed:false,assertions:[{id:'not-run',passed:false}]},artifacts:[],engine:{version:'4.7.2-stable',isolation:'appcontainer',evidenceHash}}});
 const explicit=await domain('godotJob.continue',{context:next,worldId,originJobId:fresh.jobId,toolCallId:'explicit-continue'});assert.equal(explicit.originJobId,fresh.jobId);assert.equal(explicit.status,'queued');
 assert.equal((await domain('godotJob.continue',{context:next,worldId,originJobId:fresh.jobId,toolCallId:'explicit-continue'})).jobId,explicit.jobId);
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({format:'craftmine.initialization-retry-core/1',passed:true,binary,binarySha256:hash(fs.readFileSync(binary)),originJobId:origin.jobId,originOutputHash:failed.outputHash,retryJobId:continued.jobId,changedSourceJobId:fresh.jobId,explicitContinuationJobId:explicit.jobId,scope:'Real Core transactions and restarts; synthetic failed executor output; ordinary initializer start remains unchanged, no Godot/player acceptance'},null,2));
 console.log('EVIDENCE_DIRECTORY='+out);
});
