#!/usr/bin/env node
// Generate the reviewable notice documents from licensing/inventory.json and
// licensing/offline-entry.json. Every statement cites the evidence path it came from.
//
// Usage:
//   node desktop/delivery/licensing/tools/gen-notices.mjs
//   node desktop/delivery/licensing/tools/gen-notices.mjs --inventory <file> --out <dir>
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const LICENSING_DIR = path.resolve(HERE, '..');
const DEFAULT_INVENTORY = path.join(LICENSING_DIR, 'inventory.json');
const DEFAULT_OUT = path.join(LICENSING_DIR, 'notices');
const OFFLINE_ENTRY = path.join(LICENSING_DIR, 'offline-entry.json');
const TEXTS_DIR = path.join(LICENSING_DIR, 'texts');

const option = name => {
  const index = process.argv.indexOf('--' + name);
  return index === -1 ? null : process.argv[index + 1];
};
const readJson = file => JSON.parse(fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, ''));
const escapePipes = value => String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');

function evidenceList(entry) {
  return (entry.evidence ?? []).map(item => '`' + item.path + '`' + (item.commit ? ' @ ' + item.commit.slice(0, 8) : '')).join('; ') || '(no evidence recorded)';
}

function statusMarker(entry) {
  if (entry.status === 'verified') return 'VERIFIED (facts only)';
  if (entry.status === 'pending-rights-review') return 'PENDING rights review — not a pass';
  return 'UNKNOWN rights holder — not cleared';
}

function entryTable(entries) {
  const rows = [
    '| id | module | origin | observed licence | target licence | status | delivery channels |',
    '| --- | --- | --- | --- | --- | --- | --- |'
  ];
  for (const entry of entries) {
    rows.push('| `' + entry.id + '` | ' + escapePipes(entry.module) + ' | ' + entry.origin + ' | ' + escapePipes(entry.observedLicense) + ' | ' + escapePipes(entry.targetLicense) + ' | ' + statusMarker(entry) + ' | ' + entry.deliveryChannels.join(', ') + ' |');
  }
  return rows.join('\n');
}

function offlineSection(offline, scope) {
  const lines = ['| text id | expected path | status | covers | evidence / note |', '| --- | --- | --- | --- | --- |'];
  for (const item of offline[scope].required) {
    lines.push('| `' + item.id + '` | `' + offline[scope].root + '/' + item.file + '` | ' + item.status + ' | ' + (item.covers ?? []).join(', ') + ' | ' + escapePipes(item.note ?? item.reason ?? '') + ' |');
  }
  return lines.join('\n');
}

function packageList(record, label) {
  const lines = ['| package | version | licence |', '| --- | --- | --- |'];
  for (const entry of record.packages) lines.push('| ' + escapePipes(entry.name ?? entry.package) + ' | ' + escapePipes(entry.version ?? '') + ' | ' + escapePipes(entry.license ?? 'NO LICENCE ID') + ' |');
  lines.push('');
  lines.push(label + ': ' + record.packages.length + ' entries. Licence counts: ' + Object.entries(record.licenseCounts).map(([key, value]) => key + '=' + value).join(', ') + '.');
  return lines.join('\n');
}

export function generate({inventoryPath = DEFAULT_INVENTORY, outDirectory = DEFAULT_OUT} = {}) {
  const inventory = readJson(inventoryPath);
  const offline = readJson(OFFLINE_ENTRY);
  const evidenceDirectory = path.join(LICENSING_DIR, 'evidence');
  const npm = readJson(path.join(evidenceDirectory, 'npm-licenses.json'));
  const cargo = readJson(path.join(evidenceDirectory, 'cargo-licenses.json'));
  const sources = fs.existsSync(path.join(TEXTS_DIR, 'SOURCES.json')) ? readJson(path.join(TEXTS_DIR, 'SOURCES.json')) : {texts: []};
  const entries = inventory.entries;
  const projectOwned = entries.filter(entry => entry.origin === 'project-authored' || entry.origin === 'generated');
  const thirdParty = entries.filter(entry => entry.origin === 'third-party');
  const userContent = entries.filter(entry => entry.origin === 'user-content');
  const pending = entries.filter(entry => entry.status !== 'verified');

  const header = [
    '<!-- GENERATED by desktop/delivery/licensing/tools/gen-notices.mjs — do not edit by hand. -->',
    '# Craftmine World notices (client and package)',
    '',
    'Generated: ' + inventory.generatedAt + ' from `desktop/delivery/licensing/inventory.json` (format `' + inventory.format + '`).',
    '',
    'This file records facts and targets. It is **not legal advice, not a licence and not a contract**.',
    'Nothing here applies a licence or relicenses anything. Pending and unknown entries are marked as such and are never a pass.',
    '',
    'Decision record: `docs/LICENSING_STRATEGY.md` (decision only; not an applied licence).',
    'Inventory: `desktop/delivery/licensing/inventory.json`. Offline entry: `desktop/delivery/licensing/offline-entry.json`.',
    'Official texts fetched from their publishers: see `desktop/delivery/licensing/texts/SOURCES.json`.',
    ''
  ].join('\n');

  const notices = [
    header,
    '## 1 Components and target licences',
    '',
    entryTable(entries),
    '',
    '## 2 Project-owned components (AGPL-3.0-only plus commercial, or MIT for export runtime — targets only)',
    '',
    'Every row below is **project-authored or project-generated**. None of these target licences is applied yet.',
    '',
    ...projectOwned.flatMap(entry => [
      '### `' + entry.id + '`',
      '',
      '- Module: ' + entry.module,
      '- Paths: ' + entry.paths.map(value => '`' + value + '`').join(', '),
      '- Rights holder: ' + entry.rightsHolder,
      '- Observed licence: ' + entry.observedLicense,
      '- Target licence: ' + entry.targetLicense,
      '- Licence file: ' + (entry.licenseFile ? '`' + entry.licenseFile + '`' : 'none'),
      '- Status: **' + statusMarker(entry) + '**',
      '- Delivery channels: ' + entry.deliveryChannels.join(', '),
      '- Evidence: ' + evidenceList(entry),
      entry.openQuestions.length ? '- Open questions:\n' + entry.openQuestions.map(question => '  - ' + question).join('\n') : '',
      ''
    ].filter(Boolean)),
    '## 3 Upstream PI-Desktop (LGPL-3.0-or-later retained)',
    '',
    'PI-Desktop is vendored at the pinned commit `' + inventory.worktree.upstreamCommit + '` and keeps LGPL-3.0-or-later. Its licence text is `vendor/pi-desktop/LICENSE` (SHA-256 e3a994d82e644b03a792a930f574002658412f62407f5fee083f2555c5f23118), copied into the package as `resources/licenses/PI-Desktop-LICENSE.txt`.',
    '',
    'The LGPL-3 text is the supplement that incorporates GPL-3 by reference; the full GPL-3 text is **not** bundled. Whether it must be is an open legal question recorded in `desktop/delivery/licensing/offline-entry.json` (id `gpl-3.0`, status `missing`).',
    '',
    'Corresponding source for the LGPL obligation travels as `resources/source/CraftmineWorld-source.zip` (see `desktop/windows-NOTICES.md` and `desktop/godot/licenses/README.md`). Evidence: `desktop/UPSTREAM.json`, `vendor/pi-desktop/LICENSE`, `desktop/delivery/licensing/evidence/upstream-diff.json` (' + inventory.upstreamDiffFacts.unchanged + ' unchanged, ' + inventory.upstreamDiffFacts.modified + ' modified, ' + inventory.upstreamDiffFacts.added + ' added tracked files).',
    '',
    '## 4 Godot Engine and its bundled third-party components',
    '',
    'Godot Engine ' + (readJson(path.join(LICENSING_DIR, '..', '..', 'godot/toolchain.lock.json')).version) + ' is MIT. Evidence: `desktop/godot/licenses/GODOT_LICENSE.txt`, `desktop/godot/toolchain.lock.json`, `desktop/godot/licenses/notices.manifest.json`. The aggregate `GODOT_COPYRIGHT.txt` is not decomposed per component; that row stays pending. Godot\'s MIT licence does not cover game assets or the LGPL obligations above.',
    '',
    '## 5 Bundled fonts',
    '',
    'Geist, Inter, Noto Sans SC and LXGW WenKai ship under OFL-1.1 with byte-pinned licence texts. Evidence: `desktop/godot/licenses/notices.manifest.json` and `vendor/pi-desktop/apps/desktop/src/assets/fonts/licenses/`.',
    '',
    '## 6 npm third-party dependencies (installed in the client)',
    '',
    'Source of truth: `vendor/pi-desktop/pnpm-lock.yaml` cross-checked against the real build inventory `resources/licenses/third-party/npm-inventory.json`. Snapshot: `desktop/delivery/licensing/evidence/npm-licenses.json` (' + npm.counts.packages + ' packages, ' + npm.counts.withoutCopiedText + ' without a copied licence text, ' + npm.counts.unmatchedAgainstLock + ' not matched against the lockfile).',
    '',
    'Electron and Chromium notices travel in their own package files (`LICENSE.electron.txt`, `LICENSES.chromium.html`) and are outside this inventory.',
    '',
    packageList(npm, 'npm packages'),
    '',
    npm.counts.withoutCopiedText ? 'Packages with no copied licence text (the obligation is recorded but no text is bundled for them): ' + npm.packages.filter(entry => !entry.licenseFiles.length).map(entry => '`' + entry.package + '`').join(', ') : '',
    '',
    '## 7 Rust third-party dependencies (linked into the shipped binaries)',
    '',
    'Source of truth: `vendor/pi-desktop/Cargo.lock` and a real `cargo metadata` walk. Snapshot: `desktop/delivery/licensing/evidence/cargo-licenses.json` (' + cargo.counts.reachableFromShippedBins + ' crates reachable from the shipped binaries, ' + cargo.counts.missingLicenseId + ' without a declared licence id). No consolidated Rust notice file exists yet (`cargo-third-party-notices`, status `missing`).',
    '',
    packageList(cargo, 'Rust crates'),
    '',
    '## 8 User-created content and AI output',
    '',
    ...userContent.flatMap(entry => [
      '### `' + entry.id + '`',
      '',
      '- Rights holder: ' + entry.rightsHolder,
      '- Observed licence: ' + entry.observedLicense,
      '- Target: ' + entry.targetLicense,
      '- Status: **' + statusMarker(entry) + '**',
      '- The project does not claim copyright in user works and makes **no warranty** about the provenance, rights or fitness of user-imported content or AI output.',
      '- Evidence: ' + evidenceList(entry),
      ''
    ]),
    '## 9 Offline licence entry inside the packaged client',
    '',
    'Root: `' + offline.package.root + '`. Entry document: `' + offline.package.entryDocument + '`.',
    '',
    offlineSection(offline, 'package'),
    '',
    'See `desktop/delivery/licensing/OFFLINE_LICENSE_ENTRY.md` for the user-facing instructions and `desktop/delivery/licensing-check.mjs` for the machine check.',
    '',
    '## 10 Pending and unknown entries (never a pass)',
    '',
    '| id | status | reason it is not cleared |',
    '| --- | --- | --- |',
    ...pending.map(entry => '| `' + entry.id + '` | ' + entry.status + ' | ' + escapePipes(entry.openQuestions[0] ?? '') + ' |'),
    '',
    '## 11 Official licence texts',
    '',
    '| text | url | retrieved | bytes | sha256 |',
    '| --- | --- | --- | --- | --- |',
    ...sources.texts.map(text => '| `' + text.file + '` | ' + text.url + ' | ' + text.retrievedAt + ' | ' + text.bytes + ' | `' + text.sha256 + '` |'),
    '',
    '## 12 Limits',
    '',
    ...inventory.limits.map(limit => '- ' + limit),
    ''
  ].filter(line => line !== null).join('\n');

  const exportNotices = [
    '<!-- GENERATED by desktop/delivery/licensing/tools/gen-notices.mjs — do not edit by hand. -->',
    '# Notices and licence notes for an exported Craftmine World game',
    '',
    'Generated: ' + inventory.generatedAt + ' from `desktop/delivery/licensing/inventory.json` and `desktop/delivery/licensing/offline-entry.json`.',
    '',
    'This file is **not a licence and not a contract**. It explains what must travel with an exported game and what the project does and does not promise.',
    '',
    '## 1 What an exported game must carry',
    '',
    '- `licenses/GODOT_LICENSE.txt` — the Godot Engine MIT licence, byte-identical to `desktop/godot/licenses/GODOT_LICENSE.txt` (SHA-256 b0435e3b3e4e55238f05f4b306f30524a1b2e20147810d436eaa554fa6855c80). Evidence: `desktop/godot/toolchain.lock.json`, `desktop/godot/licenses/notices.manifest.json`, `desktop/godot/export-probes.mjs`.',
    '- `licenses/GODOT_COPYRIGHT.txt` — the aggregate engine third-party notices. Evidence: `desktop/godot/licenses/notices.manifest.json`.',
    '- `licenses/EXPORT-NOTICES.md` — this document.',
    '- The licence texts for any user content or third-party asset the creator includes. The project cannot supply or audit those.',
    '',
    '## 2 Project export runtime (MIT target — not yet applied)',
    '',
    'The export runtime candidates are `desktop/godot/web/bridge.js`, `desktop/godot/web/shell.html`, `desktop/godot/probes/shared/web_bridge.gd` and the three bases\' export-runtime scripts. Their declared origin is project-authored and their target is MIT, but the formal MIT text with a copyright-holder string is **not written** (`desktop/delivery/licensing/offline-entry.json`, id `mit`, status `missing`). Evidence: `desktop/delivery/base-assets/shared-web.json`, `desktop/delivery/base-assets/first-person.json`, `desktop/delivery/base-assets/top-down.json`, `desktop/delivery/base-assets/bases-*.json`, `desktop/delivery/base-assets/rights/*.md`.',
    '',
    '## 3 AGPL / LGPL code in an export needs separate handling',
    '',
    'If an exported game includes AGPL-3.0-only code (creation core, built-in plugin, craftmine-core) or LGPL-3.0-or-later code (PI-Desktop and its modifications), the export needs its own compliance handling: corresponding source and licence texts for the included code, and for LGPL the source/replacement or relinking facilities that the chosen distribution requires. The current export pipeline does not include the client, so the ids `agpl-3.0` and `lgpl-3.0` are recorded as `conditional`, not satisfied. Evidence: `docs/LICENSING_STRATEGY.md` section 3, `desktop/delivery/licensing/offline-entry.json`.',
    '',
    '## 4 What a player or creator may do with an exported game',
    '',
    '- The Godot Engine MIT licence permits commercial use, modification and redistribution of the engine as embedded in the export, provided its copyright and licence notice travel with it.',
    '- The creator\'s own content stays the creator\'s: the project does not claim copyright in user works (`desktop/windows-NOTICES.md`, `desktop/godot/licenses/notices.manifest.json` notIncluded section).',
    '- Third-party assets the creator imports keep their own licences; the creator is responsible for them.',
    '- The project\'s export-runtime code is a **MIT target**, not an applied grant; until the text exists, no licence is asserted here.',
    '',
    '## 5 What must travel with an export (offline entry)',
    '',
    'Root: `' + offline.export.root + '`. Entry document: `' + offline.export.entryDocument + '`.',
    '',
    offlineSection(offline, 'export'),
    '',
    '## 6 What the project does not warrant',
    '',
    '- No warranty that an export is free of third-party rights, including AI-generated content.',
    '- No warranty of merchantability, fitness for a purpose or legal sufficiency in any jurisdiction.',
    '- No warranty that the notice set is complete for a jurisdiction other than the one the project reviewed.',
    '- The project does not promise third-party authorisation and cannot grant rights it does not hold.',
    '',
    '## 7 Evidence',
    '',
    ...entries.filter(entry => entry.deliveryChannels.includes('user-export')).map(entry => '- `' + entry.id + '` (' + entry.status + '): ' + evidenceList(entry)),
    ''
  ].join('\n');

  fs.mkdirSync(outDirectory, {recursive: true});
  const clientPath = path.join(outDirectory, 'CRAFTMINE-NOTICES.md');
  const exportPath = path.join(outDirectory, 'EXPORT-NOTICES.md');
  fs.writeFileSync(clientPath, notices + '\n');
  fs.writeFileSync(exportPath, exportNotices + '\n');
  return {clientPath, exportPath, entries: entries.length, pending: pending.length};
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const result = generate({inventoryPath: option('inventory') ?? DEFAULT_INVENTORY, outDirectory: option('out') ?? DEFAULT_OUT});
    console.log('WROTE ' + path.relative(process.cwd(), result.clientPath));
    console.log('WROTE ' + path.relative(process.cwd(), result.exportPath));
    console.log('entries=' + result.entries + ' pendingOrUnknown=' + result.pending);
  } catch (error) {
    console.error('gen-notices failed: ' + error.message);
    process.exit(2);
  }
}
