import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {createBlenderJobs}=require('../plugins/craftmine-world/blender-jobs.cjs');
const native=require('../plugins/craftmine-world/blender-broker.cjs');
const sha='1'.repeat(64),brokerSha='2'.repeat(64),runtimeSha='3'.repeat(64);
async function fixture(t,overrides={}){
  const dataPath=await fs.mkdtemp(path.join(os.tmpdir(),'cm-bl-test-'));
  const context={projectId:'project',sessionId:'session',turnId:'turn'};
  const binding={context,worldId:'world',workspace:{task:{binding:{taskId:'task',baseBuild:'base'}}},toolCallId:'tool-1'};
  let revision=1,patches=[],calls=[],requests=[],mutate=overrides.mutate;
  const core={directory:dataPath,call:async(method,args)=>{calls.push({method,args});if(method==='godotProject.index')return {worldId:'world',revision,manifestHash:sha,baseBuild:'base',content:{repoId:'repo',branchId:'main',contentOid:'a'.repeat(40)}};
    if(method==='godotProject.read'){const model=Buffer.from('model-bytes');return {worldId:'world',revision,manifestHash:sha,path:args.path,sha256:overrides.readHash??native.hash(model),bytes:model.length};}
    if(method==='godotProject.patch'){if(overrides.patchError)throw Object.assign(Error(overrides.patchError),{errorCode:overrides.patchError});patches.push(args);revision++;return {...(overrides.gitReceipt?{}:{worldId:'world'}),revision,manifestHash:sha};}throw Error('UNEXPECTED_METHOD:'+method);}};
  const discovery={toolchain:{runtimeRoot:path.join(dataPath,'runtime')},brokerSha256:brokerSha,runtimeVersion:'5.2.1',runtimeInventoryDigest:runtimeSha};
  const runBroker=async(found,request,signal)=>{requests.push(request);if(overrides.wait)await new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>reject(Error('BLENDER_JOB_CANCELLED')),{once:true});});
    const files=[];for(const name of await fs.readdir(request.projectRoot)){const bytes=await fs.readFile(path.join(request.projectRoot,name));files.push({path:name,bytes:bytes.length,sha256:native.hash(bytes)});}
    const outputs={'model.glb':Buffer.from('model-bytes'),'source.blend':Buffer.from('BLENDER-model'),'script.py':await fs.readFile(path.join(request.projectRoot,'script.py')),'report.json':Buffer.from(JSON.stringify({meshObjects:1,vertices:8,polygons:6,materials:1}))};
    const artifactsRoot=path.join(request.tasksRoot,request.taskId,'artifacts');await fs.mkdir(artifactsRoot,{recursive:true});const artifacts=[];
    for(const [name,bytes]of Object.entries(outputs)){await fs.writeFile(path.join(artifactsRoot,name),bytes);artifacts.push({path:name,bytes:bytes.length,sha256:native.hash(bytes)});}
    const receipt={...request,state:'succeeded',exitCode:0,sourceFiles:files,sourceSnapshotDigest:native.digest(files),policyVersion:'craftmine.windows.lpac-registry.v1',processVerification:{appContainerSid:"S-1-test",verified:true,verifiedBeforeResume:true,jobMembershipVerified:true,isAppContainer:true,activeProcessLimit:1},networkPreflight:{processVerification:{appContainerSid:"S-1-test",verified:true,verifiedBeforeResume:true,jobMembershipVerified:true,isAppContainer:true,activeProcessLimit:1},verified:true,jobActiveProcesses:0,exactTaskExempt:false,hostReceivedCounts:[0,0,0,0]},cleanup:{verified:true,workRemoved:true,profileHresult:0,error:null},resourceEnforcement:{enforced:false},jobActiveProcesses:0,binRemoved:true,recoveryJournal:{cleared:true,error:null,policyVersion:'craftmine.windows.recovery-journal.v1'},brokerSha256:brokerSha,runtimeVersion:'5.2.1',runtimeInventoryDigest:runtimeSha,artifactsRoot,artifacts};
    if(overrides.stale)revision++;await mutate?.(receipt,request);return receipt;};
  const options={dataPath,toolchain:discovery.toolchain,discover:async()=>discovery,recover:async()=>({verified:true,reclaimed:0}),runBroker};
  const service=createBlenderJobs(core,options);t.after(async()=>{await service.stop();await fs.rm(dataPath,{recursive:true,force:true});});
  const args={name:'crate',script:'import bpy\nbpy.ops.mesh.primitive_cube_add()',revision:1,manifestHash:sha,expectedHash:null};
  let seq=0;const start=(extra={},bound=binding)=>service.tool('blender_generate',{...args,...extra},{...bound,toolCallId:'tool-'+(++seq)});
  const read=(job,bound=binding)=>service.tool('blender_job_read',{jobId:job.jobId},bound);
  return {service,core,options,start,read,binding,args,dataPath,patches,calls,requests,setRevision:value=>{revision=value;},setMutate:value=>{mutate=value;}};
}
test('asynchronous generation preserves sources, pins native request, commits exact Godot transaction, never claims applied',async t=>{
  const f=await fixture(t);const job=await f.start();assert.equal(job.status,'queued');const result=await f.read(job);
  assert.equal(result.status,'imported');assert.equal(result.applied,false);assert.equal(result.playableVerified,false);assert.equal(result.stats.vertices,8);
  assert.equal(f.patches.length,1);const patch=f.patches[0];assert.equal(patch.revision,1);assert.equal(patch.manifestHash,sha);assert.equal(patch.operations[0].expectedHash,null);assert.equal(patch.operations[0].path,'assets/blender/crate.glb');assert.equal(patch.operation.expectedHeadOid,'a'.repeat(40));
  assert.equal(f.requests[0].inputHash,native.digest([{path:'script.py',bytes:Buffer.byteLength(f.args.script),sha256:native.hash(f.args.script)}]));assert.match(f.requests[0].taskId,/^bl-[a-f0-9]{20}$/);
  assert.equal((await fs.readFile(path.join(f.dataPath,'blender-jobs',job.jobId,'assets','source.blend'))).toString(),'BLENDER-model');assert.ok(!JSON.stringify(result).includes(f.dataPath));
});
test('source revision race preserves output and does not overwrite newer project',async t=>{const f=await fixture(t,{stale:true});const result=await f.read(await f.start());assert.equal(result.status,'generated');assert.equal(result.reason,'BLENDER_SOURCE_STALE');assert.equal(f.patches.length,0);assert.equal(result.artifacts.length,4);});
test('destination hash conflict is surfaced without lost generated source',async t=>{const f=await fixture(t,{patchError:'FILE_HASH_MISMATCH'});const result=await f.read(await f.start({expectedHash:'4'.repeat(64)}));assert.equal(result.status,'generated');assert.equal(result.reason,'FILE_HASH_MISMATCH');});
test('Git patch receipt without worldId imports only after pinned source verification',async t=>{const f=await fixture(t,{gitReceipt:true});const result=await f.read(await f.start());assert.equal(result.status,'imported');const read=f.calls.find(call=>call.method==='godotProject.read');assert.equal(read.args.worldId,'world');assert.equal(read.args.revision,2);assert.equal(read.args.limit,1);});
test('a successful patch receipt with wrong committed bytes cannot claim imported',async t=>{const f=await fixture(t,{gitReceipt:true,readHash:'0'.repeat(64)});const result=await f.read(await f.start());assert.equal(result.status,'generated');assert.equal(result.reason,'BLENDER_IMPORT_SOURCE_MISMATCH');});
for(const [label,mutate,reason]of [
  ['world binding',receipt=>{receipt.sourceBinding={...receipt.sourceBinding,worldId:'other'};},'BLENDER_BROKER_BINDING_MISMATCH'],
  ['OS isolation',receipt=>{receipt.processVerification.verified=false;},'BLENDER_OS_ISOLATION_UNVERIFIED'],
  ['cleanup',receipt=>{receipt.binRemoved=false;},'BLENDER_CLEANUP_UNVERIFIED'],
  ['active native child',receipt=>{receipt.jobActiveProcesses=1;},'BLENDER_OS_ISOLATION_UNVERIFIED'],
  ['runtime pin',receipt=>{receipt.runtimeInventoryDigest='0'.repeat(64);},'BLENDER_RUNTIME_UNVERIFIED'],
  ['artifact hash',receipt=>{receipt.artifacts[0].sha256='0'.repeat(64);},'BLENDER_ARTIFACT_HASH_MISMATCH'],
  ['artifact traversal',receipt=>{receipt.artifacts[0].path='../model.glb';},'BLENDER_ARTIFACT_LIST_INVALID'],
])test('rejects forged '+label+' before import',async t=>{const f=await fixture(t,{mutate});const result=await f.read(await f.start());assert.equal(result.status,'failed');assert.equal(result.reason,reason);assert.equal(f.patches.length,0);});
test('cross-world reads, cancellation and previous source are refused',async t=>{const f=await fixture(t);const job=await f.start();await f.read(job);const foreign={...f.binding,worldId:'other'};await assert.rejects(f.read(job,foreign),/BINDING_MISMATCH/);f.setRevision(1);await assert.rejects(f.start({previousJobId:job.jobId},foreign),/SOURCE_STALE/);await assert.rejects(f.service.tool('blender_cancel',{jobId:job.jobId},{...f.binding,context:{...f.binding.context,turnId:'other'}}),/CANCEL_SCOPE_MISMATCH/);});
test('turn end cancels native worker and records terminal cancellation',async t=>{const f=await fixture(t,{wait:true});const job=await f.start();await new Promise(resolve=>setTimeout(resolve,20));await f.service.cancelTurn(f.binding.context);const result=await f.read(job);assert.equal(result.status,'cancelled');assert.equal(f.patches.length,0);});
test('previous source is verified and reused; tampering prevents execution',async t=>{const f=await fixture(t);const first=await f.start();await f.read(first);const second=await f.start({revision:2,name:'crate-v2',previousJobId:first.jobId});await f.read(second);assert.equal(f.requests.length,2);assert.ok(await fs.readFile(path.join(f.requests[1].projectRoot,'source.blend')));await fs.writeFile(path.join(f.dataPath,'blender-jobs',first.jobId,'assets','source.blend'),'tampered');await assert.rejects(f.start({revision:3,previousJobId:first.jobId}),/SOURCE_HASH_MISMATCH/);});
test('restart marks abandoned record interrupted, store switching refuses old source identity',async t=>{const f=await fixture(t);const job=await f.start();await f.read(job);const recordPath=path.join(f.dataPath,'blender-jobs',job.jobId,'record.json');const record=JSON.parse(await fs.readFile(recordPath));record.status='running';await fs.writeFile(recordPath,JSON.stringify(record));const restarted=createBlenderJobs(f.core,f.options);await restarted.start();assert.equal((await restarted.tool('blender_job_read',{jobId:job.jobId},f.binding)).status,'interrupted');f.core.directory=path.join(f.dataPath,'restore');await assert.rejects(f.read(job),/BINDING_MISMATCH/);await restarted.stop();});
test('missing packaged toolchain is an explicit capability gap and never spawns arbitrary Blender',async t=>{const f=await fixture(t);const service=createBlenderJobs(f.core,{dataPath:f.dataPath,toolchain:null});const status=await service.status();assert.equal(status.available,false);assert.equal(status.reason,'BLENDER_TOOLCHAIN_UNAVAILABLE');await assert.rejects(service.tool('blender_generate',f.args,f.binding),/TOOLCHAIN_UNAVAILABLE/);await service.stop();});

test('replayed or concurrent invocation returns one durable job and changed replay is refused',async t=>{const f=await fixture(t);const [a,b]=await Promise.all([f.service.tool('blender_generate',f.args,f.binding),f.service.tool('blender_generate',f.args,f.binding)]);assert.equal(a.jobId,b.jobId);await f.read(a);assert.equal(f.requests.length,1);assert.equal((await f.service.tool('blender_generate',f.args,f.binding)).jobId,a.jobId);await assert.rejects(f.service.tool('blender_generate',{...f.args,name:'other'},f.binding),/INVOCATION_CHANGED/);});
test('incomplete native recovery blocks generation and is retried after the external state changes',async t=>{const f=await fixture(t);let blocked=true,count=0;const service=createBlenderJobs(f.core,{...f.options,recover:async()=>{count++;if(blocked)throw Error('BLENDER_RECOVERY_INCOMPLETE');return {verified:true,reclaimed:1};}});assert.equal((await service.status()).reason,'BLENDER_RECOVERY_INCOMPLETE');await assert.rejects(service.tool('blender_generate',f.args,f.binding),/RECOVERY_INCOMPLETE/);assert.equal(f.requests.length,0);blocked=false;assert.equal((await service.status()).available,true);await service.status();assert.equal(count,3);await service.stop();await service.start();assert.equal(count,4);await service.stop();});
test('runtime lock and native executable must both match host-selected broker identity',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'cm-bl-pin-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.mkdir(path.join(root,'broker'));await fs.mkdir(path.join(root,'runtime'));const executable=Buffer.from('test-broker'),runtime=Buffer.from('test-runtime');await fs.writeFile(path.join(root,'broker','blender-host-broker.exe'),executable);await fs.writeFile(path.join(root,'runtime','blender.exe'),runtime);const files=[{path:'blender.exe',bytes:runtime.length,sha256:native.hash(runtime)}];const lock={format:'craftmine.blender-toolchain/1',runtimeVersion:'5.2.1',files};const identity={format:'craftmine.blender-broker-identity/1',bytes:executable.length,sha256:native.hash(executable),runtimeVersion:'5.2.1',runtimeInventoryDigest:native.hash(JSON.stringify(files))};const toolchain={runtimeRoot:root,broker:path.join(root,'broker','blender-host-broker.exe'),brokerIdentity:path.join(root,'broker','broker-identity.json'),toolchainLock:path.join(root,'toolchain.lock.json')};await fs.writeFile(toolchain.brokerIdentity,JSON.stringify(identity));await fs.writeFile(toolchain.toolchainLock,JSON.stringify(lock));assert.equal((await native.discover(toolchain)).runtimeVersion,'5.2.1');await fs.writeFile(toolchain.broker,'forged');await assert.rejects(native.discover(toolchain),/BROKER_PIN_MISMATCH/);await fs.writeFile(toolchain.broker,executable);lock.files[0].sha256='0'.repeat(64);await fs.writeFile(toolchain.toolchainLock,JSON.stringify(lock));await assert.rejects(native.discover(toolchain),/RUNTIME_PIN_MISMATCH/);});
async function failScript(receipt,request){const log=Buffer.from('Traceback (most recent call last):\n  File "'+path.join(request.projectRoot,'script.py')+'", line 2\nNameError: missing_mesh\n');const logsRoot=path.join(request.tasksRoot,request.taskId,'logs');await fs.mkdir(logsRoot,{recursive:true});await fs.writeFile(path.join(logsRoot,'task.log'),log);receipt.state='failed';receipt.exitCode=1;receipt.logsRoot=logsRoot;receipt.logs=[{path:'task.log',bytes:log.length,sha256:native.hash(log)}];}
test('failed script exposes bounded pinned traceback as untrusted diagnostics without private roots',async t=>{const f=await fixture(t,{mutate:failScript});const result=await f.read(await f.start());assert.equal(result.status,'failed');assert.equal(result.diagnostics.source,'untrusted-script-log');assert.match(result.diagnostics.text,/NameError: missing_mesh/);assert.ok(!result.diagnostics.text.includes(f.dataPath));assert.equal(f.patches.length,0);});
test('forged receipt binding or arbitrary diagnostic root never grants log reads',async t=>{for(const mode of ['binding','path','hash']){const f=await fixture(t,{mutate:async(receipt,request)=>{await failScript(receipt,request);if(mode==='binding')receipt.sourceBinding={...receipt.sourceBinding,worldId:'other'};if(mode==='path')receipt.logsRoot=path.dirname(receipt.logsRoot);if(mode==='hash')receipt.logs[0].sha256='0'.repeat(64);}});const result=await f.read(await f.start());assert.equal(result.diagnostics,undefined);assert.equal(f.patches.length,0);}});
test('cancel during the final asynchronous active check cannot import',async t=>{const f=await fixture(t);let release,pausedResolve;const gate=new Promise(resolve=>{release=resolve;}),paused=new Promise(resolve=>{pausedResolve=resolve;});const service=createBlenderJobs(f.core,{...f.options,assertActive:async()=>{for(const id of await fs.readdir(path.join(f.dataPath,'blender-jobs')).catch(()=>[])){const record=JSON.parse(await fs.readFile(path.join(f.dataPath,'blender-jobs',id,'record.json')).catch(()=>'{"status":null}'));if(record.status==='importing'){pausedResolve();await gate;}}}});const job=await service.tool('blender_generate',f.args,f.binding);await paused;const cancelled=service.cancelTurn(f.binding.context);release();await cancelled;assert.equal((await service.tool('blender_job_read',{jobId:job.jobId},f.binding)).status,'cancelled');assert.equal(f.patches.length,0);await service.stop();});
test('world status discovers preserved source across conversations with exact name and pagination; global status stays private',async t=>{const f=await fixture(t);const first=await f.start();await f.read(first);const second=await f.start({name:'roof',revision:2});await f.read(second);const newConversation={...f.binding,context:{...f.binding.context,sessionId:'new-session',turnId:'new-turn'}};const status=await f.service.tool('blender_status',{limit:1},newConversation);assert.equal(status.jobs.total,2);assert.equal(status.jobs.items.length,1);assert.equal(status.jobs.nextOffset,1);assert.equal(status.jobs.items[0].sourceJobId,second.jobId);const next=await f.service.tool('blender_status',{offset:1,limit:1},newConversation);assert.equal(next.jobs.items[0].sourceJobId,first.jobId);assert.equal(next.jobs.nextOffset,null);const named=await f.service.tool('blender_status',{name:'crate'},newConversation);assert.equal(named.jobs.total,1);assert.equal(named.jobs.items[0].sourceJobId,first.jobId);assert.equal((await f.service.status()).jobs,undefined);assert.ok(!JSON.stringify(status.jobs).includes(f.dataPath));});
test('history excludes other worlds, projects, stores and linked records and rejects path-shaped name queries',async t=>{const f=await fixture(t);const own=await f.start();await f.read(own);const root=path.join(f.dataPath,'blender-jobs'),record=JSON.parse(await fs.readFile(path.join(root,own.jobId,'record.json')));
  for(const changes of [{worldId:'other-world'},{projectId:'other-project'},{storeDirectory:path.join(f.dataPath,'old-store')},{modelPath:'../outside.glb'}]){const id=require('node:crypto').randomUUID();await fs.mkdir(path.join(root,id));await fs.writeFile(path.join(root,id,'record.json'),JSON.stringify({...record,...changes,jobId:id}));}
  const linkedId=require('node:crypto').randomUUID();await fs.symlink(path.join(root,own.jobId),path.join(root,linkedId),process.platform==='win32'?'junction':'dir');
  const status=await f.service.tool('blender_status',{},f.binding);assert.equal(status.jobs.total,1);assert.equal(status.jobs.items[0].jobId,own.jobId);const foreign=await f.service.tool('blender_status',{}, {...f.binding,worldId:'unrelated'});assert.equal(foreign.jobs.total,0);await assert.rejects(f.service.tool('blender_status',{name:'../outside'},f.binding),/BLENDER_NAME_INVALID/);await assert.rejects(f.service.tool('blender_status',{offset:-1},f.binding),/BLENDER_HISTORY_PAGE_INVALID/);await assert.rejects(f.service.tool('blender_status',{limit:21},f.binding),/BLENDER_HISTORY_PAGE_INVALID/);f.core.directory=path.join(f.dataPath,'new-store');assert.equal((await f.service.tool('blender_status',{},f.binding)).jobs.total,0);
});
test('reads and history remain importing while source transaction preparation is delayed',async t=>{const f=await fixture(t);let release,pausedResolve;const gate=new Promise(resolve=>{release=resolve;}),paused=new Promise(resolve=>{pausedResolve=resolve;});const original=f.core.call;f.core.call=async(method,args)=>{if(method==='godotProject.index'&&args.revision===undefined){pausedResolve();await gate;}return original(method,args);};const job=await f.start();await paused;const keepAlive=setTimeout(()=>{},2000);const pending=await f.read(job);clearTimeout(keepAlive);assert.equal(pending.status,'importing');const history=await f.service.tool('blender_status',{},f.binding);assert.equal(history.jobs.items[0].status,'importing');assert.equal(f.patches.length,0);release();assert.equal((await f.read(job)).status,'imported');});
