import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {createBlenderJobs}=require('../plugins/craftmine-world/blender-jobs.cjs');
const native=require('../plugins/craftmine-world/blender-broker.cjs');
const sha='1'.repeat(64),brokerSha='2'.repeat(64),runtimeSha='3'.repeat(64);
async function fixture(t,overrides={}){
  const dataPath=await fs.mkdtemp(path.join(os.tmpdir(),'cm-bl-test-'));
  const context={projectId:'project',sessionId:'session',turnId:'turn'};
  const binding={context,worldId:'world',workspace:{task:{binding:{taskId:'task',baseBuild:'base'}}},toolCallId:'tool-1'};
  let revision=1,patches=[],calls=[],requests=[],mutate=overrides.mutate;
  const core={directory:dataPath,call:async(method,args)=>{calls.push({method,args});if(method==='godotProject.index')return {worldId:'world',revision,manifestHash:sha,baseBuild:'base',content:{repoId:'repo',branchId:'main',contentOid:'a'.repeat(40)}};
    if(method==='godotProject.patch'){if(overrides.patchError)throw Object.assign(Error(overrides.patchError),{errorCode:overrides.patchError});patches.push(args);revision++;return {worldId:'world',revision,manifestHash:sha};}throw Error('UNEXPECTED_METHOD:'+method);}};
  const discovery={toolchain:{runtimeRoot:path.join(dataPath,'runtime')},brokerSha256:brokerSha,runtimeVersion:'5.2.1',runtimeInventoryDigest:runtimeSha};
  const runBroker=async(found,request,signal)=>{requests.push(request);if(overrides.wait)await new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>reject(Error('BLENDER_JOB_CANCELLED')),{once:true});});
    const files=[];for(const name of await fs.readdir(request.projectRoot)){const bytes=await fs.readFile(path.join(request.projectRoot,name));files.push({path:name,bytes:bytes.length,sha256:native.hash(bytes)});}
    const outputs={'model.glb':Buffer.from('model-bytes'),'source.blend':Buffer.from('BLENDER-model'),'script.py':await fs.readFile(path.join(request.projectRoot,'script.py')),'report.json':Buffer.from(JSON.stringify({meshObjects:1,vertices:8,polygons:6,materials:1}))};
    const artifactsRoot=path.join(request.tasksRoot,request.taskId,'artifacts');await fs.mkdir(artifactsRoot,{recursive:true});const artifacts=[];
    for(const [name,bytes]of Object.entries(outputs)){await fs.writeFile(path.join(artifactsRoot,name),bytes);artifacts.push({path:name,bytes:bytes.length,sha256:native.hash(bytes)});}
    const receipt={...request,state:'succeeded',exitCode:0,sourceFiles:files,sourceSnapshotDigest:native.digest(files),policyVersion:'craftmine.windows.lpac-registry.v1',processVerification:{verified:true,verifiedBeforeResume:true,jobMembershipVerified:true,isAppContainer:true,activeProcessLimit:1},networkPreflight:{verified:true,jobActiveProcesses:0,exactTaskExempt:false,hostReceivedCounts:[0,0,0,0]},cleanup:{verified:true,workRemoved:true,profileHresult:0,error:null},resourceEnforcement:{enforced:false},jobActiveProcesses:0,binRemoved:true,recoveryJournal:{cleared:true,error:null,policyVersion:'craftmine.windows.recovery-journal.v1'},brokerSha256:brokerSha,runtimeVersion:'5.2.1',runtimeInventoryDigest:runtimeSha,artifactsRoot,artifacts};
    if(overrides.stale)revision++;await mutate?.(receipt,request);return receipt;};
  const options={dataPath,toolchain:discovery.toolchain,discover:async()=>discovery,recover:async()=>({verified:true,reclaimed:0}),runBroker};
  const service=createBlenderJobs(core,options);t.after(async()=>{await service.stop();await fs.rm(dataPath,{recursive:true,force:true});});
  const args={name:'crate',script:'import bpy\nbpy.ops.mesh.primitive_cube_add()',revision:1,manifestHash:sha,expectedHash:null};
  let seq=0;const start=(extra={},bound=binding)=>service.tool('blender_generate',{...args,...extra},{...bound,toolCallId:'tool-'+(++seq)});
  const read=(job,bound=binding)=>service.tool('blender_job_read',{jobId:job.jobId},bound);
  return {service,core,options,start,read,binding,args,dataPath,patches,calls,requests,setRevision:value=>{revision=value;},setMutate:value=>{mutate=value;}};
}
test('asynchronous generation preserves sources, pins native request, commits exact Godot transaction, never claims applied',async t=>{
  const f=await fixture(t);const job=await f.start();assert.equal(job.status,'queued');const result=await f.read(job);
  assert.equal(result.status,'imported');assert.equal(result.applied,false);assert.equal(result.playableVerified,false);assert.equal(result.stats.vertices,8);
  assert.equal(f.patches.length,1);const patch=f.patches[0];assert.equal(patch.revision,1);assert.equal(patch.manifestHash,sha);assert.equal(patch.operations[0].expectedHash,null);assert.equal(patch.operations[0].path,'assets/blender/crate.glb');assert.equal(patch.operation.expectedHeadOid,'a'.repeat(40));
  assert.equal(f.requests[0].inputHash,native.digest([{path:'script.py',bytes:Buffer.byteLength(f.args.script),sha256:native.hash(f.args.script)}]));assert.match(f.requests[0].taskId,/^bl-[a-f0-9]{20}$/);
  assert.equal((await fs.readFile(path.join(f.dataPath,'blender-jobs',job.jobId,'assets','source.blend'))).toString(),'BLENDER-model');assert.ok(!JSON.stringify(result).includes(f.dataPath));
});
test('source revision race preserves output and does not overwrite newer project',async t=>{const f=await fixture(t,{stale:true});const result=await f.read(await f.start());assert.equal(result.status,'generated');assert.equal(result.reason,'BLENDER_SOURCE_STALE');assert.equal(f.patches.length,0);assert.equal(result.artifacts.length,4);});
test('destination hash conflict is surfaced without lost generated source',async t=>{const f=await fixture(t,{patchError:'FILE_HASH_MISMATCH'});const result=await f.read(await f.start({expectedHash:'4'.repeat(64)}));assert.equal(result.status,'generated');assert.equal(result.reason,'FILE_HASH_MISMATCH');});
for(const [label,mutate,reason]of [
  ['world binding',receipt=>{receipt.sourceBinding={...receipt.sourceBinding,worldId:'other'};},'BLENDER_BROKER_BINDING_MISMATCH'],
  ['OS isolation',receipt=>{receipt.processVerification.verified=false;},'BLENDER_OS_ISOLATION_UNVERIFIED'],
  ['cleanup',receipt=>{receipt.binRemoved=false;},'BLENDER_CLEANUP_UNVERIFIED'],
  ['active native child',receipt=>{receipt.jobActiveProcesses=1;},'BLENDER_OS_ISOLATION_UNVERIFIED'],
  ['runtime pin',receipt=>{receipt.runtimeInventoryDigest='0'.repeat(64);},'BLENDER_RUNTIME_UNVERIFIED'],
  ['artifact hash',receipt=>{receipt.artifacts[0].sha256='0'.repeat(64);},'BLENDER_ARTIFACT_HASH_MISMATCH'],
  ['artifact traversal',receipt=>{receipt.artifacts[0].path='../model.glb';},'BLENDER_ARTIFACT_LIST_INVALID'],
])test('rejects forged '+label+' before import',async t=>{const f=await fixture(t,{mutate});const result=await f.read(await f.start());assert.equal(result.status,'failed');assert.equal(result.reason,reason);assert.equal(f.patches.length,0);});
test('cross-world reads, cancellation and previous source are refused',async t=>{const f=await fixture(t);const job=await f.start();await f.read(job);const foreign={...f.binding,worldId:'other'};await assert.rejects(f.read(job,foreign),/BINDING_MISMATCH/);f.setRevision(1);await assert.rejects(f.start({previousJobId:job.jobId},foreign),/SOURCE_STALE/);await assert.rejects(f.service.tool('blender_cancel',{jobId:job.jobId},{...f.binding,context:{...f.binding.context,turnId:'other'}}),/CANCEL_SCOPE_MISMATCH/);});
test('turn end cancels native worker and records terminal cancellation',async t=>{const f=await fixture(t,{wait:true});const job=await f.start();await new Promise(resolve=>setTimeout(resolve,20));await f.service.cancelTurn(f.binding.context);const result=await f.read(job);assert.equal(result.status,'cancelled');assert.equal(f.patches.length,0);});
test('previous source is verified and reused; tampering prevents execution',async t=>{const f=await fixture(t);const first=await f.start();await f.read(first);const second=await f.start({revision:2,name:'crate-v2',previousJobId:first.jobId});await f.read(second);assert.equal(f.requests.length,2);assert.ok(await fs.readFile(path.join(f.requests[1].projectRoot,'source.blend')));await fs.writeFile(path.join(f.dataPath,'blender-jobs',first.jobId,'assets','source.blend'),'tampered');await assert.rejects(f.start({revision:3,previousJobId:first.jobId}),/SOURCE_HASH_MISMATCH/);});
test('restart marks abandoned record interrupted, store switching refuses old source identity',async t=>{const f=await fixture(t);const job=await f.start();await f.read(job);const recordPath=path.join(f.dataPath,'blender-jobs',job.jobId,'record.json');const record=JSON.parse(await fs.readFile(recordPath));record.status='running';await fs.writeFile(recordPath,JSON.stringify(record));const restarted=createBlenderJobs(f.core,f.options);await restarted.start();assert.equal((await restarted.tool('blender_job_read',{jobId:job.jobId},f.binding)).status,'interrupted');f.core.directory=path.join(f.dataPath,'restore');await assert.rejects(f.read(job),/BINDING_MISMATCH/);await restarted.stop();});
test('missing packaged toolchain is an explicit capability gap and never spawns arbitrary Blender',async t=>{const f=await fixture(t);const service=createBlenderJobs(f.core,{dataPath:f.dataPath,toolchain:null});const status=await service.status();assert.equal(status.available,false);assert.equal(status.reason,'BLENDER_TOOLCHAIN_UNAVAILABLE');await assert.rejects(service.tool('blender_generate',f.args,f.binding),/TOOLCHAIN_UNAVAILABLE/);await service.stop();});

test('replayed or concurrent invocation returns one durable job and changed replay is refused',async t=>{const f=await fixture(t);const [a,b]=await Promise.all([f.service.tool('blender_generate',f.args,f.binding),f.service.tool('blender_generate',f.args,f.binding)]);assert.equal(a.jobId,b.jobId);await f.read(a);assert.equal(f.requests.length,1);assert.equal((await f.service.tool('blender_generate',f.args,f.binding)).jobId,a.jobId);await assert.rejects(f.service.tool('blender_generate',{...f.args,name:'other'},f.binding),/INVOCATION_CHANGED/);});
test('incomplete native recovery blocks generation and is retried after the external state changes',async t=>{const f=await fixture(t);let blocked=true,count=0;const service=createBlenderJobs(f.core,{...f.options,recover:async()=>{count++;if(blocked)throw Error('BLENDER_RECOVERY_INCOMPLETE');return {verified:true,reclaimed:1};}});assert.equal((await service.status()).reason,'BLENDER_RECOVERY_INCOMPLETE');await assert.rejects(service.tool('blender_generate',f.args,f.binding),/RECOVERY_INCOMPLETE/);assert.equal(f.requests.length,0);blocked=false;assert.equal((await service.status()).available,true);await service.status();assert.equal(count,3);await service.stop();await service.start();assert.equal(count,4);await service.stop();});
test('runtime lock and native executable must both match host-selected broker identity',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'cm-bl-pin-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.mkdir(path.join(root,'broker'));await fs.mkdir(path.join(root,'runtime'));const executable=Buffer.from('test-broker'),runtime=Buffer.from('test-runtime');await fs.writeFile(path.join(root,'broker','blender-host-broker.exe'),executable);await fs.writeFile(path.join(root,'runtime','blender.exe'),runtime);const files=[{path:'blender.exe',bytes:runtime.length,sha256:native.hash(runtime)}];const lock={format:'craftmine.blender-toolchain/1',runtimeVersion:'5.2.1',files};const identity={format:'craftmine.blender-broker-identity/1',bytes:executable.length,sha256:native.hash(executable),runtimeVersion:'5.2.1',runtimeInventoryDigest:native.hash(JSON.stringify(files))};const toolchain={runtimeRoot:root,broker:path.join(root,'broker','blender-host-broker.exe'),brokerIdentity:path.join(root,'broker','broker-identity.json'),toolchainLock:path.join(root,'toolchain.lock.json')};await fs.writeFile(toolchain.brokerIdentity,JSON.stringify(identity));await fs.writeFile(toolchain.toolchainLock,JSON.stringify(lock));assert.equal((await native.discover(toolchain)).runtimeVersion,'5.2.1');await fs.writeFile(toolchain.broker,'forged');await assert.rejects(native.discover(toolchain),/BROKER_PIN_MISMATCH/);await fs.writeFile(toolchain.broker,executable);lock.files[0].sha256='0'.repeat(64);await fs.writeFile(toolchain.toolchainLock,JSON.stringify(lock));await assert.rejects(native.discover(toolchain),/RUNTIME_PIN_MISMATCH/);});
