import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
const root=path.resolve('desktop/godot/components/canine-visuals'),manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));
function read(item){const bytes=fs.readFileSync(path.join(root,item.file));assert.equal(createHash('sha256').update(bytes).digest('hex'),item.sha256);assert.equal(bytes.readUInt32LE(0),0x46546c67);assert.equal(bytes.readUInt32LE(4),2);assert.equal(bytes.readUInt32LE(8),bytes.length);const length=bytes.readUInt32LE(12);assert.equal(bytes.readUInt32LE(16),0x4e4f534a);const json=JSON.parse(bytes.subarray(20,20+length).toString());const start=20+length;assert.equal(bytes.readUInt32LE(start+4),0x004e4942);const binary=bytes.subarray(start+8);assert.equal(bytes.readUInt32LE(start),binary.length);return{json,binary};}
function values(json,binary,index){const a=json.accessors[index],view=json.bufferViews[a.bufferView],count=a.count*({SCALAR:1,VEC3:3,VEC4:4}[a.type]);assert.equal(a.componentType,5126);const offset=(view.byteOffset??0)+(a.byteOffset??0);assert.ok(offset+count*4<=binary.length);return Array.from({length:count},(_,i)=>binary.readFloatLE(offset+i*4));}
for(const item of manifest.items)test(item.appearanceKey+' is self-contained finite polygon geometry with actual node animations',()=>{
 const{json,binary}=read(item);assert.equal(json.asset.version,'2.0');assert.equal(json.buffers.length,1);assert.equal(json.buffers[0].uri,undefined);assert.equal(json.buffers[0].byteLength,binary.length);assert.equal(json.images,undefined);assert.equal(json.skins,undefined);assert.equal(json.nodes.filter(n=>n.mesh!==undefined).length,7);assert.equal(item.restBoundsMetres.min[1],0);
 let triangles=0;for(const mesh of json.meshes){assert.ok(mesh.primitives.length<=8);for(const primitive of mesh.primitives){assert.equal(primitive.mode,4);assert.ok(json.materials[primitive.material]);const positions=values(json,binary,primitive.attributes.POSITION),normals=values(json,binary,primitive.attributes.NORMAL);assert.equal(positions.length,normals.length);assert.equal(positions.length%9,0);triangles+=positions.length/9;assert.ok(positions.every(x=>Number.isFinite(x)&&Math.abs(x)<4));for(let i=0;i<normals.length;i+=3)assert.ok(Math.abs(Math.hypot(...normals.slice(i,i+3))-1)<1e-5);}}
 assert.equal(triangles,item.triangles);assert.ok(triangles<3000);assert.deepEqual(json.animations.map(a=>a.name),['idle','walk']);
 for(const animation of json.animations){let moving=0;for(const channel of animation.channels){assert.ok(json.nodes[channel.target.node]);const sampler=animation.samplers[channel.sampler],times=values(json,binary,sampler.input),data=values(json,binary,sampler.output),stride=channel.target.path==='rotation'?4:3;assert.equal(sampler.interpolation,'LINEAR');assert.ok(['rotation','translation'].includes(channel.target.path));assert.equal(data.length,times.length*stride);assert.equal(times[0],0);assert.ok(times.every((t,i)=>Number.isFinite(t)&&(i===0||t>times[i-1])));assert.ok(data.every(Number.isFinite));const target=json.nodes[channel.target.node];if(channel.target.path==='rotation'){const axis=target.name==='HeadPivot'?1:target.name==='TailPivot'?2:/^(Fore|Hind)[LR]$/.test(target.name)?0:-1;assert.ok(axis>=0,'Analytic envelope only supports declared rigid axes');for(let i=0;i<data.length;i+=4){assert.ok(Math.abs(Math.hypot(...data.slice(i,i+4))-1)<1e-6);if(target.name==='TailPivot')assert.ok(Math.abs(2*Math.atan2(data[i+axis],data[i+3]))<=item.motionEnvelope.assumptions.tailAngleMaxRadians+1e-6);for(let j=0;j<3;j++)if(j!==axis)assert.ok(Math.abs(data[i+j])<1e-7);}}else{assert.ok(target.name==='BodyPivot'||/^(Fore|Hind)[LR]$/.test(target.name));const maxLift=target.name==='BodyPivot'?item.motionEnvelope.assumptions.bodyTranslationYMax:item.motionEnvelope.assumptions.walkLegLiftLocalMetres+1e-6;for(let i=0;i<data.length;i+=3){assert.equal(data[i],Math.fround(target.translation[0]));assert.equal(data[i+2],Math.fround(target.translation[2]));assert.ok(data[i+1]>=target.translation[1]-1e-6&&data[i+1]<=target.translation[1]+maxLift);}}if(data.some((v,i)=>Math.abs(v-data[i%stride])>0.001))moving++;for(let i=0;i<stride;i++)assert.ok(Math.abs(data[i]-data[data.length-stride+i])<1e-6,'In-place animation must close without a pose jump');}assert.ok(moving>=3);}
});
test('dog and white Pomeranian have distinct modelled silhouettes, not a palette-only swap',()=>{const[a,b]=manifest.items;assert.notEqual(a.triangles,b.triangles);assert.ok(a.restBoundsMetres.size[2]>b.restBoundsMetres.size[2]*2);assert.ok(a.restBoundsMetres.size[1]>b.restBoundsMetres.size[1]*1.5);assert.ok(b.restBoundsMetres.size[0]/b.restBoundsMetres.size[2]>a.restBoundsMetres.size[0]/a.restBoundsMetres.size[2]*1.5);});

test('checked engine motion evidence binds these exact GLBs and lies within continuous envelope',()=>{const evidence=JSON.parse(fs.readFileSync(path.join(root,manifest.motionEvidence)));for(const item of manifest.items){assert.equal(evidence.geometryAndAnimationSource.find(v=>v.appearanceKey===item.appearanceKey).sha256,item.sha256);const e=evidence.measurements.find(v=>v.appearanceKey===item.appearanceKey);assert.ok(e.vertexSamples>1000000);assert.equal(e.yMin,0);assert.ok(e.radiusMax<=item.motionEnvelope.radiusMax);assert.ok(e.yMin>=item.motionEnvelope.yMin);assert.ok(e.yMax<=item.motionEnvelope.yMax);}});
