import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {createRequire}from'node:module';
import {CoreClient}from'../plugins/craftmine-world/core-client.cjs';import {createManagedPackageInstaller}from'../plugins/craftmine-world/reuse-service.mjs';import{unpackStaticPackage}from'../plugins/craftmine-world/package-zip.mjs';import{buildBuiltinCombatPackage,COMBAT_ASSET_ID}from'../desktop/build-builtin-combat-package.mjs';
const require=createRequire(import.meta.url),{createSourceLibraryService}=require(process.env.CRAFTMINE_SOURCE_LIBRARY_PLUGIN?path.join(path.resolve(process.env.CRAFTMINE_SOURCE_LIBRARY_PLUGIN),'source-library-service.cjs'):'../plugins/craftmine-world/source-library-service.cjs'),{archiveInstallation,assessArchiveForSource}=require('../plugins/craftmine-world/source-library-read-hints.cjs');
test('declaration preflight explains the immutable v1 failure even when target source is unavailable',()=>{
 const old=unpackStaticPackage(buildBuiltinCombatPackage({version:1}).bytes),next=unpackStaticPackage(buildBuiltinCombatPackage().bytes),hint=archiveInstallation(old);
 assert.equal(hint.status,'blocked-declaration');assert.equal(hint.resources[0].reason,'PACKAGE_SINGLE_ENTITY_DECLARATION_REQUIRED');assert.equal(hint.resources[0].parameterChangeCanFix,false);assert.equal(hint.resources[0].automaticInstance,null);assert.deepEqual(hint.resources[0].recovery.searchRequest,{mode:'search',query:COMBAT_ASSET_ID});
 const unavailable=assessArchiveForSource(old,{available:false,reason:'READ_UNAVAILABLE',source:null});assert.equal(unavailable.status,'installation-declaration-blocked');assert.equal(unavailable.sourcePrerequisitesStatus,'unknown');
 const current=archiveInstallation(next);assert.equal(current.status,'declared');assert.equal(current.resources[0].automaticInstance.entity,'monster-one');assert.equal(current.resources[0].behaviorSetup.requiredManualNodes[0].countPerPlayer,1);assert.equal(current.runtimeVerified,false);
});

test('real Core source installer refuses v1 unchanged and installs two independent v2 monsters with all helper files',{skip:!process.env.CRAFTMINE_CORE_BIN},async t=>{
 await fs.mkdir('test-results',{recursive:true});const root=await fs.mkdtemp(path.resolve('test-results/combat-install-contract-')),core=new CoreClient(process.env.CRAFTMINE_CORE_BIN,path.join(root,'core'));
 const worldId='combat-contract-world',context={projectId:'contract-project',sessionId:'contract-session',turnId:'contract-turn'},calls=[],report={worldId,root,engineStarted:false,modelCalls:0};
 const call=async(method,args)=>{calls.push(method);return core.call(method,args,120000);};t.after(async()=>{await core.stop();await fs.writeFile(path.join(root,'report.json'),JSON.stringify({...report,calls},null,2));});await core.start();
 await call('world.create',{id:worldId,title:'Combat contract CPU fixture',world:{build:{id:'base-contract',scene:{format:'craftmine.scene/3',objects:[]}},snapshot:{format:'craftmine.progress/1',player:{x:0.5,y:7.6,z:0.5,yaw:0,pitch:0}},extensions:[]}});
 await call('workspace.open',{context,selectedWorld:worldId});await call('godotProject.create',{context,worldId,toolCallId:'create-source',baseBuild:'base-contract',baseId:'creation-sandbox',files:[{path:'project.godot',text:'config_version=5\n[application]\nrun/main_scene="res://scenes/creation.tscn"\n'},{path:'scenes/creation.tscn',text:'[gd_scene format=3]\n[node name="World" type="Node3D"]\n'}]});await call('content.migrate.apply',{worldId});
 const refs=[];for(const version of[1,2]){const p=buildBuiltinCombatPackage({version}),file=path.join(root,p.file);await fs.writeFile(file,p.bytes);await call('asset.import',{operationId:'seed-combat-'+version,sourceRoot:root,sourcePath:file,assetId:COMBAT_ASSET_ID,version,kind:'module',mediaKind:'package',path:p.file,mediaType:'application/x-godot-package',displayName:p.entry.label,source:p.entry.source,tags:['combat']});const r=await call('asset.read',{assetId:COMBAT_ASSET_ID,version});refs.push({assetId:COMBAT_ASSET_ID,version,contentHash:r.version_.contentHash});}
 const installer=createManagedPackageInstaller({call,enqueue:async()=>{},stagingRoot:path.join(root,'installs'),bind:async(worldId,operationId)=>{const worldRecord=await call('world.read',{id:worldId}),status=await call('content.status',{worldId}),index=await call('godotProject.index',{context,worldId,offset:0,limit:1});return{context,worldRecord,operation:{operationId,worldId,repoId:status.repoId,branchId:index.branchId,expectedHeadOid:status.branches.find(b=>b.name==='refs/heads/'+index.branchId).oid,expectedAppliedOid:status.appliedOid,expectedProgressRevision:worldRecord.revision}};}});
 const service=createSourceLibraryService({call,installSource:installer,installSourceGroup:args=>installer.group(args),directory:path.join(root,'proposals')});
 const old=await service.tool({mode:'read',ref:refs[0]},context,worldId,'read-v1');assert.equal(old.automaticInstallation.status,'blocked-declaration');assert.match(old.note,/changing tool parameters cannot repair/);assert.equal(old.automaticInstallation.resources[0].parameterChangeCanFix,false);
 const proposal=await service.tool({mode:'propose',ref:refs[0]},context,worldId,'propose-v1'),before=await call('godotProject.index',{context,worldId,offset:0,limit:32});await assert.rejects(service.installProposal({worldId,proposalId:proposal.proposal.proposalId}),/PACKAGE_SINGLE_ENTITY_DECLARATION_REQUIRED/);const rejected=await call('godotProject.index',{context,worldId,offset:0,limit:32});assert.equal(rejected.manifestHash,before.manifestHash);assert.equal(rejected.revision,before.revision);assert(!calls.includes('godotProject.applyFiles'));
 const found=await service.tool({mode:'search',query:COMBAT_ASSET_ID},context,worldId,'search-v2');assert(found.result.items.some(item=>item.version===2&&item.targetCompatibility.automaticInstallation.status==='declared'));
 const group=await service.tool({mode:'propose-group',items:[{ref:refs[1],position:{x:5,y:0,z:-4}},{ref:refs[1],position:{x:-5,y:0,z:-4}}]},context,worldId,'propose-v2');const installed=await service.installProposal({worldId,proposalId:group.proposal.proposalId});assert.equal(installed.applied,false);assert.equal(installed.instanceIds.length,2);assert.equal(new Set(installed.instanceIds).size,2);
 const after=await call('godotProject.index',{context,worldId,offset:0,limit:32});for(const name of['combat_vitals','sandbox_weapon','sandbox_monster']){assert(after.files.some(f=>f.path.endsWith('/scripts/'+name+'.gd')));assert(after.files.some(f=>f.path.endsWith('/scripts/'+name+'.gd.uid')));}
 const scene=await call('godotProject.read',{context,worldId,revision:after.revision,manifestHash:after.manifestHash,path:'scenes/creation.tscn',offset:0,limit:16000});assert.equal((scene.text.match(/type="CharacterBody3D"/g)??[]).length,2);assert(!scene.text.includes('scripts/combat_vitals.gd'));assert(!scene.text.includes('scripts/sandbox_weapon.gd'));assert.equal(calls.filter(m=>m==='godotProject.applyFiles').length,1);assert.equal(calls.filter(m=>m==='godotBuild.start').length,1);
 Object.assign(report,{passed:true,oldRef:refs[0],newRef:refs[1],installed,sourceRevision:after.revision,sourceManifestHash:after.manifestHash,autoMonsterInstances:2,autoVitalsInstances:0,autoWeaponInstances:0,checkExecution:'not-run-source-transaction-only'});
});
