import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{PROTECTED_CREATION_FILES,readPck4,readCreationProjectSelectors,verifyCreationPack}=require('../plugins/craftmine-world/godot-creation-pack.cjs');
const hash=(value,algorithm='sha256')=>createHash(algorithm).update(value).digest(),u32=value=>{const b=Buffer.alloc(4);b.writeUInt32LE(value);return b;},u64=value=>{const b=Buffer.alloc(8);b.writeBigUInt64LE(BigInt(value));return b;};
const string=value=>{const raw=Buffer.from(value),pad=Buffer.alloc((4-raw.length%4)%4);return Buffer.concat([u32(4),u32(raw.length),raw,pad]);};
const selectors=[['autoload/CraftmineRuntime','*res://craftmine_shared/runtime_bridge.gd'],['craftmine/runtime/adapter','res://craftmine_shared/base_adapter.gd']];
function project(entries=selectors){return Buffer.concat([Buffer.from('ECFG'),u32(entries.length),...entries.flatMap(([key,value])=>{const bytes=Buffer.isBuffer(value)?value:string(value);return [u32(Buffer.byteLength(key)),Buffer.from(key),u32(bytes.length),bytes];})]);}
function pack(entries){const header=Buffer.alloc(112);for(const [offset,value]of [[0,0x43504447],[4,4],[8,4],[12,7],[16,2],[20,2]])header.writeUInt32LE(value,offset);header.writeBigUInt64LE(112n,24);let offset=0;const chunks=[],directory=[];for(const item of entries){const bytes=Buffer.from(item.data),name=Buffer.from(item.path),padded=Buffer.concat([name,Buffer.alloc((4-name.length%4)%4)]);chunks.push(bytes);directory.push(Buffer.concat([u32(padded.length),padded,u64(offset),u64(bytes.length),hash(bytes,'md5'),u32(item.flags??0)]));offset+=bytes.length;}header.writeBigUInt64LE(BigInt(112+offset),32);return Buffer.concat([header,...chunks,u32(entries.length),...directory]);}
const files=()=>[...PROTECTED_CREATION_FILES.map(path=>({path,data:'extends RefCounted\n# '+path+'\n'})),{path:'project.binary',data:project()}];
const pins=entries=>entries.filter(e=>PROTECTED_CREATION_FILES.includes(e.path)).map(e=>({path:e.path,bytes:Buffer.byteLength(e.data),sha256:hash(e.data).toString('hex')}));
test('PCK independently binds actual packed scripts and compiled selectors to claimed source bytes',()=>{const entries=files(),result=verifyCreationPack(pack(entries),pins(entries));assert.equal(result.files.length,3);assert.equal(result.project.selectors['craftmine/runtime/adapter'],selectors[1][1]);});
test('exported script changes fail even with a freshly valid MD5 and unchanged source pin list',()=>{const entries=files(),expected=pins(entries);entries[0].data+='\n# tool changed this only in export copy\n';assert.throws(()=>verifyCreationPack(pack(entries),expected),/PROTECTED_MISMATCH/);});
test('compiled selector changes fail even when all three protected scripts match source',()=>{const entries=files();entries.at(-1).data=project([[selectors[0][0],'*res://forged.gd'],selectors[1]]);assert.throws(()=>verifyCreationPack(pack(entries),pins(entries)),/SELECTOR_MISMATCH/);});
test('resource remaps, duplicate paths, traversal, encrypted entries and format changes fail closed',()=>{
 for(const item of [{path:PROTECTED_CREATION_FILES[0]+'.remap',data:'path=res://forged.gd'},{path:PROTECTED_CREATION_FILES[0].replace('.gd','.gdc'),data:'compiled'},{path:'override.cfg',data:'override'}]){const entries=[...files(),item];assert.throws(()=>verifyCreationPack(pack(entries),pins(entries)));}
 for(const item of [{path:'../escape.gd',data:'x'},{path:PROTECTED_CREATION_FILES[0].toUpperCase(),data:'x'},{path:'encrypted.gd',data:'x',flags:1}])assert.throws(()=>readPck4(pack([...files(),item])));
 const b=pack(files());b.writeUInt32LE(3,4);assert.throws(()=>readPck4(b),/FORMAT_UNSUPPORTED/);
});
test('binary project reader skips only length-bounded unrelated variants and rejects selector aliases',()=>{
 assert.equal(Object.keys(readCreationProjectSelectors(project([...selectors,['unrelated',u32(28)]]))).length,2);
 for(const entries of [[...selectors,selectors[0]],[...selectors,['craftmine/runtime/adapter.web','res://forged.gd']],[selectors[0]],[[selectors[0][0],u32(2)],selectors[1]]])assert.throws(()=>readCreationProjectSelectors(project(entries)));
 const b=project();b.writeUInt32LE(0xffffffff,8);assert.throws(()=>readCreationProjectSelectors(b),/PROJECT_INVALID/);
});
test('truncation, out-of-range file offsets and raw data corruption are refused',()=>{const b=pack(files());assert.throws(()=>readPck4(b.subarray(0,b.length-1)));const corrupted=Buffer.from(b);corrupted[112]^=1;assert.throws(()=>readPck4(corrupted),/DIGEST_MISMATCH/);const invalid=Buffer.from(b);invalid.writeBigUInt64LE(2n**63n,32);assert.throws(()=>readPck4(invalid),/RANGE_INVALID/);});
