import test from'node:test';import assert from'node:assert/strict';import{allowedContinuationCase,stoppedOriginal,validateInheritedBudget,compareHarvestRestore,assertRejectedBeforeModel}from'./helpers/creation-model-continuation.mjs';
const budget={format:'craftmine.creation-evaluation-budget/1',limit:40,requests:Array.from({length:25},(_,i)=>'private-fixture-'+i)};
const original={format:'craftmine.creation-next-model/1',model:'deepseek-flash',provider:'deepseek',sessionId:'s',worldId:'w',launches:[{exit:{code:0}}],cases:[{id:'CA05',outcome:'failed',error:'WORLD_BUSY',modelRequests:11},{id:'CA06',outcome:'not_run',modelRequests:0}]};
test('only closed original artifact with its exact shared 25 reservation baseline is accepted',()=>{assert.equal(stoppedOriginal(original,budget).id,'CA05');assert.throws(()=>stoppedOriginal({...original,launches:[{exit:{code:null}}]},budget));assert.throws(()=>stoppedOriginal(original,{...budget,requests:[]}));});
test('prior attempted cases cannot be submitted and previously untouched continuation has one attempt',()=>{assert.equal(allowedContinuationCase(original,'CA06',[]),true);assert.equal(allowedContinuationCase(original,'CA06',['CA06']),false);assert.equal(allowedContinuationCase(original,'CA05',[]),false);assert.equal(allowedContinuationCase(original,'CA07',[]),false);});
test('continuation never resets or changes inherited reservation identity and caps the combined ledger at 40',()=>{assert.equal(validateInheritedBudget(budget,{...budget,requests:[...budget.requests,'new']} ).newReserved,1);assert.throws(()=>validateInheritedBudget(budget,{...budget,requests:['changed',...budget.requests.slice(1)]}));assert.throws(()=>validateInheritedBudget(budget,{...budget,requests:Array.from({length:41},(_,i)=>'r'+i)}));});
test('paused restore tolerates only verified countdown progression and rejects reset rewards or unrelated changes',()=>{const saved={body:{inventory:{wood:1},rules:{chop:{remainingFrames:280,chopped:true,chops:1}},player:{position:[0,1,6]}}};const restored=structuredClone(saved);restored.body.rules.chop.remainingFrames=276;assert.equal(compareHarvestRestore(saved,restored,'chop',4).equal,true);restored.body.inventory.wood=2;assert.equal(compareHarvestRestore(saved,restored,'chop',4).equal,false);restored.body.inventory.wood=1;restored.body.rules.chop.remainingFrames=300;assert.equal(compareHarvestRestore(saved,restored,'chop',4).equal,false);});
const rejected=()=>({attempt:{id:'CA07',request:'原话',submitted:false,modelRequests:0,startedAt:new Date(1000).toISOString(),finishedAt:new Date(2000).toISOString(),budgetAtStart:{reserved:31},promptResult:{ok:false,error:{code:'CREATION_TARGET_STALE'}}},turn:{id:'rejected-turn',status:'error',error_code:'CREATION_TARGET_STALE',input_tokens:0,output_tokens:0,usage_json:null,started_at:1100,ended_at:1200},messages:[{role:'user',text:'原话',is_error:0}],calls:0,gaps:0,interruptions:0,budget:{...budget,requests:Array.from({length:31},(_,i)=>'r'+i)}});
test('only the explicit stale target rejection with zero dispatch evidence can recover',()=>{assert.deepEqual(assertRejectedBeforeModel(rejected()),{reason:'rejected-before-model',turnId:'rejected-turn',modelRequests:0,reserved:31});});
test('a submitted attempt, any actual call, accounting uncertainty or changed budget cannot replay',()=>{
 for(const mutate of [x=>x.attempt.submitted=true,x=>x.attempt.modelRequests=1,x=>x.attempt.promptResult.ok=true,x=>x.attempt.promptResult.error.code='NETWORK_ERROR',x=>x.calls=1,x=>x.gaps=1,x=>x.interruptions=1,x=>x.turn.input_tokens=1,x=>x.turn.usage_json='{}',x=>x.messages.push({role:'assistant',text:'done'}),x=>x.budget.requests.pop()]){const sample=rejected();mutate(sample);assert.throws(()=>assertRejectedBeforeModel(sample));}
});
test('a different or unfinished turn cannot satisfy the failed attempt evidence',()=>{for(const mutate of [x=>x.turn.ended_at=null,x=>x.turn.started_at=999,x=>x.turn.ended_at=2001,x=>x.messages[0].text='another wish',x=>x.attempt.id='HOLDOUT01']){const sample=rejected();mutate(sample);assert.throws(()=>assertRejectedBeforeModel(sample));}});
