import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {collectGodotScenarioDiagnostic} from '../vendor/pi-desktop/apps/desktop/electron/main/godot-scenario-collector.ts';
const binding={jobId:'gjob-'+'a'.repeat(64),inputHash:'b'.repeat(64),worldId:'world',buildId:'gbd-'+'c'.repeat(64),baseId:'creation-sandbox'};
const plan={format:'craftmine.godot-scenario/1',fixtureRef:'host-fixture',steps:[{op:'walk',args:{forward:1,right:0,frames:60}},{op:'interact',args:{}}],assertions:[{id:'position',step:0,path:['state','player','position','2'],range:[-4,-2]},{id:'hit',step:1,path:['actionResult','interacted'],equals:true}]};
function fixture(){const controller=new AbortController(),calls=[];let tick=0;const runtime={worldId:binding.worldId,buildId:binding.buildId,instanceId:'instance',request:async(op,args)=>{calls.push({op,args});return op==='observe-envelope'?{result:{format:'craftmine.godot-observation/1',worldId:runtime.worldId,buildId:runtime.buildId,instanceId:runtime.instanceId,baseId:binding.baseId,sampledAt:new Date().toISOString(),payload:{creation:{physicsTick:++tick},player:{position:[0,.9,-3]},unwanted:'not copied'}}}:{result:{interacted:true}};}};return {runtime,controller,calls,options:{binding,runtime,plan:structuredClone(plan),signal:controller.signal}};}
test('collects exact actions with scoped real samples and keeps verdict non-authoritative',async()=>{const f=fixture(),r=await collectGodotScenarioDiagnostic(f.options);assert.equal(r.status,'passed');assert.equal(r.authority,'diagnostic-only');assert.equal(r.affectsCandidateReadiness,false);assert.deepEqual(f.calls.filter(c=>c.op!=='observe-envelope'),plan.steps);assert.equal(r.transcript.steps[0].observation.state.unwanted,undefined);});
test('observed unmet assertion remains failed without readiness authority',async()=>{const f=fixture();f.options.plan.assertions[0].range=[10,20];const r=await collectGodotScenarioDiagnostic(f.options);assert.equal(r.status,'failed');assert.equal(r.affectsCandidateReadiness,false);});
test('abort before start performs no transport work',async()=>{const f=fixture();f.controller.abort();const r=await collectGodotScenarioDiagnostic(f.options);assert.equal(r.reason,'SCENARIO_CANCELLED');assert.equal(f.calls.length,0);});
test('abort during an unresolved real action returns promptly and ignores late response',async()=>{const f=fixture(),original=f.runtime.request;let resolveAction,started;const dispatched=new Promise(r=>started=r);f.runtime.request=async(op,args)=>{if(op==='walk'){started();return new Promise(r=>resolveAction=r);}return original(op,args);};const pending=collectGodotScenarioDiagnostic(f.options);await dispatched;f.controller.abort();const r=await pending;assert.equal(r.status,'inconclusive');assert.equal(r.reason,'SCENARIO_CANCELLED');resolveAction({result:{}});await new Promise(r=>setImmediate(r));assert.equal(r.transcript.steps.length,0);assert.ok(!f.calls.some(c=>c.op==='interact'));});
test('identity changes and forged envelope identity stop before subsequent actions',async()=>{for(const mismatch of ['runtime','envelope']){const f=fixture(),original=f.runtime.request;f.runtime.request=async(op,args)=>{const r=await original(op,args);if(op==='walk'){if(mismatch==='runtime')f.runtime.instanceId='replacement';else f.runtime.request=async()=>({result:{...r.result,format:'craftmine.godot-observation/1',instanceId:'replacement'}});}return r;};const r=await collectGodotScenarioDiagnostic(f.options);assert.equal(r.status,'inconclusive');assert.ok(!f.calls.some(c=>c.op==='interact'));}});
test('caller mutation cannot replace a cloned frozen plan',async()=>{const f=fixture(),original=f.runtime.request;f.runtime.request=async(op,args)=>{f.options.plan.steps[0]={op:'save',args:{}};return original(op,args);};const r=await collectGodotScenarioDiagnostic(f.options);assert.equal(r.status,'passed');assert.ok(!f.calls.some(c=>c.op==='save'));});
test('invalid or unsupported plans and missing clocks never dispatch gameplay',async()=>{for(const kind of ['plan','base','clock','stale']){const f=fixture();if(kind==='plan')f.options.plan.steps[0]={op:'set-time',args:{hours:0}};if(kind==='base')f.options.binding={...binding,baseId:'first-person'};if(kind==='clock'||kind==='stale'){const original=f.runtime.request;f.runtime.request=async(op,args)=>{const r=await original(op,args);if(kind==='clock')delete r.result.payload.creation.physicsTick;else r.result.sampledAt='2000-01-01';return r;};}const r=await collectGodotScenarioDiagnostic(f.options);assert.equal(r.status,'inconclusive');assert.ok(f.calls.every(c=>c.op==='observe-envelope'));}});
test('verifier hook selects only host plans after authoritative checks and excludes diagnostics from readiness',()=>{const source=readFileSync(new URL('../vendor/pi-desktop/apps/desktop/electron/main/godot-build-verifier.ts',import.meta.url),'utf8');assert.ok(source.indexOf('if(this.scenarioDiagnostics)')>source.indexOf('targetFeedbackPassed=!!requirementsEvidence'));assert.match(source,/const passed = !halted && assertions.every/);assert.doesNotMatch(source,/assertions\.push\([^\n]*scenario/i);assert.match(source,/scenarioStop\.abort\(\)/);assert.match(source,/scenarioDiagnostics\(binding\)/);});
