import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{readGodotBuildWithWait:read}=require('../plugins/craftmine-world/godot-build-read-wait.cjs');
const params={context:{projectId:'project',sessionId:'session',turnId:'turn'},worldId:'world',jobId:'gjob-'+'a'.repeat(64)};
const job=(status='running',extra={})=>({jobId:params.jobId,worldId:'world',taskId:'task',buildId:'build',kind:'check',sourceRevision:1,manifestHash:'a'.repeat(64),status,stage:'export',...extra});
function fixture(statuses=['running','passed']){let clock=0,reads=0,active=true,selected=true;const calls=[];return {calls,get reads(){return reads;},set active(v){active=v;},set selected(v){selected=v;},options:{core:{call:async(method,input,timeout)=>{assert.equal(method,'godotBuild.read');assert.deepEqual(input,params);assert.ok(timeout>0&&timeout<=5000);calls.push(input);return job(statuses[Math.min(reads++,statuses.length-1)]);}},params,waitMs:30000,assertActive:()=>{if(!active)throw Error('TURN_ENDED');},assertSelected:async()=>{if(!selected)throw Error('WORLD_CHANGED');},now:()=>clock,pause:async ms=>{clock+=ms;}}};}
test('one model read waits for actual terminal result without writes or enqueues',async()=>{const f=fixture(['queued','claimed','running','passed']);const result=await read(f.options);assert.equal(result.status,'passed');assert.equal(result.waitReason,'terminal');assert.equal(result.waitedMs,1500);assert.equal(f.reads,4);});
for(const status of ['passed','failed','cancelled','interrupted','blocked'])test(status+' returns immediately',async()=>{const f=fixture([status]);const result=await read(f.options);assert.equal(result.status,status);assert.equal(result.waitedMs,0);assert.equal(f.reads,1);});
test('deadline returns last real state and sample age without inventing completion',async()=>{const f=fixture(['running']);const result=await read({...f.options,waitMs:1100});assert.equal(result.status,'running');assert.equal(result.waitReason,'deadline');assert.equal(result.waitedMs,1100);assert.equal(result.lastReadAgeMs,100);assert.equal(f.reads,3);});
test('zero wait performs one bounded immediate read',async()=>{const f=fixture(['running']);const result=await read({...f.options,waitMs:0});assert.equal(result.waitedMs,0);assert.equal(f.reads,1);});
test('cancellation during pause prevents further reads',async()=>{const f=fixture(['running']);await assert.rejects(read({...f.options,pause:async()=>{f.active=false;}}),/TURN_ENDED/);assert.equal(f.reads,1);});
test('world switch during wait rejects the result',async()=>{const f=fixture(['running']);await assert.rejects(read({...f.options,pause:async()=>{f.selected=false;}}),/WORLD_CHANGED/);assert.equal(f.reads,1);});
for(const change of [{worldId:'foreign'},{jobId:'foreign'},{buildId:'changed'},{taskId:'changed'},{status:'invented'}])test('different identity or unknown status cannot finish the original read: '+JSON.stringify(change),async()=>{const f=fixture(['running']);let count=0;f.options.core.call=async()=>job('running',++count===1?{}:change);await assert.rejects(read(f.options),/IDENTITY_CHANGED/);});
test('caller or transport mutation cannot change later request binding',async()=>{const f=fixture(['running']);let calls=0;const original=structuredClone(params);f.options.core.call=async(method,input)=>{assert.deepEqual(input,original);input.context.turnId='forged';input.worldId='foreign';return job(++calls===1?'running':'passed');};assert.equal((await read(f.options)).status,'passed');assert.deepEqual(params,original);});
test('hung core read is bounded even when a fixture ignores the RPC timeout',async()=>{const start=Date.now(),f=fixture();await assert.rejects(read({...f.options,core:{call:()=>new Promise(()=>{})},readTimeoutMs:30}),/BUILD_READ_TIMEOUT/);assert.ok(Date.now()-start<500);});
test('cancelled turn interrupts a pending real timer read before its deadline',async()=>{const f=fixture(),start=Date.now();const timer=setTimeout(()=>{f.active=false;},25);try{await assert.rejects(read({...f.options,core:{call:()=>new Promise(()=>{})},readTimeoutMs:1000}),/TURN_ENDED/);assert.ok(Date.now()-start<500);}finally{clearTimeout(timer);}});
test('a slow subsequent read returns truthful stale age and timeout reason',async()=>{const f=fixture(['running']);let count=0;f.options.core.call=()=>++count===1?Promise.resolve(job()):new Promise(()=>{});const result=await read({...f.options,readTimeoutMs:20});assert.equal(result.status,'running');assert.equal(result.waitReason,'read-timeout');assert.equal(result.lastReadAgeMs,500);});
test('invalid wait configuration and extra request identity fail before core',async()=>{const f=fixture();for(const waitMs of [-1,30001,NaN,1.5,'30'])await assert.rejects(read({...f.options,waitMs}),/WAIT_INVALID/);await assert.rejects(read({...f.options,params:{...params,script:'fake'}}),/BINDING_INVALID/);assert.equal(f.reads,0);});
