import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
import {resolveTranscriptTruncation} from '../vendor/pi-desktop/packages/shared/src/transcript-truncation.ts';
const require=createRequire(new URL('../vendor/pi-desktop/apps/desktop/package.json',import.meta.url)),{transformSync}=require('esbuild');
// Execute the actual ordinary main-process branch, rather than reproducing its
// save/truncate algorithm in the fixture. Runtime launch lies outside this slice.
const main=fs.readFileSync(new URL('../vendor/pi-desktop/apps/desktop/electron/main/index.ts',import.meta.url),'utf8'),start=main.indexOf('    const allMessages = Array.isArray(session.messages) ? session.messages : [];'),end=main.indexOf('    const launch = await resolveAgentRuntimeLaunch(',start);assert.ok(start>=0&&end>start);
const code=transformSync('(async()=>{'+main.slice(start,end)+'return {session,req};})()',{loader:'ts',target:'es2022'}).code;
async function run(failSave=false){const old={id:'old',role:'assistant',content:'保留旧会话'},failed={id:'failed-user',role:'user',content:'原愿望'},stored={session:{id:'session',messages:[old,failed]},revisions:[]},calls=[];
 const host={call:async(method,args)=>{calls.push({method,args:JSON.parse(JSON.stringify(args))});if(method==='session.listRevisions')return {revisions:stored.revisions};if(method==='session.saveRevision'){if(failSave)throw Error('PERSISTENCE_FAILED');stored.revisions.push({revisionIndex:1,isActive:false,messages:args.messages});return{};}if(method==='session.replaceMessages'){stored.session={...stored.session,messages:args.messages};return{};}if(method==='session.get')return {session:stored.session};throw Error('Unexpected '+method);}};
 const context={session:stored.session,req:{sessionId:'session',content:'原愿望',truncateFromMessageId:'failed-user'},resolveTranscriptTruncation,host,sidecar:null,ErrorCodes:{NOT_FOUND:'NOT_FOUND'},logger:{app(){}}};
 let result,error;try{result=await vm.runInNewContext(code,context);}catch(e){error=e;}return {calls,stored,result,error};
}
test('ordinary retry archives original failed branch before replacing the live tail',async()=>{const r=await run();assert.equal(r.error,undefined);const archived=r.calls.findIndex(c=>c.method==='session.saveRevision'),cut=r.calls.findIndex(c=>c.method==='session.replaceMessages');assert.ok(archived>=0&&cut>archived);assert.equal(r.stored.revisions[0].messages[0].id,'failed-user');assert.equal(r.stored.revisions[0].messages[0].content,'原愿望');assert.deepEqual(r.stored.session.messages.map(m=>m.id),['old']);assert.equal(r.result.req.__revisionMeta.rootUserId,'failed-user');});
test('failed revision persistence aborts ordinary retry without truncating the original failed user',async()=>{const r=await run(true);assert.match(r.error.message,/PERSISTENCE_FAILED/);assert.equal(r.calls.some(c=>c.method==='session.replaceMessages'),false);assert.deepEqual(r.stored.session.messages.map(m=>m.id),['old','failed-user']);});
