import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {test} from 'node:test';import {stripTypeScriptTypes} from 'node:module';import {EventEmitter} from 'node:events';
const root=process.cwd(),dir=path.join(root,'vendor/pi-desktop/apps/desktop/electron/main');const read=file=>fs.readFileSync(path.join(dir,file),'utf8');
const ticks=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
const awaitOwnedClose=vm.runInNewContext(stripTypeScriptTypes(read('owned-resource-close.ts'),{mode:'transform'}).replaceAll('export function','function')+'\nawaitOwnedClose',{setTimeout,clearTimeout});
const closeBody=stripTypeScriptTypes(read('owned-view-close.ts'),{mode:'transform'});const OwnedViewClose=vm.runInNewContext(closeBody.slice(closeBody.indexOf('export class')).replace('export class','class')+'\nOwnedViewClose',{setTimeout,clearTimeout,awaitOwnedClose});
function load(file,name,globals={}){const source=stripTypeScriptTypes(read(file),{mode:'transform'});return vm.runInNewContext(source.slice(source.indexOf('export class '+name)).replace('export class '+name,'class '+name)+'\n'+name,{setTimeout,clearTimeout,OwnedViewClose,pluginViewKey:(a,b)=>a+'/'+b,resolveLocalFile:()=>null,normalizeUrl:x=>x,...globals});}
const BrowserPane=load('browser-view.ts','BrowserPane'),PluginViewHost=load('plugin-view-host.ts','PluginViewHost');
function contents(mode='deferred'){const wc=new EventEmitter();wc.destroyed=false;wc.closeCount=0;wc.isDestroyed=()=>wc.destroyed;wc.finish=()=>{wc.destroyed=true;wc.emit('destroyed');};wc.close=()=>{wc.closeCount++;if(mode==='throw')throw Error('fixed close failure');if(mode==='sync')wc.finish();};return wc;}
function plugin(entries){const owner=new PluginViewHost();owner.retiring=new OwnedViewClose('PLUGIN_TEST',30);for(const [id,wc]of entries)owner.views.set(id,{key:id,pluginId:id.split('/')[0],view:{webContents:wc},usedAt:1});return owner;}
function browser(wc){const owner=new BrowserPane(()=>{});owner.retiring=new OwnedViewClose('BROWSER_TEST',30);owner.view={webContents:wc};owner.contents=wc;return owner;}
test('owned close registers before synchronous destroyed and reuses the same promise',async()=>{const closer=new OwnedViewClose('FIXTURE',30),wc=contents('sync');const a=closer.close(wc),b=closer.close(wc);assert.equal(a,b);await a;await closer.drain();assert.equal(wc.closeCount,1);assert.equal(closer.closing.size,0);});
test('browser dispose shares one promise and retains renderer until delayed destroyed',async()=>{const wc=contents(),owner=browser(wc);const first=owner.dispose();assert.equal(owner.dispose(),first);let done=false;first.then(()=>done=true);await ticks();assert.equal(done,false);assert.equal(owner.retiring.closing.size,1);assert.equal(owner.getWebContents(),null);wc.finish();await first;assert.equal(owner.retiring.closing.size,0);});
test('timeout is rejected, retained as failure, and late destruction only releases the reference',async()=>{const wc=contents(),owner=browser(wc);const promise=owner.dispose();await assert.rejects(promise,/CLOSE_INCOMPLETE/);assert.equal(owner.retiring.closing.size,1);assert.equal(owner.dispose(),promise);wc.finish();await ticks();assert.equal(owner.retiring.closing.size,0);await assert.rejects(owner.dispose(),/CLOSE_INCOMPLETE/);});
test('one plugin close throw does not prevent other views closing and cannot report success',async()=>{const bad=contents('throw'),good=contents(),owner=plugin([['a/one',bad],['b/two',good]]);const promise=owner.dispose();assert.equal(promise,owner.dispose());const failed=assert.rejects(promise,/CLOSE_INCOMPLETE/);await ticks();assert.equal(bad.closeCount,1);assert.equal(good.closeCount,1);assert.equal(owner.retiring.closing.size,2);good.finish();await failed;assert.equal(owner.retiring.closing.size,1);bad.finish();});
test('an earlier eviction failure is still reported at owner disposal',async()=>{const bad=contents('throw'),owner=plugin([['a/one',bad]]);await assert.rejects(owner.destroy('a/one'),/fixed close failure/);assert.equal(owner.views.size,0);await assert.rejects(owner.dispose(),/CLOSE_INCOMPLETE/);bad.finish();});
test('disposed owners reject new views before creating or navigating',async()=>{const b=new BrowserPane(()=>{}),p=new PluginViewHost();await Promise.all([b.dispose(),p.dispose()]);assert.throws(()=>b.navigate('https://example.invalid'),/DISPOSED/);await assert.rejects(b.navigateAndWait('https://example.invalid'),/DISPOSED/);assert.throws(()=>p.open({pluginId:'a',viewId:'one'}),/DISPOSED/);});
test('late plugin factory return after disposal is retired instead of inserted',async()=>{const owner=new PluginViewHost(),wc=contents('sync');owner.createView=()=>{owner.dispose();return {webContents:wc};};assert.throws(()=>owner.open({pluginId:'a',viewId:'one'}),/DISPOSED/);await owner.dispose();assert.equal(owner.views.size,0);assert.equal(wc.closeCount,1);});
test('pending browser navigation cannot return a new or disposed surface',async()=>{const wc=contents(),owner=browser(wc);let resolve;wc.loadURL=()=>new Promise(r=>resolve=r);const navigation=owner.navigateAndWait('https://example.invalid',null,100);const rejected=assert.rejects(navigation,/DISPOSED/);const closed=owner.dispose();await ticks();wc.finish();resolve();await Promise.all([closed,rejected]);});
test('close after an async preparation cannot destroy a replacement with the same key',async()=>{const old=contents('sync'),fresh=contents('sync'),owner=plugin([['a/one',old]]);let resolve;owner.prepareEntries=()=>new Promise(r=>resolve=r);const closing=owner.close('a','one');owner.views.set('a/one',{key:'a/one',pluginId:'a',view:{webContents:fresh}});resolve();await closing;assert.equal(old.closeCount,1);assert.equal(fresh.closeCount,0);await owner.dispose();});
const main=read('index.ts'),start=main.indexOf('  shutdownPromise = (async () => {'),end=main.indexOf('\n});\n\napp.on("activate"',start);assert.ok(start>0&&end>start);const shutdown=stripTypeScriptTypes('async function run(){'+main.slice(start,end)+';return shutdownPromise;}');
function mainContext(browserPane,pluginViews){const events=[];const owner=name=>({dispose(){events.push(name);return Promise.resolve();}});return {events,context:{shutdownPromise:null,shutdownComplete:false,assetPreviews:owner('assets'),godotExports:owner('exports'),settleRunningTurnsForQuit:()=>Promise.resolve(),host:owner('host'),pluginPanels:{closeAll:()=>Promise.resolve()},updater:owner('updater'),logger:{app(){}},plugins:{disposeAll:()=>Promise.resolve()},userMcp:{disposeAll:()=>Promise.resolve()},browserPane,pluginViews,godotWorld:owner('godot'),inflightCheckpointer:owner('checkpoint'),sidecar:owner('sidecar'),recordHeadlessShutdownFailure:name=>events.push('failure:'+name),app:{quit:()=>events.push('releaseQuit')}}};}
test('actual Main shutdown waits for both renderer barriers before releaseQuit',async()=>{const b=contents(),p=contents(),f=mainContext(browser(b),plugin([['a/one',p]]));const running=vm.runInNewContext(shutdown+'\nrun()',f.context);await ticks();assert.ok(!f.events.includes('releaseQuit'));b.finish();await ticks();assert.ok(!f.events.includes('releaseQuit'));p.finish();await running;await ticks();assert.ok(f.events.includes('releaseQuit'));});
test('actual Main captures a synchronous owner throw and still starts all other owners',async()=>{const f=mainContext({dispose(){throw Error('fixed browser exception');}},{dispose:()=>Promise.resolve()});await vm.runInNewContext(shutdown+'\nrun()',f.context);await ticks();assert.ok(f.events.includes('godot'));assert.ok(f.events.includes('sidecar'));assert.ok(f.events.includes('failure:browser-pane'));assert.ok(f.events.includes('releaseQuit'));});

test('late prepared close keeps the original contents after Electron clears the view property',async()=>{const wc=contents('sync'),owner=plugin([['a/one',wc]]);const entry=owner.views.get('a/one');wc.on('destroyed',()=>{entry.view.webContents=undefined;});let resolve;owner.prepareEntries=()=>new Promise(r=>resolve=r);const prepared=owner.close('a','one');await owner.dispose();resolve();await prepared;assert.equal(wc.closeCount,1);});

const BrowserHost=load('browser-host.ts','BrowserHost',{BrowserCdp:class{detach(){}}});
test('guest retirement is observed and the application pane can navigate again after plugin reload',async()=>{const old=contents(),pane=browser(old),host=new BrowserHost({pane});const pending=host.disposeGuest();let done=false;pending.then(()=>done=true);await ticks();assert.equal(done,false);old.finish();await pending;assert.equal(pane.disposed,false);const fresh=contents('sync');fresh.loadURL=async()=>{};fresh.getURL=()=>'';fresh.getTitle=()=>'';fresh.isLoading=()=>false;fresh.navigationHistory={canGoBack:()=>false,canGoForward:()=>false};pane.view={webContents:fresh};pane.contents=fresh;await pane.navigateAndWait('https://example.invalid',null,100);await pane.dispose();assert.equal(fresh.closeCount,1);});
test('guest detach failure still starts renderer close and returns an observable rejection',async()=>{const wc=contents('sync'),pane=browser(wc),host=new BrowserHost({pane});host.cdp.detach=()=>{throw Error('detach failed');};await assert.rejects(host.disposeGuest(),/BROWSER_GUEST_CLOSE_INCOMPLETE/);assert.equal(wc.closeCount,1);await pane.dispose();});
test('guest close timeout is propagated and stays visible at final owner shutdown',async()=>{const wc=contents(),pane=browser(wc),host=new BrowserHost({pane});await assert.rejects(host.disposeGuest(),/BROWSER_GUEST_CLOSE_INCOMPLETE/);await assert.rejects(pane.dispose(),/CLOSE_INCOMPLETE/);wc.finish();});
test('late old guest navigation cannot return the replacement guest',async()=>{const wc=contents(),pane=browser(wc);let resolve;wc.loadURL=()=>new Promise(r=>resolve=r);const navigation=pane.navigateAndWait('https://example.invalid',null,100);const rejected=assert.rejects(navigation,/BROWSER_VIEW_CHANGED/);const close=pane.closeGuest();wc.finish();await close;const fresh=contents('sync');pane.view={webContents:fresh};pane.contents=fresh;resolve();await rejected;await pane.dispose();});
for(const stage of ['godotExports','settleRunningTurnsForQuit'])test('Main records '+stage+' rejection and still closes every later owner',async()=>{const f=mainContext({dispose:()=>Promise.resolve()},{dispose:()=>Promise.resolve()});if(stage==='godotExports')f.context.godotExports={dispose(){throw Error('fixed export failure');}};else f.context.settleRunningTurnsForQuit=async()=>{throw Error('fixed settlement failure');};await vm.runInNewContext(shutdown+'\nrun()',f.context);await ticks();assert.ok(f.events.includes('host'));assert.ok(f.events.includes('sidecar'));assert.ok(f.events.includes('failure:'+(stage==='godotExports'?'godot-exports':'settle-running-turns')));assert.ok(f.events.includes('releaseQuit'));});
