import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {compileScene,upgradeScene,INITIAL_SNAPSHOT} from '../../../app/scene.mjs';
import {sourceFixture} from './fixtures/applied-source.mjs';
const require=createRequire(import.meta.url);
const {CoreClient}=require('../../../plugins/craftmine-world/core-client.cjs');
const {createWorkbenchService}=require('../../../plugins/craftmine-world/workbench-service.cjs');
assert.ok(process.env.CRAFTMINE_CORE_BIN&&process.env.CRAFTMINE_DOMAIN_MODULE,'Supply isolated copied Rust binary and actual A domain bundle');
const {createLibraryService,createMemoryService}=require(path.resolve(process.env.CRAFTMINE_DOMAIN_MODULE));
const context={projectId:'c-source-project',sessionId:'c-source-session',turnId:'c-source-turn'};
const empty=upgradeScene({format:'craftmine.scene/1',title:'Fixture',night:false,objects:[]});
const source=upgradeScene({format:'craftmine.scene/1',title:'Fixture',night:false,objects:[{id:'oak-tree',name:'真实库测试树',position:{x:0,y:6,z:0},parts:[{offset:{x:0,y:0,z:0},size:{x:1,y:3,z:1},material:'wood'}]}]});
const build=scene=>{const compiled=compileScene(scene);return {...compiled,behaviors:compiled.behaviors||[],id:'v-'+compiled.hash.slice(0,20)};};
const applied=sourceFixture({context,empty,source,build,INITIAL_SNAPSHOT});
test('actual Rust workbench service enforces scope, provenance, exact reuse and validated context',async t=>{
  fs.mkdirSync('test-results',{recursive:true});const directory=fs.mkdtempSync(path.resolve('test-results/dispatch-c-service-'));
  const core=new CoreClient(process.env.CRAFTMINE_CORE_BIN,directory);t.after(()=>core.stop());await core.start();
  const call=(method,args)=>core.call(method,args,15000),queued=[];let selectedWorld='source-world';
  const library=createLibraryService({call}),memory=createMemoryService({call});
  const service=createWorkbenchService(core,{library,memory,verifications:{enqueue:(job,owner)=>queued.push({job,owner})},getSettings:async()=>({activeWorldId:selectedWorld})});
  const host={...context,context,selectedWorld,active:false};
  await applied(call);
  const invoke=(channel,payload={},owner=host)=>service.handle(channel,{worldId:owner.selectedWorld,...payload},owner);
  const cap=await invoke('workbench.capabilities');assert.ok(cap.channels.includes('library.install'));assert.ok(!cap.channels.includes('workbench.prepareAction'));assert.ok(!cap.channels.includes('backup.restore'));
  await assert.rejects(invoke('memory.search',{sessionId:'forged'}),/UNKNOWN_FIELD/);
  await assert.rejects(invoke('memory.search',{worldId:'different'}),/SELECTED_WORLD/);
  await assert.rejects(invoke('library.capture',{operationId:'capture-unproven',kind:'object',resourceId:'oak-tree',applicationId:'forged'}),/APPLIED_SOURCE/);
  const saved=await invoke('library.capture',{operationId:'capture-real',kind:'object',resourceId:'oak-tree',tags:['树']});assert.equal(saved.metadata.scope.projectId,context.projectId);assert.equal(saved.metadata.evidence.applied,true);
  assert.equal((await invoke('library.search',{query:'测试树'})).total,1);assert.match((await invoke('library.read',{ref:saved.ref})).source.text,/真实库测试树/);
  const formal=await call('world.read',{id:'source-world'}),selection={build:{id:formal.world.build.id,hash:formal.world.build.hash},objectId:'oak-tree',selectionRevision:1};
  await invoke('selection.set',selection);assert.equal((await service.selectionRead(host)).objectId,'oak-tree');
  await assert.rejects(invoke('selection.set',selection),/STALE_SELECTION/);
  await assert.rejects(invoke('selection.set',{...selection,selectionRevision:2,objectId:'missing'}),/OBJECT_NOT_FOUND/);
  await invoke('selection.clear');assert.equal(await service.selectionRead(host),null);
  await call('workspace.endTurn',{sessionId:context.sessionId,turnId:context.turnId,status:'completed'});
  await call('world.create',{id:'target-world',title:'Target',world:{build:build(empty),snapshot:INITIAL_SNAPSHOT,extensions:[]}});
  selectedWorld='target-world';const target={projectId:'c-target',sessionId:'c-target-session',turnId:'c-target-turn'},targetHost={...target,context:target,selectedWorld,active:false,origin:{modelKey:'fixture/provider',request:{messageId:'user-install',text:'加入这棵树'}}};
  await call('workspace.open',{context:target,selectedWorld});
  assert.equal((await invoke('library.search',{query:'测试树'},targetHost)).total,1);
  const install={operationId:'real-install',ref:saved.ref,revision:0,position:{x:8,y:6,z:0}};
  assert.equal(await service.handle('workbench.prepareAction',{channel:'library.install',payload:{worldId:selectedWorld,...install}},targetHost),null);
  const result=await invoke('library.install',install,targetHost);assert.equal(result.applied,false);assert.equal(result.receipt.revision,1);assert.equal(queued.length,1);assert.equal(queued[0].job.status,'queued');
  const replay=await service.handle('workbench.prepareAction',{channel:'library.install',payload:{worldId:selectedWorld,...install}},targetHost);assert.equal(replay.replayed,true);
  const actual=await call('workspace.inspect',{context:target});assert.equal(actual.task.draft.scene.objects.length,1);assert.equal((await call('world.read',{id:selectedWorld})).world.build.scene.objects.length,0);
  await assert.rejects(service.handle('workbench.prepareAction',{channel:'library.install',payload:{worldId:selectedWorld,...install,position:{x:10,y:6,z:0}}},targetHost),/REPLAY_MISMATCH/);
  await call('verification.cancel',{context:target,id:queued[0].job.id});
  const rule=await invoke('memory.propose',{operationId:'player-rule',kind:'project-rule',claim:'花草小一点，保留行走空间',tags:['花草']},targetHost);assert.equal(rule.status,'validated');assert.equal(rule.scope.worldId,selectedWorld);
  const proposed=await invoke('memory.propose',{operationId:'player-workflow',kind:'workflow',claim:'尝试新的排列方法',tags:[]},targetHost);assert.equal(proposed.status,'proposed');
  const injected=await service.validatedContext(target);assert.deepEqual(injected.memories.map(item=>item.id),[rule.id]);
  await assert.rejects(invoke('memory.propose',{operationId:'forged-memory',kind:'project-rule',claim:'假验证',status:'validated'},targetHost),/UNKNOWN_FIELD/);
  const replacement=await invoke('memory.propose',{operationId:'replacement',kind:'project-rule',claim:'花草应当小而疏朗',replaceId:rule.id},targetHost);assert.equal(replacement.status,'validated');
  const records=await invoke('memory.search',{includeInactive:true},targetHost);assert.ok(records.items.find(item=>item.id===rule.id).supersededBy);
  await invoke('memory.retire',{id:replacement.id,reason:'玩家手动停用'},targetHost);assert.equal((await service.validatedContext(target)).memories.length,0);
  selectedWorld='source-world';assert.equal((await invoke('memory.search',{},host)).total,0);
  await assert.rejects(invoke('memory.propose',{operationId:'cross-world',kind:'project-rule',claim:'错误世界'}, {...host,context:target}),/HOST_ACTION_TURN|WORKSPACE_WORLD/);
  console.log('Isolated Rust evidence directory:',directory);
});

