import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'package-native-')),{build}=createRequire(path.join(process.env.CRAFTMINE_DEPS_ROOT||path.resolve('vendor/pi-desktop/packages/agent-runtime'),'package.json'))('esbuild');
await build({entryPoints:[path.resolve('vendor/pi-desktop/apps/desktop/electron/main/craftmine-package-service.ts')],outfile:path.join(root,'native.mjs'),bundle:true,platform:'node',format:'esm'});
const {createCraftminePackageService}=await import(pathToFileURL(path.join(root,'native.mjs'))),sha=bytes=>createHash('sha256').update(bytes).digest('hex');
async function fixture() {
 const dir=await fs.mkdtemp(path.join(root,'case-')),file=path.join(dir,'component.zip'),bytes=Buffer.from('fixed opaque test ZIP bytes');await fs.writeFile(file,bytes);
 const state={world:'alpha',now:0,fail:false,calls:[],pick:file,picks:0};
 const service=createCraftminePackageService({selection:async()=>state.world,now:()=>state.now,pickFile:async()=>{state.picks++;return state.pick;},domainCall:async(channel,input)=>{assert.equal(channel,'package.request');state.calls.push(input);if(input.method==='installSource'){if(state.fail){state.fail=false;throw Object.assign(Error('lost'),{code:'TRANSPORT_LOST'});}return{worldId:input.args.worldId,status:'check-queued',applied:false,archiveSha256:sha(Buffer.from(input.args.archiveBase64,'base64')),instanceIds:['i-'+input.args.operationId],source:{revision:1,manifestHash:'a'.repeat(64),privatePath:dir},job:{id:'job',status:'queued',request:{body:'private source'},root:dir}};}if(input.method==='exportSource')return{archiveBase64:bytes.toString('base64'),archiveSha256:sha(bytes),files:2};if(input.method==='sourceList')return{worldId:state.world,revision:1,manifestHash:'a'.repeat(64),mainScene:'world.tscn',items:[],archiveBase64:'never-render',privatePath:dir};throw Error('unknown');}});
 const call=(method,args={})=>service.request('package.request',{worldId:state.world,method,params:{worldId:state.world,...args}});return {dir,file,bytes,state,service,call};
}
test('lost import result retries exact bytes and operation without opening another picker',async()=>{const f=await fixture();f.state.fail=true;await assert.rejects(f.call('importSource',{operationId:'same-operation'}),/TRANSPORT_LOST/);const result=await f.call('importSource',{operationId:'same-operation'});assert.equal(f.state.picks,1);assert.deepEqual(f.state.calls[0],f.state.calls[1]);assert.equal(JSON.stringify(result).includes('private source'),false);assert.equal(JSON.stringify(result).includes(f.dir),false);assert.ok(result.grantId);const repeat=await f.call('repeatImportSource',{operationId:'new-operation',grantId:result.grantId});assert.notDeepEqual(result.instanceIds,repeat.instanceIds);});
test('world, hash and expiration grants reject before another install',async()=>{const f=await fixture(),receipt=await f.call('importSource',{operationId:'first-operation'});f.state.world='beta';await assert.rejects(f.call('repeatImportSource',{operationId:'wrong-world-op',grantId:receipt.grantId}),/WORLD_MISMATCH/);f.state.world='alpha';await fs.writeFile(f.file,'changed');await assert.rejects(f.call('repeatImportSource',{operationId:'changed-file-op',grantId:receipt.grantId}),/FILE_CHANGED/);await fs.writeFile(f.file,f.bytes);f.state.now=700000;await assert.rejects(f.call('repeatImportSource',{operationId:'expired-file-op',grantId:receipt.grantId}),/GRANT_EXPIRED/);assert.equal(f.state.calls.filter(call=>call.method==='installSource').length,1);});
test('source responses are projected and renderer paths cannot become authority',async()=>{const f=await fixture();const list=await f.call('sourceList');assert.equal('archiveBase64'in list,false);assert.equal('privatePath'in list,false);await assert.rejects(f.call('importSource',{operationId:'inject-path-op',archivePath:f.file}),/INVALID_PARAMS/);await assert.rejects(f.service.request('package.request',{worldId:'alpha',method:'sourceList',params:{worldId:'beta'}}),/WORLD_MISMATCH/);});
test('oversized and linked files reject without invoking a core installer',async()=>{const f=await fixture();const handle=await fs.open(f.file,'w');await handle.truncate(5*1024*1024+1);await handle.close();await assert.rejects(f.call('importSource',{operationId:'oversized-file-op'}),/TOO_LARGE/);const target=path.join(f.dir,'owned-target'),link=path.join(f.dir,'owned-link');await fs.mkdir(target);await fs.writeFile(path.join(target,'component.zip'),f.bytes);await fs.symlink(target,link,process.platform==='win32'?'junction':'dir');f.state.pick=path.join(link,'component.zip');await assert.rejects(f.call('importSource',{operationId:'linked-file-op'}),/LINK_DENIED/);assert.equal(f.state.calls.length,0);});
test('native export saves verified bytes and returns no archive payload',async()=>{const f=await fixture();f.state.pick=path.join(f.dir,'export.zip');const result=await f.call('exportSource',{revision:1,manifestHash:'a'.repeat(64),nodePath:'Door',assetId:'door',version:1});assert.equal(result.status,'completed');assert.deepEqual(await fs.readFile(f.state.pick),f.bytes);assert.equal('archiveBase64'in result,false);f.service.dispose();await assert.rejects(f.call('sourceList'),/DISPOSED/);});
console.log('PACKAGE_NATIVE_FIXTURE '+root);
