import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {compileScene,upgradeScene,INITIAL_SNAPSHOT} from '../../app/scene.mjs';
import {sourceFixture} from '../dispatch/c/fixtures/applied-source.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const require=createRequire(new URL('../../vendor/pi-desktop/packages/agent-runtime/package.json',import.meta.url));
const {build}=require('esbuild');
const built=await build({entryPoints:[path.join(root,'vendor/pi-desktop/apps/desktop/electron/main/craftmine-panel-gateway.ts')],bundle:true,platform:'node',format:'esm',write:false});
const {createCraftminePanelGateway}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const journalBuild=await build({entryPoints:[path.join(root,'vendor/pi-desktop/apps/desktop/electron/main/craftmine-operation-journal.ts')],bundle:true,platform:'node',format:'esm',write:false});
const {createCraftmineOperationJournal}=await import('data:text/javascript;base64,'+Buffer.from(journalBuild.outputFiles[0].text).toString('base64'));
const compiledRequire=createRequire(import.meta.url);
const {CoreClient}=compiledRequire(path.join(root,'desktop/build/craftmine.world/core-client.cjs'));
const {createHostRequests}=compiledRequire(path.join(root,'desktop/build/craftmine.world/host-requests.cjs'));
const {createWorkbenchService}=compiledRequire(path.join(root,'desktop/build/craftmine.world/workbench-service.cjs'));
const {createLibraryService,createMemoryService,emptyWorld}=compiledRequire(path.join(root,'desktop/build/craftmine.world/domain.cjs'));

test('actual Rust panel integration preserves draft identity, exact receipts and bound context after world switches',async t=>{
  await mkdir(path.join(root,'test-results'),{recursive:true});const directory=await mkdtemp(path.join(root,'test-results/batch07-domain-'));
  await writeFile(path.join(directory,'TEST_PROFILE'),'Independent G Rust domain test; host and evidence are explicit fixtures.');
  const core=new CoreClient(process.env.CRAFTMINE_CORE_BIN||path.join(root,'desktop/build/rust-target/debug/craftmine-core.exe'),directory);
  t.after(()=>core.stop());await core.start();
  let failSubmit=false;const call=(method,params)=>{if(method==='verification.submit'&&failSubmit){failSubmit=false;throw Error('INJECTED_SUBMIT_TRANSPORT_FAILURE');}return core.call(method,params);},library=createLibraryService({call}),memory=createMemoryService({call});
  let selectedWorld='source-world',sessionId=null,sequence=0;const active=new Map(),queued=[];
  const verifications={enqueue:job=>queued.push(job)};
  const workbench=createWorkbenchService({call},{library,memory,verifications,getSettings:async()=>({activeWorldId:selectedWorld})});
  const domain=createHostRequests(core,{workbench,getSettings:async()=>({activeWorldId:selectedWorld})});
  const panelOptions={operations:createCraftmineOperationJournal(path.join(directory,'pending')), viewingSession:()=>sessionId,session:async id=>({id,providerId:'fixture',modelId:'fixture'}),activeTurn:id=>active.get(id),domain,
    begin:async session=>{const turn='action-'+(++sequence);active.set(session.id,turn);return turn;},
    end:async(id,status)=>{await core.call('workspace.endTurn',{sessionId:id,turnId:active.get(id),status});active.delete(id);},
    resume:async()=>{throw Error('No model in this explicit host fixture');},interrupt:async(context,reason)=>{await domain('task.interrupt',{context,reason});},stop:async()=>{},backup:async(channel,payload)=>{assert.equal(Object.hasOwn(payload,'worldId'),false);return {channel,...payload};},diagnostics:async()=>({})};
  let panel=createCraftminePanelGateway(panelOptions);
  const empty=upgradeScene({format:'craftmine.scene/1',title:'Fixture',night:false,objects:[]});
  const source=upgradeScene({...empty,format:'craftmine.scene/1',objects:[{id:'oak-tree',name:'树',position:{x:0,y:6,z:0},parts:[{offset:{x:0,y:0,z:0},size:{x:1,y:3,z:1},material:'wood'}]}]});
  const compile=scene=>{const result=compileScene(scene);return {...result,behaviors:result.behaviors||[],id:'v-'+result.hash.slice(0,20)};};
  const sourceContext={projectId:'fixture-project',sessionId:'fixture-source',turnId:'fixture-turn'};
  await sourceFixture({context:sourceContext,empty,source,build:compile,INITIAL_SNAPSHOT})(call);
  await call('workspace.endTurn',{sessionId:sourceContext.sessionId,turnId:sourceContext.turnId,status:'completed'});
  assert.ok((await panel('workbench.capabilities',{worldId:selectedWorld})).channels.includes('task.recoverable'));
  assert.equal((await panel('task.current',{worldId:selectedWorld})).context,null);
  for(const channel of ['backup.status','backup.cancel'])assert.equal((await panel(channel,{worldId:selectedWorld,operationId:'backup-operation'})).operationId,'backup-operation');
  const capture=await panel('library.capture',{worldId:selectedWorld,operationId:'capture-panel-tree',kind:'object',resourceId:'oak-tree',tags:[]});
  await call('world.create',{id:'target',title:'Target',world:emptyWorld('Target')});selectedWorld='target';sessionId='native-session-fixture';
  const args={worldId:selectedWorld,operationId:'install-panel-tree',ref:capture.ref,revision:0};
  await assert.rejects(panel('library.install',{...args,context:sourceContext}),/HOST_IDENTITY/);
  failSubmit=true;const installed=await panel('library.install',args);assert.equal(installed.receipt.revision,1);assert.equal(queued.length,0);assert.equal(installed.verificationStatus,'retry-required');assert.equal(active.size,0);
  const replay=await panel('library.install',args);assert.deepEqual(replay.receipt,installed.receipt);assert.equal(sequence,1);
  await assert.rejects(panel('library.install',{...args,position:{x:7,y:6,z:0}}),/REPLAY_MISMATCH/);
  let current=(await panel('task.current',{worldId:selectedWorld})).context;
  assert.equal(current.status,'finished');assert.equal(current.draft.revision,1);
  const unchanged=structuredClone(current);
  const retryArgs={worldId:selectedWorld,operationId:'recheck-after-submit-failure',taskId:current.binding.taskId,generation:current.generation,revision:current.draft.revision,draftHash:current.draft.hash};
  const checked=await panel('draft.recheck',retryArgs);assert.equal(checked.status,'queued');assert.equal(sequence,1);assert.equal(queued.length,1);
  const afterCheck=(await panel('task.current',{worldId:selectedWorld})).context;
  assert.deepEqual(afterCheck.draft,unchanged.draft);assert.deepEqual(afterCheck.binding,unchanged.binding);assert.equal(afterCheck.generation,unchanged.generation);assert.deepEqual(afterCheck.budget,unchanged.budget);
  await core.stop();await core.start();
  panel=createCraftminePanelGateway({...panelOptions,operations:createCraftmineOperationJournal(path.join(directory,'pending'))});
  assert.deepEqual(await panel('draft.recheck',retryArgs),checked);assert.equal(queued.length,1);
  assert.deepEqual((await panel('library.install',args)).receipt,installed.receipt);assert.equal(sequence,1);
  const memoryArgs={worldId:selectedWorld,operationId:'remember-panel-rule',kind:'project-rule',claim:'树之间保留行走空间',tags:['树']};
  const saved=await panel('memory.propose',memoryArgs);assert.equal(saved.status,'validated');
  panel=createCraftminePanelGateway({...panelOptions,operations:createCraftmineOperationJournal(path.join(directory,'pending'))});
  const count=sequence;
  assert.deepEqual(await panel('memory.propose',memoryArgs),saved);assert.equal(sequence,count);
  await assert.rejects(panel('memory.propose',{...memoryArgs,claim:'同编号不同规则'}),/REPLAY_MISMATCH/);
  current=(await panel('task.current',{worldId:selectedWorld})).context;
  selectedWorld='source-world';
  const context=Object.fromEntries(['projectId','sessionId','turnId'].map(key=>[key,current.binding[key]]));
  assert.equal((await domain('task.context',{context})).world.id,'target');
  assert.equal((await workbench.validatedContext(context)).selection,null);
  assert.equal((await domain('task.context',{context})).memories[0].text,memoryArgs.claim);
  await assert.rejects(panel('memory.search',{worldId:'target'}),/SELECTED_WORLD_CHANGED/);
  selectedWorld='target';
  const interruptedContext={...context,turnId:'interrupted-fixture-turn'};
  active.set(sessionId,interruptedContext.turnId);
  const interrupted=await domain('turn.begin',{context:interruptedContext,selectedWorld,request:{id:'recovery-original-request',text:'保留原来的树，继续种花'}});
  const owned={context:interruptedContext,binding:interrupted.binding,generation:interrupted.generation};
  await domain('budget.reserve',{...owned,requestId:'request-before-interruption',purpose:'creation',estimatedInputTokens:100,maxOutputTokens:50});
  await domain('task.interrupt',{context:interruptedContext,reason:'HOST_INTERRUPTED'});
  await call('workspace.endTurn',{sessionId,turnId:interruptedContext.turnId,status:'error'});active.delete(sessionId);
  const before=(await panel('task.current',{worldId:selectedWorld})).context;
  assert.equal(before.recovery,'interrupted');
  await assert.rejects(panel('task.resume',{worldId:selectedWorld,taskId:before.binding.taskId,generation:before.generation}),/No model in this explicit host fixture/);
  const after=(await panel('task.current',{worldId:selectedWorld})).context;
  assert.equal(after.recovery,'interrupted');assert.equal(after.generation,before.generation+1);
  assert.equal(after.budget.ownerTaskId,before.budget.ownerTaskId);
  assert.equal(after.budget.requestCount,before.budget.requestCount);
  assert.equal(after.budget.reservedTokens,before.budget.reservedTokens);
  assert.deepEqual(after.draft,before.draft);assert.equal(active.size,0);
  const recoverable=await panel('task.recoverable',{worldId:selectedWorld});
  assert.ok(recoverable.items.some(item=>item.generation===after.generation));
  await assert.rejects(domain('turn.begin',{context:{...context,turnId:'must-not-reset-budget'},selectedWorld,request:{id:'bypass-recovery',text:'新任务'}}),/EXPLICIT_RECOVERY/);
});


test('lost budget receipt survives Rust and Main restart after recovery advances the task head',async t=>{
  await mkdir(path.join(root,'test-results'),{recursive:true});
  const directory=await mkdtemp(path.join(root,'test-results/batch07-budget-receipt-'));
  const core=new CoreClient(process.env.CRAFTMINE_CORE_BIN||path.join(root,'desktop/build/rust-target/debug/craftmine-core.exe'),directory);
  t.after(()=>core.stop());await core.start();
  let sessionId='budget-receipt-session',selectedWorld='budget-world',activeTurn;
  const projectId='pi-'+createHash('sha256').update(JSON.stringify(['session',sessionId])).digest('hex');
  const context={projectId,sessionId,turnId:'before-recovery'};
  await core.call('world.create',{id:selectedWorld,title:'Budget receipt',world:emptyWorld('Budget receipt')});
  const call=(method,args)=>core.call(method,args);
  const workbench=createWorkbenchService(core,{library:createLibraryService({call}),memory:createMemoryService({call}),getSettings:async()=>({activeWorldId:selectedWorld})});
  const trusted=createHostRequests(core,{workbench,getSettings:async()=>({activeWorldId:selectedWorld})});
  const before=await trusted('turn.begin',{context,selectedWorld,request:{id:'original-request',text:'Preserve this original task'}});
  await trusted('budget.reserve',{context,binding:before.binding,generation:before.generation,requestId:'unknown-before-recovery',purpose:'creation',estimatedInputTokens:100,maxOutputTokens:50});
  await trusted('task.interrupt',{context,reason:'HOST_INTERRUPTED'});
  await core.call('workspace.endTurn',{sessionId,turnId:context.turnId,status:'error'});
  const current=(await trusted('task.context',{context}));
  let configurations=0,loseResponse=true;
  const options={viewingSession:()=>sessionId,session:async id=>({id}),activeTurn:()=>activeTurn,
    domain:async(method,args)=>{
      const result=await trusted(method,args);
      if(method==='budget.configure'){configurations++;if(loseResponse){loseResponse=false;throw Error('INJECTED_LOST_BUDGET_RESPONSE');}}
      return result;
    },begin:async()=>{throw Error('Must not create a turn');},end:async()=>{},stop:async()=>{},resume:async()=>{},interrupt:async()=>{},backup:async()=>{},diagnostics:async()=>{}};
  const journalDir=path.join(directory,'pending');
  let panel=createCraftminePanelGateway({...options,operations:createCraftmineOperationJournal(journalDir)});
  const payload={taskId:current.binding.taskId,generation:current.generation,maxTokens:4000};
  const prepared=await panel('workbench.prepare',{worldId:selectedWorld,channel:'task.budget',payload});
  await assert.rejects(panel('workbench.execute',{worldId:selectedWorld,operationId:prepared.operationId}),/INJECTED_LOST_BUDGET_RESPONSE/);
  assert.equal((await panel('workbench.operations',{worldId:selectedWorld})).items[0].state,'uncertain');
  const exact={projectId,sessionId,worldId:selectedWorld,...payload,operationId:prepared.operationId};
  const authoritative=await core.call('budget.findReceipt',exact);assert.equal(authoritative.budget.limits.maxTokens,4000);
  await core.stop();await core.start();
  const nextContext={...context,turnId:'after-recovery'};
  const resumed=await trusted('task.resume',{context:nextContext,worldId:selectedWorld,taskId:current.binding.taskId,generation:current.generation});
  assert.notEqual(resumed.workspace.task.binding.taskId,current.binding.taskId);assert.equal(resumed.generation,current.generation+1);
  activeTurn=nextContext.turnId;
  const afterHead=await trusted('task.context',{context:nextContext});
  panel=createCraftminePanelGateway({...options,operations:createCraftmineOperationJournal(journalDir)});
  assert.deepEqual(await panel('workbench.execute',{worldId:selectedWorld,operationId:prepared.operationId}),authoritative);
  assert.equal(configurations,1);assert.equal((await panel('workbench.operations',{worldId:selectedWorld})).items[0].state,'completed');
  const afterReplay=await trusted('task.context',{context:nextContext});assert.deepEqual(afterReplay.budget,afterHead.budget);assert.deepEqual(afterReplay.draft,afterHead.draft);assert.deepEqual(afterReplay.binding,afterHead.binding);
  assert.equal(afterReplay.budget.reservedTokens,150);assert.equal(afterReplay.budget.unknownRequestCount,1);
  await assert.rejects(panel('task.budget',{worldId:selectedWorld,operationId:prepared.operationId,...payload,maxTokens:9000}),/REPLAY_MISMATCH/);
  await assert.rejects(core.call('budget.findReceipt',{...exact,maxTokens:9000}),/REPLAY_MISMATCH/);
  for(const scope of [{sessionId:'foreign'},{projectId:'foreign'},{worldId:'foreign-world'}])await assert.rejects(core.call('budget.findReceipt',{...exact,...scope}));
  await assert.rejects(core.call('budget.findReceipt',{...exact,context:{projectId}}));
  sessionId='foreign';assert.deepEqual((await panel('workbench.operations',{worldId:selectedWorld})).items,[]);await assert.rejects(panel('workbench.execute',{worldId:selectedWorld,operationId:prepared.operationId}),/OWNER_MISMATCH/);sessionId=context.sessionId;
  selectedWorld='foreign-world';await assert.rejects(panel('workbench.execute',{worldId:selectedWorld,operationId:prepared.operationId}),/OWNER_MISMATCH/);selectedWorld='budget-world';
  activeTurn=undefined;
  const unknown=await panel('workbench.prepare',{worldId:selectedWorld,channel:'task.budget',payload:{...payload,maxTokens:5000}});
  assert.equal(await core.call('budget.findReceipt',{...exact,operationId:unknown.operationId,maxTokens:5000}),null);
  await assert.rejects(panel('workbench.execute',{worldId:selectedWorld,operationId:unknown.operationId}),/STALE_TASK/);assert.equal(configurations,1);
});
