#!/usr/bin/env node
// Verifies that the committed example worlds still match the base and templates.
//
// The worlds under `worlds/` are generated by tools/new-world.mjs and committed so
// they can be opened directly. This check regenerates them into a temporary
// directory and compares every file, so a change to core/ or templates/ that was
// not propagated is caught instead of drifting silently.
//
// Usage:
//   node tools/check-sync.mjs

import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const BASE_DIR = resolve(HERE, '..');

const WORLDS = [
  {
    key: 'blank',
    template: 'blank',
    worldId: 'example-blank',
    name: '空白起点',
    description: 'Top-down blank start',
    directory: join(BASE_DIR, 'worlds', 'blank'),
  },
  {
    key: 'town',
    template: 'town',
    worldId: 'example-town',
    name: '小镇示例',
    description: 'One road, one shop, one NPC, one collect-and-deliver quest',
    directory: join(BASE_DIR, 'worlds', 'town'),
  },
];

function fileMap(root) {
  const map = new Map();
  const walk = (directory) => {
    for (const entry of readdirSync(directory).sort()) {
      if (entry === '.godot') continue;
      const full = join(directory, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (!entry.endsWith('.import')) {
        map.set(relative(root, full).split(sep).join('/'), createHash('sha256').update(readFileSync(full)).digest('hex'));
      }
    }
  };
  walk(root);
  return map;
}

function compare(a, b) {
  const problems = [];
  for (const [path, hash] of a) {
    if (!b.has(path)) problems.push(`missing: ${path}`);
    else if (b.get(path) !== hash) problems.push(`differs: ${path}`);
  }
  for (const path of b.keys()) if (!a.has(path)) problems.push(`unexpected: ${path}`);
  return problems;
}

function main() {
  const work = mkdtempSync(join(tmpdir(), 'topdown-sync-'));
  let failures = 0;
  try {
    for (const world of WORLDS) {
      const generated = join(work, world.key);
      const outcome = spawnSync('node', [
        join(BASE_DIR, 'tools', 'new-world.mjs'),
        '--template', world.template,
        '--world-id', world.worldId,
        '--name', world.name,
        '--description', world.description,
        '--out', generated,
        '--force',
      ], { encoding: 'utf8', windowsHide: true });
      if (outcome.status !== 0) {
        process.stdout.write(`FAIL  ${world.key}: new-world failed: ${outcome.stderr || outcome.stdout}\n`);
        failures += 1;
        continue;
      }
      const problems = compare(fileMap(generated), fileMap(world.directory));
      if (problems.length === 0) {
        process.stdout.write(`PASS  ${world.key}: ${world.directory} matches the generator\n`);
      } else {
        failures += 1;
        process.stdout.write(`FAIL  ${world.key}: ${problems.length} difference(s)\n`);
        for (const problem of problems) process.stdout.write(`      ${problem}\n`);
      }
    }
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
  process.stdout.write(failures === 0 ? '\nall example worlds are in sync\n' : `\n${failures} world(s) out of sync\n`);
  process.exit(failures === 0 ? 0 : 1);
}

main();
