#!/usr/bin/env node
// Generates the original low-poly OBJ assets of the first-person base.
//
// Every vertex below is authored in this file. No third-party, commercial or
// ripped game asset is used, downloaded or converted. The generated .obj files
// stay plain text so a model or a person can read, edit and re-save them.
//
// Usage:
//   node tools/generate_meshes.mjs          # (re)write assets/meshes/*.obj
//   node tools/generate_meshes.mjs --check  # fail if committed output differs
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
const outputDirectory = path.join(directory, '..', 'assets', 'meshes');
const checkOnly = process.argv.includes('--check');

// Face order is [+Z, -Z, +X, -X, +Y, -Y]; winding is counter-clockwise seen from outside.
const FACE_NORMALS = [[0, 0, 1], [0, 0, -1], [1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0]];
const FACE_INDICES = [[0, 1, 2, 3], [5, 4, 7, 6], [1, 5, 6, 2], [4, 0, 3, 7], [3, 2, 6, 7], [4, 5, 1, 0]];

/** Axis-aligned box from two corners, in metres. */
function box(min, max) {
  const [x0, y0, z0] = min;
  const [x1, y1, z1] = max;
  if (!(x1 > x0 && y1 > y0 && z1 > z0)) throw Error('Box bounds must be strictly increasing: ' + JSON.stringify([min, max]));
  return {
    corners: [[x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1], [x0, y0, z0], [x1, y0, z0], [x1, y1, z0], [x0, y1, z0]],
  };
}

const number = value => (Object.is(value, -0) ? 0 : value).toFixed(4);

function renderObj(name, note, boxes) {
  const lines = [
    '# ' + name + ' - original low-poly geometry for the craftmine first-person base.',
    '# ' + note,
    '# Generated by tools/generate_meshes.mjs; edit the generator or this file, both are source.',
    '# License: MIT, see ../../licenses/ORIGINAL_ASSETS_LICENSE.txt',
    '# Units: metres. Godot convention: +Y up, -Z forward.',
    'o ' + name,
  ];
  for (const part of boxes) for (const corner of part.corners) lines.push('v ' + corner.map(number).join(' '));
  for (const part of boxes) for (const normal of FACE_NORMALS) lines.push('vn ' + normal.join(' '));
  let vertexBase = 1;
  boxes.forEach((part, partIndex) => {
    FACE_INDICES.forEach((face, faceIndex) => {
      const normalIndex = partIndex * FACE_NORMALS.length + faceIndex + 1;
      lines.push('f ' + face.map(index => (vertexBase + index) + '//' + normalIndex).join(' '));
    });
    vertexBase += part.corners.length;
  });
  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Authored meshes
// ---------------------------------------------------------------------------

const meshes = {
  // Service pistol. Origin sits at the top of the grip so the camera mount can
  // offset it directly; the barrel points down -Z.
  weapon_pistol: renderObj('weapon_pistol', 'Handgun with grip, frame, slide, barrel and sights.', [
    box([-0.022, -0.135, -0.045], [0.022, 0.005, 0.035]),   // grip
    box([-0.028, -0.005, -0.235], [0.028, 0.048, 0.030]),   // frame and slide
    box([-0.014, -0.002, -0.300], [0.014, 0.026, -0.235]),  // barrel
    box([-0.004, 0.048, -0.225], [0.004, 0.062, -0.205]),   // front sight
    box([-0.020, 0.048, -0.020], [0.020, 0.062, 0.005]),    // rear sight
    box([-0.012, -0.055, -0.120], [0.012, -0.035, 0.000]),  // trigger guard
  ]),
  // Practice sword. Origin at the guard; the blade points down -Z.
  weapon_sword: renderObj('weapon_sword', 'Training sword with tapered blade, guard, grip and pommel.', [
    box([-0.012, 0.000, -0.920], [0.012, 0.045, 0.000]),    // blade
    box([-0.008, 0.008, -0.980], [0.008, 0.037, -0.920]),   // blade tip
    box([-0.075, -0.010, -0.020], [0.075, 0.055, 0.020]),   // guard
    box([-0.018, -0.020, 0.020], [0.018, 0.045, 0.140]),    // grip
    box([-0.026, -0.026, 0.140], [0.026, 0.052, 0.170]),    // pommel
  ]),
  // Range target. Origin at the floor; the torso plate faces +Z.
  target_dummy: renderObj('target_dummy', 'Standing target with base, post, torso plate and head.', [
    box([-0.320, 0.000, -0.320], [0.320, 0.080, 0.320]),    // base
    box([-0.050, 0.080, -0.050], [0.050, 1.050, 0.050]),    // post
    box([-0.420, 1.050, -0.060], [0.420, 1.750, 0.060]),    // torso plate
    box([-0.620, 1.350, -0.050], [-0.420, 1.500, 0.050]),   // left arm
    box([0.420, 1.350, -0.050], [0.620, 1.500, 0.050]),     // right arm
    box([-0.160, 1.780, -0.060], [0.160, 2.100, 0.060]),    // head
  ]),
  // Interactable ammunition crate. Origin at the floor.
  ammo_crate: renderObj('ammo_crate', 'Ammunition crate with lid rim.', [
    box([-0.220, 0.000, -0.220], [0.220, 0.300, 0.220]),    // body
    box([-0.245, 0.300, -0.245], [0.245, 0.360, 0.245]),    // lid rim
    box([-0.180, 0.360, -0.030], [0.180, 0.400, 0.030]),    // handle
  ]),
  // Static cover crate. Origin at the floor.
  range_crate: renderObj('range_crate', 'Stackable cover crate.', [
    box([-0.350, 0.000, -0.350], [0.350, 0.650, 0.350]),    // body
    box([-0.380, 0.650, -0.380], [0.380, 0.710, 0.380]),    // lid
  ]),
};

fs.mkdirSync(outputDirectory, {recursive: true});
let changed = false;
for (const [name, content] of Object.entries(meshes)) {
  const file = path.join(outputDirectory, name + '.obj');
  const previous = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (previous === content) continue;
  changed = true;
  if (checkOnly) {
    console.error('Mesh is stale: ' + path.relative(path.join(directory, '..'), file));
    continue;
  }
  fs.writeFileSync(file, content);
  console.log('wrote ' + path.relative(path.join(directory, '..'), file));
}
if (checkOnly && changed) {
  console.error('Run node tools/generate_meshes.mjs and commit the result.');
  process.exitCode = 1;
} else if (!changed) {
  console.log('Meshes already up to date.');
}
