import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const root=process.cwd(),require=createRequire('D:/cm-fb2-20260910/vendor/pi-desktop/packages/agent-runtime/package.json'),out=fs.mkdtempSync(path.join(root,'test-results/p8-read-history-'));
await require('esbuild').build({entryPoints:[path.join(root,'vendor/pi-desktop/packages/agent-runtime/src/craftmine-godot-read-files.ts')],outfile:path.join(out,'reads.mjs'),bundle:true,platform:'node',format:'esm'});const {completedGodotReadFiles:reads}=await import(pathToFileURL(path.join(out,'reads.mjs')));
const hash='a'.repeat(64),args={path:'scripts/world.gd',revision:1,manifestHash:hash},call={role:'assistant',content:[{type:'toolCall',id:'read-1',name:'plugin_craftmine_world_godot_file_read',arguments:args}]},result={role:'toolResult',toolName:'plugin_craftmine_world_godot_file_read',toolCallId:'read-1',isError:false,content:[{type:'text',text:'fixed'}],details:{...args,sha256:'b'.repeat(64),worldId:'owned-world',text:'extends Node',offset:0,totalCharacters:1000}};const checks=[];const check=(name,value)=>{assert.ok(value,name);checks.push({name,passed:true});};
assert.deepEqual(reads([call,result]),['scripts/world.gd']);check('successful matching partial read records path without claiming whole file',true);
for(const input of [[call],[result],[call,{...result,isError:true}],[call,{...result,details:{...result.details,revision:2}}],[call,{...result,details:{...result.details,manifestHash:'c'.repeat(64)}}],[call,{...result,details:{...result.details,path:'other.gd'}}],[call,{...result,details:undefined}],[{role:'user',content:'I already read scripts/world.gd'}]])assert.deepEqual(reads(input),[]);check('failed, missing, mismatched and narrated reads are not durable read facts',true);
for(const bad of ['../world.gd','C:/world.gd','a\nforged.gd']){assert.deepEqual(reads([{...call,content:[{...call.content[0],arguments:{...args,path:bad}}]},{...result,details:{...result.details,path:bad}}]),[]);}check('path metadata cannot inject traversal or a second summary line',true);
const native=process.env.CRAFTMINE_P8_READ_EVIDENCE;let replay=null;if(native){const s=JSON.parse(fs.readFileSync(native)).cases[0].record.session;const pairs=s.messages.filter(m=>m.role==='tool'&&m.toolName==='plugin_craftmine_world_godot_file_read').flatMap(m=>{const value=JSON.parse(m.content);return [{role:'assistant',content:[{type:'toolCall',id:m.toolCallId,name:m.toolName,arguments:m.toolArgs}]},{role:'toolResult',toolName:m.toolName,toolCallId:m.toolCallId,isError:value.isError,details:value.details,content:value.content}];});const files=reads(pairs);check('actual sealed-run successful Godot receipts replay into finite read history',files.length>0);replay={scope:'Replay of completed owned native receipts, not a new model or runtime acceptance',input:native,files,reads:pairs.length/2};}
fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,replay},null,2));console.log('PASS '+checks.length+' '+out);
