import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire,stripTypeScriptTypes} from 'node:module';import {pathToFileURL} from 'node:url';import vm from 'node:vm';
const root=process.cwd(),deps=process.env.CRAFTMINE_P8_TEST_DEPS??path.join(root,'vendor/pi-desktop/packages/agent-runtime'),require=createRequire(path.join(deps,'package.json'));fs.mkdirSync(path.join(root,'test-results'),{recursive:true});const out=fs.mkdtempSync(path.join(root,'test-results/p8-thinking-summary-')),checks=[];
const check=(name,fn)=>{fn();checks.push({name,passed:true});};
await require('esbuild').build({entryPoints:[path.join(root,'vendor/pi-desktop/packages/agent-runtime/src/provider-binding.ts'),path.join(root,'vendor/pi-desktop/packages/agent-runtime/src/compaction-completion.ts')],outdir:out,bundle:true,platform:'node',format:'esm',banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},nodePaths:[path.join(deps,'node_modules')]});
const {buildProviderModel}=await import(pathToFileURL(path.join(out,'provider-binding.js')));
const {requireCompleteSummary,CRAFTMINE_SUMMARY_FOCUS}=await import(pathToFileURL(path.join(out,'compaction-completion.js')));
const sdk=await import(pathToFileURL(path.join(deps,'node_modules/@earendil-works/pi-ai/dist/api/openai-completions.js')));
const pi=await import(pathToFileURL(path.join(deps,'node_modules/@earendil-works/pi-agent-core/dist/index.js')));
const modelId='deepseek-v4.1-flash-expires-on-0910';const provider={id:'synthetic-provider',vendorKey:'deepseek',name:'Owned fixture',baseUrl:'http://127.0.0.1:1/fixed/deepseek.com/v1',modelId,apiKey:'synthetic-not-a-secret',apiStyle:'chat_completions',supportsReasoning:false,supportedThinkingLevels:['off'],modelConfig:{source:'generic',name:modelId,reasoning:false,input:['text'],contextWindow:128000,maxTokens:16384,cost:{input:0,output:0,cacheRead:0,cacheWrite:0},thinkingLevelMap:{off:null}}};
let bodies=[];const fetch=async(_url,options)=>{bodies.push(JSON.parse(options.body));return new Response('data: '+JSON.stringify({id:'synthetic',model:modelId,choices:[{index:0,delta:{content:'done'},finish_reason:'stop'}],usage:{prompt_tokens:10,completion_tokens:2,total_tokens:12}})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});};
try{
const model=buildProviderModel(provider);const response=await sdk.streamSimple(model,{messages:[{role:'user',content:'offline',timestamp:1}]},{apiKey:'synthetic',maxTokens:32,maxRetries:0,fetch}).result();check('actual SDK off-only binding emits disabled and preserves exact requested identity',()=>{assert.equal(response.stopReason,'stop');assert.deepEqual(bodies.at(-1).thinking,{type:'disabled'});assert.equal(bodies.at(-1).reasoning_effort,undefined);assert.equal(bodies.at(-1).model,modelId);assert.equal(model.baseUrl,provider.baseUrl);assert.deepEqual(provider.supportedThinkingLevels,['off']);});
await sdk.streamSimple(model,{messages:[{role:'user',content:'offline',timestamp:1}]},{apiKey:'synthetic',maxTokens:32,maxRetries:0,fetch,reasoning:'high'}).result();check('actual SDK enabled high remains enabled',()=>assert.deepEqual(bodies.at(-1).thinking,{type:'enabled'}));
for(const [name,change]of [['unrelated vendor and host',{vendorKey:'custom',baseUrl:'https://example.invalid/v1'}],['unrelated model',{modelId:'unrelated'}],['Responses protocol',{apiStyle:'responses'}]])check(name+' is not rewritten',()=>{assert.equal(buildProviderModel({...provider,...change}).reasoning,false);});
check('official exact hostname works without vendor metadata; lookalike does not',()=>{assert.equal(buildProviderModel({...provider,vendorKey:undefined,baseUrl:'https://api.deepseek.com/v1'}).reasoning,true);assert.equal(buildProviderModel({...provider,vendorKey:undefined,baseUrl:'https://api.deepseek.com.evil.invalid/v1'}).reasoning,false);});
const usage={input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}};
const raw=fs.readFileSync(path.join(root,'vendor/pi-desktop/packages/agent-runtime/src/runtime.ts'),'utf8');const start=raw.indexOf('  private async generateCompaction('),end=raw.indexOf('\n  /**',start);const startBuild=raw.indexOf('  private async buildCheckpoint('),endBuild=raw.indexOf('\n  /**',startBuild);
const classText=stripTypeScriptTypes('class RuntimeSlice {'+raw.slice(start,end)+raw.slice(startBuild,endBuild)+'}',{mode:'transform'});
const RuntimeSlice=vm.runInNewContext(classText+'\nRuntimeSlice',{requireCompleteSummary,CRAFTMINE_SUMMARY_FOCUS,compact:pi.compact,withAbortSignal:pi.withAbortSignal,BACKGROUND_CONTEXT:pi.BACKGROUND_CONTEXT,buildSessionContext:()=>({messages:[]}),isRecord:v=>!!v&&typeof v==='object',craftmineGuardedStream:(_m,c,o,_h,_p,fn)=>fn(c,o)});
for(const reason of ['length','toolUse','stop','error','aborted']){let persisted=0,received;const original=[{role:'user',content:'Keep exact existing state',timestamp:1}],preparation={messagesToSummarize:original,turnPrefixMessages:[],retainedTail:original,isSplitTurn:false,tokensBefore:100,fileOps:{read:new Set(['world.gd']),written:new Set(),edited:new Set()},settings:{reserveTokens:1024,keepRecentTokens:100,enabled:true}};const r=new RuntimeSlice();Object.assign(r,{craftmineWorld:true,thinkingLevel:'off',model,models:{streamSimple(_m,c){received=c;return {result:async()=>({role:'assistant',api:model.api,provider:model.provider,model:model.id,content:[{type:'text',text:'PARTIAL_OR_COMPLETE'}],stopReason:reason,errorMessage:reason==='error'?'synthetic failure':undefined,usage,timestamp:1})};}},trackedModelStream:(_m,_s,fn)=>fn(),entriesWithCompaction:()=>[],contextBudget:()=>({hardLimit:10000}),prepareCompactionInput:()=>({ok:true,value:preparation}),retainedUserMessageBudget:()=>100,compactionSummaryWouldExceedBudget:()=>false,fullEntries:[{id:'owned-boundary'}],createCheckpoint:(_p,_id,summary)=>{persisted++;return {summary};}});const result=await r.buildCheckpoint(new AbortController().signal,'active_turn');check('actual runtime + PI compact '+reason+' completion gate',()=>{assert.equal(result.ok,reason==='stop');assert.equal(persisted,reason==='stop'?1:0);assert.equal(preparation.messagesToSummarize,original);assert.ok(received.messages[0].content[0].text.includes(CRAFTMINE_SUMMARY_FOCUS));if(reason==='length')assert.match(result.message,/COMPACTION_SUMMARY_TRUNCATED/);});}
check('empty successful summary is refused',()=>assert.throws(()=>requireCompleteSummary({stopReason:'stop',content:[{type:'text',text:' '}]}),/SUMMARY_EMPTY/));
console.log('PASS '+checks.length+' provider/summary checks; synthetic SDK fetch only');
}catch(error){process.exitCode=1;checks.push({failure:String(error.stack??error)});console.error(String(error.stack??error));}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({scope:'Actual pinned SDK and actual runtime compaction methods with synthetic provider response; zero external model/configuration access',checks,syntheticRequests:bodies.length,bodies:bodies.map(({model,thinking,reasoning_effort,max_tokens})=>({model,thinking,reasoning_effort,max_tokens}))},null,2));console.log(out);}
