import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
import {createP8Relay,MODEL,ENDPOINT} from './relay.mjs';
const root=process.cwd(),deps=process.env.CRAFTMINE_P8_TEST_DEPS??'D:/cm-fb2-20260910/vendor/pi-desktop/packages/agent-runtime',require=createRequire(path.join(deps,'package.json'));
const out=fs.mkdtempSync(path.join(root,'test-results/p8-visible-budget-'));const checks=[];let relay;
await require('esbuild').build({entryPoints:[path.join(root,'vendor/pi-desktop/packages/agent-runtime/src/craftmine-context.ts')],outfile:path.join(out,'budget.mjs'),bundle:true,platform:'node',format:'esm',nodePaths:[path.join(deps,'node_modules')]});
const {estimateCraftmineRequest,createCraftmineRequestHooks,craftmineGuardedStream}=await import(pathToFileURL(path.join(out,'budget.mjs')));
const {convertToLlm}=await import(pathToFileURL(path.join(deps,'node_modules/@earendil-works/pi-agent-core/dist/harness/messages.js')));
const sdk=await import(pathToFileURL(path.join(deps,'node_modules/@earendil-works/pi-ai/dist/api/openai-completions.js')));
const check=(name,condition)=>{assert.ok(condition,name);checks.push({name,passed:true});};let forwarded=0;const bodies=[];
try{relay=await createP8Relay({configuration:async()=>({key:'sk-owned-synthetic-only',model:MODEL,endpoint:ENDPOINT}),persist:async()=>{},forward:async(_url,options)=>{forwarded++;bodies.push(JSON.parse(options.body));return new Response('data: '+JSON.stringify({id:'owned',model:MODEL,choices:[{index:0,delta:{role:'assistant',content:'ok'},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({id:'owned',model:MODEL,choices:[{index:0,delta:{},finish_reason:'stop'}],usage:{prompt_tokens:20,completion_tokens:5,total_tokens:25}})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}});
const model={id:MODEL,name:MODEL,provider:'fixture',api:'openai-completions',baseUrl:relay.baseUrl,reasoning:false,input:['text'],contextWindow:32000,maxTokens:100,cost:{input:0,output:0,cacheRead:0,cacheWrite:0},compat:{supportsDeveloperRole:false}};
const messages=[{role:'user',content:'Read the source',timestamp:1},{role:'assistant',api:model.api,provider:model.provider,model:MODEL,timestamp:2,stopReason:'toolUse',usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},content:[{type:'toolCall',id:'call-1',name:'read_source',arguments:{path:'world.gd'}}]},{role:'toolResult',toolCallId:'call-1',toolName:'read_source',content:[{type:'text',text:'extends Node\n'}],isError:false,timestamp:3}];
const base={systemPrompt:'Owned fixture',messages:convertToLlm(messages),tools:[{name:'read_source',description:'Read a managed source',parameters:{type:'object',properties:{path:{type:'string'}}}}]};
const mirrored={...base,messages:convertToLlm(messages.map(m=>m.role==='toolResult'?{...m,details:{text:'UI-only-'.repeat(100000)}}:m))};
check('actual PI conversion preserves mirrored details, requiring explicit estimator projection',mirrored.messages.at(-1).details.text.length===800000);
assert.deepEqual(estimateCraftmineRequest(base,100),estimateCraftmineRequest(mirrored,100));check('huge UI mirror has exactly zero model-input budget impact',true);
const writes=[];const hooks=createCraftmineRequestHooks({getContext:async()=>({binding:{projectId:'p',sessionId:'s',turnId:'t',taskId:'t',baseBuild:'b'},generation:1,status:'running',world:{id:'w',revision:0,buildId:'b',hash:'a'.repeat(64)},draft:{revision:0,hash:'b'.repeat(64)},requirements:[],modifiedResources:[],receipts:[],jobs:[],lease:{owned:true},budget:{}}),domainCall:async(method,params)=>{writes.push({method,params});return {};}});
const start=(context,options)=>sdk.streamSimple(model,context,{...options,apiKey:relay.auth,maxRetries:0});
for(const context of [base,mirrored]){const answer=await craftmineGuardedStream(model,context,{},hooks,'creation',start).result();assert.equal(answer.stopReason,'stop',answer.errorMessage);}
assert.deepEqual(bodies[0],bodies[1]);check('actual SDK produces byte-equivalent model payload with and without mirrored details',forwarded===2&&!JSON.stringify(bodies).includes('UI-only-'));
const large={...base,messages:convertToLlm(messages.map(m=>m.role==='toolResult'?{...m,content:[{type:'text',text:'visible'.repeat(20000)}]}:m))};check('large actual content still exceeds both compaction threshold and hard context budget',estimateCraftmineRequest(large,100).total>=32000);
const failed=await craftmineGuardedStream(model,large,{},hooks,'creation',start).result();check('oversized actual content fails closed before SDK forwarding',failed.stopReason==='error'&&failed.errorMessage.includes('CONTEXT_BUDGET_EXCEEDED')&&forwarded===2);
const expanded=await craftmineGuardedStream(model,base,{onPayload:payload=>({...payload,unexpected:'wire'.repeat(40000)})},hooks,'creation',start).result();check('unexpected provider wire expansion still fails final physical gate',expanded.stopReason==='error'&&expanded.errorMessage.includes('FINAL_PAYLOAD_BUDGET_EXCEEDED')&&forwarded===2);
console.log('PASS '+checks.length+' actual SDK/PI conversion and fail-closed checks; zero real provider POST');
}catch(error){process.exitCode=1;checks.push({failure:String(error.stack??error)});}finally{await relay?.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({scope:'Actual pinned PI conversion and SDK, loopback transport, synthetic upstream response; no authorized file or external provider request',checks,forwardedSynthetic:forwarded},null,2));console.log(out);}
