/* Harness UI and local preset adapter. No network requests, model calls, or imported code execution. */
(() => {
'use strict';
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='world-workshop-voxel-v02',RUNTIME='voxel-webgl@0.2',FORMAT='world-workshop-cartridge/0.2';
const BASE={harvest:false,yield:2,bridge:false,night:false,treeStyle:'pine',speed:4.5,treeRules:{}};
const STYLES={pine:'林间绿',sakura:'樱花粉',autumn:'暖秋金'};
const FIELDS={harvest:'树木采集',yield:'木材掉落数量',bridge:'河上木桥',night:'夜晚',treeStyle:'树木外观',speed:'步行速度',treeRules:'单棵树采集规则'};
const fresh=()=>({player:{x:-9.5,y:6,z:17.5,yaw:-.17,pitch:.035},wood:0,stone:0,edits:{},collected:[],fly:false,slot:2});
let data={config:clone(BASE),revision:1,versions:[{revision:1,label:'林间起点 · 3D 初始世界',config:clone(BASE),time:Date.now()}],state:fresh(),packages:[],archives:[],messages:[]};
let engine=null,mode='play',selected=null,pending=null,job=null,applying=false,assetChoice='sakura',entered=false,modalReturn=null,saveTimer=null,toastTimer=null,mapBase=null,loading=false,storageOK=true,loadWarning='';
const validObject=x=>x&&typeof x==='object'&&!Array.isArray(x);
function requireKeys(x,allowed){if(!validObject(x))throw Error('数据应为对象');for(const k of Object.keys(x))if(!allowed.includes(k))throw Error('不支持的字段：'+k);}
function safeText(x,max=100){if(typeof x!=='string'||x.length>max)throw Error('文字字段格式或长度无效');return x;}
function validateConfig(v){requireKeys(v,Object.keys(BASE));const out={};for(const[k,x]of Object.entries(v)){
 if(['harvest','bridge','night'].includes(k)){if(typeof x!=='boolean')throw Error(k+' 必须是布尔值');out[k]=x;}
 else if(k==='yield'){if(!Number.isInteger(x)||x<1||x>10)throw Error('掉落数量需要是 1–10 的整数');out[k]=x;}
 else if(k==='speed'){if(!Number.isFinite(x)||x<2||x>9)throw Error('步行速度范围是 2–9');out[k]=x;}
 else if(k==='treeStyle'){if(!Object.hasOwn(STYLES,x))throw Error('未知树木外观');out[k]=x;}
 else if(k==='treeRules'){if(!validObject(x)||Object.keys(x).length>200)throw Error('树木规则无效');out[k]={};for(const[id,r]of Object.entries(x)){if(!/^tree-\d{3}$/.test(id)||Number(id.slice(5))<1||Number(id.slice(5))>200)throw Error('树木 ID 无效');requireKeys(r,['harvest','yield']);const s=validateConfig(r);out[k][id]=s;}}
 }return out;
}
function validateEdits(e){if(!validObject(e)||Object.keys(e).length>12000)throw Error('方块修改格式无效，或超过 12,000 处');const out={};for(const [k,v]of Object.entries(e)){const n=Number(k);if(!Number.isInteger(n)||String(n)!==k||n<96*96||n>=96*96*40||!Number.isInteger(v)||v<0||v>12||v===11)throw Error('卡带包含无效方块');out[k]=v;}return out;}
function validateCollected(x){if(!Array.isArray(x)||x.length>200||x.some(id=>!/^tree-\d{3}$/.test(id)))throw Error('采集记录无效');return [...new Set(x)];}
function validateState(s){requireKeys(s,['player','wood','stone','edits','collected','fly','slot']);requireKeys(s.player,['x','y','z','yaw','pitch']);const p=s.player;
 for(const k of ['x','y','z','yaw','pitch'])if(!Number.isFinite(p[k]))throw Error('玩家坐标或视角无效');
 if(Math.abs(p.x)>47.6||Math.abs(p.z)>47.6||p.y<0||p.y>38.2||Math.abs(p.yaw)>1e6||Math.abs(p.pitch)>1.53)throw Error('玩家位置超出运行器边界');
 for(const k of ['wood','stone'])if(!Number.isInteger(s[k])||s[k]<0||s[k]>1000000)throw Error('背包数量无效');
 if(typeof s.fly!=='boolean'||!Number.isInteger(s.slot)||s.slot<0||s.slot>5)throw Error('玩家状态无效');
 return{player:{...p},wood:s.wood,stone:s.stone,edits:validateEdits(s.edits),collected:validateCollected(s.collected),fly:s.fly,slot:s.slot};
}
function validatePackage(p){requireKeys(p,['format','id','name','version','kind','runtime','author','license','permissions','dependencies','config','world']);
 if(p.format!==FORMAT||p.runtime!==RUNTIME)throw Error('卡带运行器不兼容。这一版只接受 voxel-webgl@0.2；上一版等距原型卡带不能直接安装。');
 if(!['world','module','asset'].includes(p.kind))throw Error('未知卡带类型');if(!/^[-a-zA-Z0-9_.]{1,100}$/.test(p.id))throw Error('卡带 ID 无效');
 if(!Array.isArray(p.permissions)||p.permissions.length)throw Error('本演示拒绝脚本、网络、文件等权限');if(!Array.isArray(p.dependencies)||p.dependencies.some(x=>x!=='runtime.core'))throw Error('卡带依赖未满足');
 const out={format:FORMAT,id:p.id,name:safeText(p.name,80),version:safeText(p.version,24),kind:p.kind,runtime:RUNTIME,author:safeText(p.author,80),license:safeText(p.license,120),permissions:[],dependencies:[...p.dependencies],config:validateConfig(p.config)};
 if(p.kind==='asset'&&Object.keys(out.config).some(k=>k!=='treeStyle'))throw Error('素材卡带只能改变外观');
 if(p.world){if(p.kind!=='world')throw Error('只有世界卡带能包含世界数据');requireKeys(p.world,['seed','edits','collected']);if(p.world.seed!=='forest-001')throw Error('未支持的世界种子');out.world={seed:'forest-001',edits:validateEdits(p.world.edits),collected:validateCollected(p.world.collected)};}
 return out;
}
try{const raw=localStorage.getItem(STORE);if(raw){if(raw.length>4500000)throw Error('本地存档过大');const d=JSON.parse(raw);if(!Number.isInteger(d.revision)||d.revision<1||d.revision>1000000)throw Error('版本号无效');
 data.config={...clone(BASE),...validateConfig(d.config)};data.state=validateState(d.state);data.revision=d.revision;
 data.versions=(d.versions||[]).slice(-10).map(v=>({revision:Number(v.revision)||1,label:String(v.label).slice(0,120),config:{...clone(BASE),...validateConfig(v.config)},time:Number(v.time)||0}));
 data.packages=(d.packages||[]).slice(-15).map(validatePackage);data.archives=(d.archives||[]).slice(-3).map(a=>({label:String(a.label).slice(0,100),config:{...clone(BASE),...validateConfig(a.config)},state:validateState(a.state)}));
 data.messages=(d.messages||[]).slice(-45).filter(m=>['user','assistant','system'].includes(m.role)&&typeof m.text==='string').map(m=>({role:m.role,text:m.text.slice(0,1800)}));
 }}catch(e){loadWarning=e.name==='SecurityError'?'浏览器不允许本页使用本地存储，请使用导出存档。':'没有加载旧存档：'+e.message+'。原始本地数据未立即覆盖；可在“操作说明”中导出原始数据。';data={config:clone(BASE),revision:1,versions:[{revision:1,label:'林间起点 · 3D 初始世界',config:clone(BASE),time:Date.now()}],state:fresh(),packages:[],archives:[],messages:[]};}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300);}
function version(n=data.revision){return 'v0.2.'+n;}
function scheduleSave(){if(loading||loadWarning)return;if(saveTimer)return;saveTimer=setTimeout(()=>{saveTimer=null;save();},1000);}
function save(force=false){if(!engine||loading||loadWarning&&!force)return;data.state=engine.snapshot();try{localStorage.setItem(STORE,JSON.stringify(data));storageOK=true;$('saveStatus').textContent='● 已保存在此浏览器';}catch(e){storageOK=false;$('saveStatus').textContent='○ 本地保存不可用，请导出存档';}}
function setTask(title,detail,working=false){$('taskTitle').textContent=title;$('taskDetail').textContent=detail;$('taskOrb').classList.toggle('working',working);$('taskBadge').textContent=working?'演示配置任务':'运行与修改分离';}
function append(role,text,persist=true){if(persist){data.messages.push({role,text});data.messages=data.messages.slice(-45);scheduleSave();}const el=document.createElement('div');el.className='message '+role;const r=document.createElement('div');r.className='message-role';r.textContent=role==='user'?'YOU / 创作者':role==='system'?'WORLD / 运行记录':'✧ WORLD AGENT / 演示';const b=document.createElement('div');b.className='message-body';b.textContent=text;el.append(r,b);$('messages').append(el);while($('messages').children.length>45)$('messages').firstElementChild.remove();$('messages').scrollTop=$('messages').scrollHeight;}
function showResume(){if(entered){$('resumePill').hidden=false;}else $('enterCard').hidden=false;}
function openAgent(target=null,focus=true){if(engine){const t=target||engine.target;if(t)selected=clone(t);engine.pauseInput();}updateContext();$('workspace').classList.remove('agent-hidden');showResume();if(focus)$('prompt').focus({preventScroll:true});}
function hideAgent(){engine?.keys.clear();$('workspace').classList.add('agent-hidden');if(document.activeElement?.blur)document.activeElement.blur();}
function enter(){if(!engine||applying||!$('modalOverlay').hidden)return;entered=true;$('enterCard').hidden=true;$('resumePill').hidden=true;hideAgent();engine.enter();}
function updateContext(){const t=selected;$('contextTarget').textContent=t?(t.treeId?t.treeId+' · '+STYLES[data.config.treeStyle]:t.name)+` · ${t.x}, ${t.y}, ${t.z}`:'当前世界';}
function switchMode(next){mode=next;engine?.setActive(next==='play');for(const m of ['play','develop','assets'])$('view-'+m).hidden=m!==next;document.querySelectorAll('[data-mode]').forEach(e=>e.classList.toggle('active',e.dataset.mode===next));const titles={play:['PLAY. CREATE. REPEAT.','你的世界，从这里生长。'],develop:['IDEA. BUILD. ITERATE.','从一个想法，到一段冒险。'],assets:['GENERATE. BIND. REMIX.','让每一份素材，进入你的世界。']};$('eyebrow').textContent=titles[next][0];$('pageTitle').textContent=titles[next][1];$('focusBtn').hidden=next!=='play';if(next!=='play'){$('app').classList.remove('focus-mode');openAgent(null,false);}else{showResume();setTimeout(()=>engine?.resize(),0);}}
function fmt(k,x){if(k==='treeStyle')return STYLES[x];if(typeof x==='boolean')return x?'启用':'关闭';if(k==='treeRules')return Object.entries(x).map(([id,r])=>id+'：'+(r.harvest?'可采集':'不可采集')+(r.yield?' / '+r.yield+' 木材':'')).join('；')||'无单独规则';return String(x);}
function diffs(config){return Object.entries(config).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(data.config[k])).map(([k,v])=>({key:k,name:FIELDS[k],before:fmt(k,data.config[k]),after:fmt(k,v)}));}
function renderUI(){ $('version').textContent=version();$('worldTime').textContent=data.config.night?'夜晚':'清晨';$('currentStyle').textContent=STYLES[data.config.treeStyle];$('candidateStyle').textContent=STYLES[assetChoice];$('woodCount').textContent=engine?.wood||0;updateContext();renderHistory();updateMinimapBase();}
function busy(){if(job||pending||applying){toast('请先应用或丢弃当前候选更新，再开始下一项修改。');return true;}return false;}
function lockTasks(v){$('sendBtn').disabled=v;$('bindBtn').disabled=v;}
function parsePrompt(text){let patch={};const local=$('scope').value==='selected';
 if(/砍|采集|伐|掉落|木材|木头/.test(text)){let rule={harvest:!/(禁止|不能|不要|关闭|取消|移除).{0,6}(砍|采集|伐)/.test(text)};const n=text.match(/(?:掉落|获得|每次|改成|改为|变成)\s*([0-9]+)\s*(?:份|个|块)?/);if(n)rule.yield=Number(n[1]);if(local){if(!selected?.treeId)throw Error('需要先靠近并对准一棵树，再按 T 携带树木上下文。');patch.treeRules={...data.config.treeRules,[selected.treeId]:{...data.config.treeRules[selected.treeId],...rule}};}else Object.assign(patch,rule);}
 if(/桥/.test(text))patch.bridge=!/(删除|拆掉|移除|去掉|不要|取消).{0,5}桥/.test(text);
 if(/夜晚|晚上|夜间/.test(text))patch.night=true;if(/白天|清晨|白昼/.test(text))patch.night=false;
 if(/樱|粉色/.test(text))patch.treeStyle='sakura';else if(/秋|金色|橙色/.test(text))patch.treeStyle='autumn';else if(/绿色|林间绿|青松|松树/.test(text))patch.treeStyle='pine';
 if(/加速|快一点|跑快|更快/.test(text))patch.speed=7;if(/正常速度|恢复速度|慢一点/.test(text))patch.speed=4.5;
 if(local&&Object.keys(patch).some(k=>k!=='treeRules'))throw Error('单棵树范围目前仅支持采集规则。改变外观、时间或木桥时，请切回整个世界范围。');
 return validateConfig(patch);
}
function makePending(patch,label,source='需求',world=null){pending={patch:validateConfig(patch),label,source,baseRevision:data.revision,world};$('pendingTitle').textContent=world?'世界卡带已就绪：'+label:'候选更新已就绪：'+label;$('pendingSummary').textContent=world?'将归档当前世界并创建新世界；不覆盖原存档。':'当前仍在运行 '+version()+'；应用时保留最新进度。';$('pendingBanner').hidden=false;lockTasks(true);setTask('新版本可以试玩了',world?'先归档当前世界，再加载世界卡带。':'你决定什么时候应用。当前可玩的世界尚未改变。');scheduleSave();}
async function startJob(patch,label){if(busy())return;const d=diffs(patch);if(!d.length){append('assistant','当前世界已经是这个设置，无需重复更新。');return;}const token={};job=token;lockTasks(true);setTask('识别到演示指令','正在整理已支持的配置项；不会生成任意代码。',true);append('system','演示任务：'+d.map(x=>x.name+' → '+x.after).join('；')+'。未识别的额外需求不会执行。');
 await new Promise(r=>setTimeout(r,450));if(job!==token)return;setTask('正在校验候选配置','检查字段白名单、参数范围与运行版本。',true);
 await new Promise(r=>setTimeout(r,450));if(job!==token)return;try{validateConfig(patch);job=null;makePending(patch,label);append('assistant','候选更新已经准备好。\n'+d.map(x=>x.name+'：'+x.before+' → '+x.after).join('\n')+'\n\n你可以继续玩，准备好后点击“应用并继续玩”。这是预设配置更新，不是真实 AI 编程结果。');}catch(e){job=null;lockTasks(false);append('system','候选校验失败：'+e.message);setTask('当前世界未改变',e.message);}}
async function submitPrompt(){const text=$('prompt').value.trim();if(!text)return;if(busy())return;append('user',text);$('prompt').value='';if($('intent').value==='discuss'){append('assistant','这版先记录你的想法，不修改世界。\n\n演示执行器目前能处理：树木采集与掉落、预设河上木桥、白天与夜晚、三种树木外观、移动速度。任意玩法设计和代码开发需要后续连接真实 Agent。');return;}
 try{const patch=parsePrompt(text);if(!Object.keys(patch).length){append('assistant','这条需求超出了本地演示执行器的范围，我没有修改世界。\n\n可以试试：“让树木可以被砍，每次掉落2份木材”“在河上建一座桥”“把树木换成樱花粉色”“把世界变成夜晚”。');return;}await startJob(patch,text.slice(0,36));}catch(e){append('assistant',e.message);toast(e.message);}}
async function applyPending(){if(!pending||job||applying||!engine)return;if(pending.baseRevision!==data.revision){toast('候选版本已过期，请重新制作。');discard();return;}const p=pending,previous={config:clone(data.config),state:engine.snapshot()},prevArchives=clone(data.archives);applying=true;engine.pauseInput();engine.setActive(false);$('applyBtn').disabled=true;$('reloadMask').hidden=false;switchMode('play');engine.setActive(false);await new Promise(r=>setTimeout(r,70));
 try{let state=previous.state;if(p.world){data.archives.push({label:'归档 '+version()+' · '+new Date().toLocaleString('zh-CN'),config:previous.config,state:previous.state});data.archives=data.archives.slice(-3);state={...fresh(),edits:clone(p.world.edits||{}),collected:[...(p.world.collected||[])]};data.config={...clone(BASE),...p.patch};}else data.config={...data.config,...p.patch};
  engine.generate(data.config,state);engine.undo=[];data.revision++;data.versions.push({revision:data.revision,label:p.label,config:clone(data.config),time:Date.now()});data.versions=data.versions.slice(-10);pending=null;$('pendingBanner').hidden=true;selected=null;renderUI();append('system','已应用 '+version()+'：'+p.label+(p.world?'。原世界已归档，可在版本窗口恢复。':'。保留了应用瞬间的位置、背包和手动搭建；仅在碰撞时移到安全位置。'));setTask('世界更新已应用','继续体验。你刚才的手动搭建和修改期间的最新进度仍然在。');save();toast('世界已更新 · 点击继续游玩');
 }catch(e){data.config=previous.config;data.archives=prevArchives;try{engine.generate(previous.config,previous.state);}catch(recoverError){showError(recoverError.message);}append('system','应用失败，尝试恢复应用前的世界：'+e.message);toast('更新失败：'+e.message);setTask('更新未完成',e.message);}
 finally{applying=false;$('reloadMask').hidden=true;$('applyBtn').disabled=false;lockTasks(!!pending);engine.setActive(true);showResume();}
}
function discard(){if(applying)return;job=null;pending=null;$('pendingBanner').hidden=true;lockTasks(false);setTask('候选更新已丢弃','当前可玩版本和游戏进度没有改变。');append('system','已丢弃候选配置，当前世界保持不变。');}
function blockSVG(top,left,right){return `<svg viewBox="0 0 40 44" class="block-svg" aria-hidden="true"><path fill="${top}" d="m20 2 17 9-17 9-17-9Z"/><path fill="${left}" d="m3 11 17 9v21L3 31Z"/><path fill="${right}" d="m20 20 17-9v20l-17 10Z"/><path fill="#ffffff18" d="m8 13 6 3v5l-6-3Zm15 12 7-4v5l-7 4Z"/></svg>`;}
const blockColors=[['#99bd65','#866b49','#6c5b3f'],['#a8b1a7','#829082','#6c7b71'],['#dbba7f','#b69460','#957944'],['#b6ce85','#87a75e','#6c8c4b'],['#ffde8c','#e5b755','#cc983e'],['#b5bbae','#8b9789','#728373']];
function renderHotbar(){const {HOTBAR,NAMES}=WorldRuntime;$('hotbar').innerHTML=HOTBAR.map((id,i)=>`<button data-slot="${i}" title="${i+1} · ${NAMES[id]}" aria-label="选择${NAMES[id]}"><span>${i+1}</span>${blockSVG(...blockColors[i])}</button>`).join('');$('hotbar').querySelectorAll('button').forEach(b=>b.onclick=()=>{engine.slot=Number(b.dataset.slot);updateSlot(engine.slot);scheduleSave();});updateSlot(engine?.slot??2);}
function updateSlot(slot){$('hotbar').querySelectorAll('button').forEach(e=>e.classList.toggle('active',Number(e.dataset.slot)===slot));$('selectedName').textContent=WorldRuntime.NAMES[WorldRuntime.HOTBAR[slot]]+' · 无限搭建';}
function treeSVG(style){const c={pine:['#b8cc88','#8aac60','#688a4e'],sakura:['#edc5d3','#d29bad','#b77897'],autumn:['#edce87','#d4af59','#b99243']}[style];return `<svg viewBox="0 0 130 150" aria-hidden="true"><ellipse cx="65" cy="135" rx="37" ry="9" fill="#08140725"/><path fill="#bc966a" d="m59 78 15 6v48l-15-6Z"/><path fill="#8d734f" d="m74 84 10-6v46l-10 8Z"/><path fill="${c[0]}" d="m20 61 42-23 48 23-44 25Z"/><path fill="${c[1]}" d="m20 61 46 25v30L20 90Z"/><path fill="${c[2]}" d="m66 86 44-25v30l-44 25Z"/><path fill="${c[0]}" d="m31 34 31-17 36 18-32 19Z"/><path fill="${c[1]}" d="m31 34 35 20v31L31 65Z"/><path fill="${c[2]}" d="m66 54 32-19v31L66 85Z"/><path fill="#ffffff13" d="m38 46 12 7v13l-12-7Zm36 17 11-6v11l-11 7Z"/></svg>`;}
function renderAssets(){const details={pine:'青绿树冠 · 像素纹理',sakura:'柔粉树冠 · 春日氛围',autumn:'金色树冠 · 暖秋氛围'};$('assetGrid').innerHTML=Object.entries(STYLES).map(([s,n])=>`<button class="asset-card ${s===assetChoice?'selected':''}" data-style="${s}" aria-label="选择${n}"><div class="asset-art ${s}">${treeSVG(s)}</div><div class="asset-card-copy"><strong>${n}</strong><small>${details[s]}</small></div></button>`).join('');$('assetGrid').querySelectorAll('button').forEach(b=>b.onclick=()=>{assetChoice=b.dataset.style;renderAssets();$('candidateStyle').textContent=STYLES[assetChoice];});}
function updateMinimapBase(){if(!engine)return;const c=document.createElement('canvas');c.width=96;c.height=96;const cx=c.getContext('2d');for(let z=-48;z<48;z++)for(let x=-48;x<48;x++){const h=engine.surface(x,z);cx.fillStyle=h<5.65?'#79b9b6':h>10?'#839271':h===5?'#ccb887':'#9bb478';cx.fillRect(x+48,z+48,1,1);}const colors={pine:'#52734c',sakura:'#bf8ea0',autumn:'#a28d45'};for(const t of engine.trees.values())if(!engine.collected.includes(t.id)){cx.fillStyle=colors[data.config.treeStyle];cx.fillRect(t.x+47,t.z+47,2,2);}cx.fillStyle='#8f7752';cx.fillRect(23,43,8,7);if(data.config.bridge)cx.fillRect(49,43,15,5);mapBase=c;}
function drawMinimap(p){if(!mapBase)return;const c=$('minimap'),ctx=c.getContext('2d');ctx.clearRect(0,0,180,180);ctx.imageSmoothingEnabled=false;ctx.drawImage(mapBase,0,0,180,180);ctx.save();ctx.translate((p.x+48)/96*180,(p.z+48)/96*180);ctx.rotate(-p.yaw);ctx.fillStyle='#f2fad6';ctx.strokeStyle='#38482f';ctx.lineWidth=1.7;ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(4,5);ctx.lineTo(0,3);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
function openModal(title,html,eyebrow='craftmine world'){engine?.pauseInput();showResume();modalReturn=document.activeElement;$('modalTitle').textContent=title;$('modalEyebrow').textContent=eyebrow;$('modalContent').innerHTML=html;$('modalOverlay').hidden=false;$('closeModal').focus();}
function closeModal(){$('modalOverlay').hidden=true;$('modalContent').innerHTML='';if(modalReturn?.isConnected)modalReturn.focus({preventScroll:true});}
function renderHistory(){const html=data.versions.slice().reverse().map(v=>`<div class="version-item"><span>${version(v.revision)}</span><div><b>${esc(v.label)}</b><p>${v.revision===data.revision?'当前配置版本':'保留当前游戏进度，仅恢复玩法与外观配置'}</p></div>${v.revision===data.revision?'<span class="tag">当前</span>':`<button class="button subtle compact" data-rollback="${v.revision}">试用此配置</button>`}</div>`).join('');$('devHistory').innerHTML=html;$('devHistory').querySelectorAll('[data-rollback]').forEach(b=>b.onclick=()=>rollback(Number(b.dataset.rollback)));return html;}
function rollback(n){if(busy())return;const v=data.versions.find(x=>x.revision===n);if(!v)return;closeModal();makePending(v.config,'恢复 '+version(n)+' 的配置','版本回退');}
function openHistory(){const h=renderHistory();openModal('世界走过的每一步',`<p class="notice">版本回退只恢复玩法与外观配置，不倒退背包、采集记录和手动方块。手动方块操作可在游戏内按 Z 撤销最近 40 步。归档恢复则会恢复完整旧世界。</p><div class="version-list">${h}</div>${data.archives.length?'<div class="section-heading" style="margin-top:23px"><h3>已归档的完整世界</h3><span>最多保留最近 3 个</span></div>'+data.archives.map((a,i)=>`<div class="version-item"><div><b>${esc(a.label)}</b><p>含当时的位置、背包、方块和配置</p></div><button class="button compact" data-archive="${i}">恢复归档</button></div>`).join(''):''}`,'VERSION HISTORY');$('modalContent').querySelectorAll('[data-rollback]').forEach(b=>b.onclick=()=>rollback(Number(b.dataset.rollback)));$('modalContent').querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>restoreArchive(Number(b.dataset.archive)));}
function restoreArchive(i){if(busy())return;const a=data.archives[i];if(!a)return;const current={label:'切换前 '+version(),config:clone(data.config),state:engine.snapshot()};data.archives.splice(i,1);data.archives.push(current);data.archives=data.archives.slice(-3);data.config=clone(a.config);engine.generate(data.config,a.state);engine.undo=[];data.revision++;data.versions.push({revision:data.revision,label:'恢复归档世界',config:clone(data.config),time:Date.now()});data.versions=data.versions.slice(-10);closeModal();renderUI();save();toast('已恢复归档。切换前的世界也已归档。');}
function builtin(kind){const p={format:FORMAT,id:'workshop.demo.'+kind,name:kind==='harvest'?'采集起点':kind==='sakura'?'樱花森林':'夜航河谷',version:'1.0.0',kind:kind==='harvest'?'module':kind==='sakura'?'asset':'world',runtime:RUNTIME,author:'最中幻想 · 内置示例',license:'演示内容：允许本地使用与改作',permissions:[],dependencies:['runtime.core'],config:kind==='harvest'?{harvest:true,yield:2}:kind==='sakura'?{treeStyle:'sakura'}:{...clone(BASE),harvest:true,bridge:true,night:true}};if(p.kind==='world')p.world={seed:'forest-001',edits:{},collected:[]};return p;}
function openLibrary(){openModal('让创造，成为下一次创造的起点。',`<p class="notice">卡带只包含本运行器认识的 JSON 配置与方块数据，不执行代码。世界卡带新建一个世界；玩法与素材卡带更新当前世界。这是本地卡带库，没有社区服务器。</p><div class="library-grid">${[['harvest','♧','采集起点','玩法模组','树木采集，每棵掉落 2 份木材。',''],['sakura','✿','樱花森林','素材包','替换外观，保留已有游戏规则。','pink'],['night','◈','夜航河谷','世界卡带','带木桥和采集的夜晚新世界。','blue']].map(([id,g,n,k,d,c])=>`<article class="cartridge"><div class="cartridge-art ${c}">${g}</div><div class="cartridge-body"><small>${k}</small><h3>${n}</h3><p>${d}</p><button class="button" data-builtin="${id}">检查并试装 ↗</button></div></article>`).join('')}</div>${data.packages.length?'<div class="section-heading" style="margin-top:23px"><h3>我的本地卡带</h3><span>'+data.packages.length+' / 15</span></div><div class="version-list">'+data.packages.map((p,i)=>`<div class="version-item"><div><b>${esc(p.name)}</b><p>${esc(p.kind)} / ${esc(p.author)}</p></div><button class="button compact" data-package="${i}">试装</button></div>`).join('')+'</div>':''}<div class="modal-actions"><span class="muted left" style="font-size:10px">兼容：${RUNTIME}</span><button class="button" id="importModalBtn">导入 JSON 卡带</button><button class="button primary" id="packModalBtn">打包当前作品</button></div>`,'CREATE ONCE. REMIX AGAIN.');$('modalContent').querySelectorAll('[data-builtin]').forEach(b=>b.onclick=()=>previewInstall(builtin(b.dataset.builtin)));$('modalContent').querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>previewInstall(data.packages[Number(b.dataset.package)]));$('importModalBtn').onclick=()=>$('importFile').click();$('packModalBtn').onclick=openPackage;}
function previewInstall(input){if(busy())return;let p;try{p=validatePackage(input);}catch(e){toast(e.message);return;}const d=diffs(p.config);openModal('安装前，先看看会改变什么。',`<p class="notice ${p.kind==='world'?'warn':''}">${p.kind==='world'?'这是一张世界卡带。应用后创建新世界；当前世界先归档，之后可以恢复。':'只制作候选更新，不立即修改正在运行的世界。手动方块修改优先保留。'}</p><div class="diff-list"><div class="diff-row"><span>卡带</span><b>${esc(p.name)}</b></div><div class="diff-row"><span>运行器检查</span><b>兼容 · ${RUNTIME}</b></div><div class="diff-row"><span>权限</span><b>无脚本 / 无网络 / 无文件访问</b></div>${d.map(x=>`<div class="diff-row"><span>${x.name}</span><b>${esc(x.before)} → ${esc(x.after)}</b></div>`).join('')}${p.world?`<div class="diff-row"><span>世界内容</span><b>${Object.keys(p.world.edits).length} 处方块修改 / ${p.world.collected.length} 棵已移除树木</b></div>`:''}</div><div class="modal-actions"><button class="button" id="backLibraryBtn">返回卡带库</button><button class="button primary" id="confirmInstallBtn">${p.kind==='world'?'准备新世界':'制作候选更新'}</button></div>`,'CARTRIDGE PREVIEW');$('backLibraryBtn').onclick=openLibrary;$('confirmInstallBtn').onclick=()=>{if(busy())return;closeModal();makePending(p.config,'安装「'+p.name+'」','卡带',p.kind==='world'?(p.world||{seed:'forest-001',edits:{},collected:[]}):null);append('system','已检查卡带「'+p.name+'」：声明式格式有效、运行器兼容、无执行权限。尚未应用。');};}
function download(name,object){const blob=new Blob([typeof object==='string'?object:JSON.stringify(object,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function openPackage(){if(job||applying){toast('等待当前配置任务结束后再打包。');return;}openModal('把这次创造，装进一张卡带。',`<p class="notice">只打包已应用版本，不包含候选更新。世界卡带包含配置、手动搭建和被采集的树木，但不携带玩家背包与个人位置；完整进度请用“导出存档”。</p><div class="field"><label for="packageName">卡带名称</label><input id="packageName" maxlength="80" value="我的林间世界"></div><div class="field"><label for="packageKind">内容类型</label><select id="packageKind"><option value="world">世界卡带 · 配置 + 方块内容</option><option value="module">玩法模组 · 采集、木桥和速度配置</option><option value="asset">素材包 · 树木外观</option></select></div><div class="field"><label for="packageAuthor">作者署名</label><input id="packageAuthor" maxlength="80" value="本地创作者"></div><div class="field"><label for="packageLicense">使用说明</label><input id="packageLicense" maxlength="120" value="仅供个人体验；再分发请联系作者"><small>此字段是作者说明，不代表平台对素材授权作出审核。</small></div><div class="diff-row"><span>已应用版本</span><b>${version()} · ${Object.keys(engine.edits).length} 处手动修改</b></div><div class="modal-actions"><button class="button primary" id="exportPackageBtn">保存到本地卡带库并导出 ↗</button></div>`,'PACKAGE YOUR CREATION');$('exportPackageBtn').onclick=()=>{try{const kind=$('packageKind').value,name=$('packageName').value.trim()||'未命名卡带';let config=kind==='world'?clone(data.config):kind==='asset'?{treeStyle:data.config.treeStyle}:{harvest:data.config.harvest,yield:data.config.yield,bridge:data.config.bridge,speed:data.config.speed,treeRules:clone(data.config.treeRules)};const p={format:FORMAT,id:'local.'+Date.now().toString(36),name,version:'1.0.0',kind,runtime:RUNTIME,author:$('packageAuthor').value.trim()||'本地创作者',license:$('packageLicense').value.trim(),permissions:[],dependencies:['runtime.core'],config};if(kind==='world')p.world={seed:'forest-001',edits:clone(engine.edits),collected:[...engine.collected]};const valid=validatePackage(p);data.packages.push(valid);data.packages=data.packages.slice(-15);save();download('craftmine-world-'+kind+'-'+Date.now()+'.cartridge.json',valid);closeModal();toast('卡带已导出'+(storageOK?'，并加入本地卡带库':'；本地空间不足，请保留下载文件'));}catch(e){toast('打包失败：'+e.message);}};}
async function importPackage(file){if(!file)return;try{if(file.size>2000000)throw Error('卡带过大，本演示限制为 2 MB');const p=validatePackage(JSON.parse(await file.text()));if(!data.packages.some(x=>x.id===p.id)){data.packages.push(p);data.packages=data.packages.slice(-15);save();}previewInstall(p);}catch(e){toast('未导入卡带：'+e.message);}finally{$('importFile').value='';}}
function exportSave(){if(!engine)return;download('craftmine-world-save-'+Date.now()+'.json',{format:'world-workshop-save/0.2',runtime:RUNTIME,config:clone(data.config),state:engine.snapshot()});toast('完整世界进度已导出');}
async function importSave(file){if(!file)return;try{if(busy())return;if(file.size>2000000)throw Error('存档超过 2 MB 限制');const p=JSON.parse(await file.text());requireKeys(p,['format','runtime','config','state']);if(p.format!=='world-workshop-save/0.2'||p.runtime!==RUNTIME)throw Error('存档格式不兼容');const config={...clone(BASE),...validateConfig(p.config)},state=validateState(p.state);data.archives.push({label:'导入存档前 '+version(),config:clone(data.config),state:engine.snapshot()});data.archives=data.archives.slice(-3);data.config=config;engine.generate(config,state);engine.undo=[];data.revision++;data.versions.push({revision:data.revision,label:'导入完整存档',config:clone(config),time:Date.now()});data.versions=data.versions.slice(-10);loadWarning='';renderUI();save();closeModal();switchMode('play');toast('存档已载入，之前的世界已归档');}catch(e){toast('未载入存档：'+e.message);}finally{$('importSaveFile').value='';}}
function openHelp(){openModal('先走进去，再改变它。',`<div class="help-grid">${[['W A S D','前后左右移动'],['鼠标','环顾；未锁定时按住拖动'],['Space','跳跃 / 飞行时上升'],['Shift','冲刺 / 飞行时下降'],['左键 / R','破坏准星所指的方块'],['右键 / Q','在方块表面放置'],['1–6','选择方块；创造模式无限材料'],['E','采集已启用玩法的整棵树'],['F','切换步行 / 创造飞行'],['Z','撤销最近一次手动方块操作'],['T','携带眼前对象，唤醒 Agent'],['Esc','释放鼠标 / 关闭弹窗']].map(([k,t])=>`<div><kbd>${k}</kbd>${t}</div>`).join('')}</div><p class="help-note">触屏：左侧摇杆移动，拖动场景环顾，右侧按钮跳跃、破坏、放置与采集。桌面点击“进入世界”锁定鼠标；浏览器禁止鼠标锁定时，按住场景拖动环顾，并用 WASD 移动、R 破坏、Q 放置。</p><p class="notice">这是 96 × 96、最高 40 格的有限 3D 实验场，不是完整《我的世界》克隆。没有怪物、联机、真实 AI 编程、任意模组脚本或无限地形。内置像素材质为程序生成，没有使用 Minecraft 官方素材。</p>${loadWarning?'<p class="notice warn">'+esc(loadWarning)+'</p>':''}<div class="modal-actions"><button class="button left" id="rawSaveBtn">导出原始本地数据</button><button class="button" id="importSaveBtn">导入完整存档</button><button class="button" id="exportSaveModalBtn">导出完整存档</button><button class="button" id="resetBtn">重置 3D 演示</button></div>`,'CONTROLS & BOUNDARIES');$('rawSaveBtn').onclick=()=>{try{download('craftmine-world-raw-local.json',localStorage.getItem(STORE)||'{}');}catch(e){toast('无法读取浏览器存储');}};$('importSaveBtn').onclick=()=>$('importSaveFile').click();$('exportSaveModalBtn').onclick=exportSave;$('resetBtn').onclick=()=>{if(busy())return;if(!confirm('重置本浏览器中的 3D 演示？会清除 3D 存档、历史与本地卡带。上一版等距原型不受影响。'))return;loadWarning='reset';clearTimeout(saveTimer);try{localStorage.removeItem(STORE);}catch(e){}location.reload();};}
function showError(message){$('errorText').textContent=message;$('errorScreen').hidden=false;}
function bindTouch(){const stick=$('joystick'),thumb=$('joystickThumb');let drag=null;const move=e=>{if(drag!==e.pointerId)return;const r=stick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/34,y=(e.clientY-r.top-r.height/2)/34,n=Math.max(1,Math.hypot(x,y));x/=n;y/=n;engine.touchMove={x,y};thumb.style.transform=`translate(${x*27}px,${y*27}px)`;};stick.onpointerdown=e=>{e.preventDefault();if(!engine)return;entered=true;$('enterCard').hidden=true;$('resumePill').hidden=true;engine.input=true;drag=e.pointerId;stick.setPointerCapture(e.pointerId);move(e);};stick.onpointermove=move;const end=()=>{drag=null;if(engine)engine.touchMove={x:0,y:0};thumb.style.transform='';};stick.onpointerup=end;stick.onpointercancel=end;stick.onlostpointercapture=end;
 $('touchJump').onpointerdown=e=>{e.preventDefault();engine.input=true;engine.keys.add('Space');e.currentTarget.setPointerCapture(e.pointerId);};for(const type of ['pointerup','pointercancel','lostpointercapture'])$('touchJump').addEventListener(type,()=>engine.keys.delete('Space'));
 $('touchBreak').onclick=()=>engine.breakBlock();$('touchPlace').onclick=()=>engine.placeBlock();$('touchHarvest').onclick=()=>engine.interact();
}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));document.querySelectorAll('[data-go-play]').forEach(b=>b.onclick=()=>switchMode('play'));
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.prompt;openAgent();});
$('enterBtn').onclick=enter;$('resumeBtn').onclick=enter;$('agentLaunch').onclick=()=>openAgent();$('closeAgent').onclick=hideAgent;$('clearContext').onclick=()=>{selected=null;updateContext();};
$('chatForm').onsubmit=e=>{e.preventDefault();submitPrompt();};$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();submitPrompt();}});$('prompt').addEventListener('focus',()=>engine?.pauseInput());
$('applyBtn').onclick=applyPending;$('discardBtn').onclick=discard;$('respawnBtn').onclick=()=>engine?.respawn();$('collectBtn').onclick=()=>engine?.interact();$('helpBtn').onclick=openHelp;$('historyBtn').onclick=openHistory;$('libraryBtn').onclick=openLibrary;$('packageBtn').onclick=openPackage;$('saveExportBtn').onclick=exportSave;
$('bindBtn').onclick=()=>{if(busy())return;append('user','把全部树木外观绑定为'+STYLES[assetChoice]+'，保留已有玩法。');startJob({treeStyle:assetChoice},'绑定外观 · '+STYLES[assetChoice]);};
$('focusBtn').onclick=()=>{$('app').classList.toggle('focus-mode');if($('app').classList.contains('focus-mode'))hideAgent();setTimeout(()=>engine?.resize(),0);toast('沉浸视图 · 按 Esc 可返回工作台');};
$('closeModal').onclick=closeModal;$('modalOverlay').addEventListener('pointerdown',e=>{if(e.target===$('modalOverlay'))closeModal();});
$('importFile').onchange=()=>importPackage($('importFile').files[0]);$('importSaveFile').onchange=()=>importSave($('importSaveFile').files[0]);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('modalOverlay').hidden){e.preventDefault();closeModal();return;}if($('app').classList.contains('focus-mode')){$('app').classList.remove('focus-mode');setTimeout(()=>engine?.resize(),0);}if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)){document.activeElement.blur();hideAgent();}showResume();}
 if(e.key==='Tab'&&!$('modalOverlay').hidden){const items=[...$('modalOverlay').querySelectorAll('button:not(:disabled),input,select,[tabindex="0"]')].filter(e=>e.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
});
window.addEventListener('pagehide',()=>save());document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
try{
 loading=true;
 engine=new WorldRuntime.VoxelRuntime($('world'),{
  onChange:()=>{scheduleSave();if(engine)updateMinimapBase();},
  onNotice:toast,onError:showError,
  onAgent:t=>{if($('modalOverlay').hidden)openAgent(t);},onSlot:updateSlot,
  onControl:s=>{if(s==='locked'||s==='touch'){$('enterCard').hidden=true;$('resumePill').hidden=true;}else if(s==='drag'){if(!entered){entered=true;$('enterCard').hidden=true;}$('resumePill').hidden=true;toast('按住场景拖动环顾 · WASD 移动 · R 破坏 · Q 放置');}else showResume();},
  onTarget:t=>{$('targetLabel').textContent=t?(t.treeId?'树木':t.name)+' · '+t.distance.toFixed(1)+' m':'';},
  onStats:s=>{$('position').textContent=[s.position.x,s.position.y,s.position.z].map(x=>x.toFixed(1)).join(' · ');$('woodCount').textContent=s.wood;$('moveMode').textContent=s.fly?'创造飞行 · Space ↑ / Shift ↓':'步行 / 创造模式';$('fps').textContent=(engine?.software?'兼容 3D · ':'')+s.fps+' FPS';drawMinimap(s.position);if(engine?.input)scheduleSave();},
  onEffect:()=>{updateMinimapBase();}
 });
 engine.generate(data.config,data.state);loading=false;
 renderHotbar();renderAssets();renderUI();bindTouch();
 if(!data.messages.length)append('assistant','这次，你真的可以走进世界了。\n\n沿着林间小径走走，跳上方块，或者亲手搭点东西。\n\n对准眼前的树，按 T 告诉我：“让树木可以被砍”。我会用本地预设准备一个候选更新，你决定何时应用。\n\n先玩起来，下一步的想法会自己出现。');else for(const m of data.messages)append(m.role,m.text,false);
 if(innerWidth<1000)hideAgent();if(matchMedia('(pointer:coarse)').matches)document.querySelector('#enterCard small').textContent='左侧摇杆移动 · 拖动画面环顾';if(loadWarning){$('saveStatus').textContent=loadWarning.includes('不允许本页')?'○ 本地存储不可用，请导出存档':'○ 旧存档校验失败，已暂停自动覆盖';setTimeout(()=>toast(loadWarning),300);}else scheduleSave();
 // Explicit inspection surface for deterministic tests; not a security boundary.
 window.workshop={runtime:engine,getState:()=>({config:clone(data.config),state:engine.snapshot(),revision:data.revision,pending:pending?clone(pending):null,job:!!job,mode,packages:clone(data.packages),archives:clone(data.archives)}),parsePrompt,validatePackage,validateState,validateConfig,submitPrompt,applyPending,discard,save,openAgent,previewInstall,builtin,switchMode,startJob,restoreArchive,version,exportSave};
}catch(e){loading=false;showError(e.message);console.error(e);}
})();
