import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../../',import.meta.url));
const require=createRequire(import.meta.url);
const {CoreClient}=require(path.join(root,'desktop/build/craftmine.world/core-client.cjs'));
const {createHostRequests}=require(path.join(root,'desktop/build/craftmine.world/host-requests.cjs'));
const {emptyWorld}=require(path.join(root,'desktop/build/craftmine.world/domain.cjs'));
test('real Rust host bridge records corrections, forbids identity/limit forgery and settles stopped requests',async t=>{
  const directory=await mkdtemp(path.join(tmpdir(),'craftmine-g-domain-'));
  await writeFile(path.join(directory,'TEST_PROFILE'),'Independent dispatch G data; no credentials');
  const binary=process.env.CRAFTMINE_CORE_BIN||path.join(root,'desktop/build/rust-target/debug/craftmine-core.exe');
  const core=new CoreClient(binary,directory);t.after(()=>core.stop());await core.start();
  await core.call('world.create',{id:'first',title:'第一世界',world:emptyWorld('第一世界')});
  await core.call('world.create',{id:'other',title:'第二世界',world:emptyWorld('第二世界')});
  let selected='first';const call=createHostRequests(core,{getSettings:async()=>({activeWorldId:selected})});
  const context={projectId:'p',sessionId:'s',turnId:'t'};
  const start=await call('turn.begin',{context,selectedWorld:'first',request:{id:'r1',text:'请生成一棵树'}});
  assert.equal(start.requirements[0].text,'请生成一棵树');
  const revised=await call('task.context',{context,request:{id:'r2',text:'树要矮一点，保留已有花草'}});
  assert.equal(revised.requirements.find(row=>row.id==='r2').kind,'correction');assert.equal(revised.requirements[0].id,'r1');assert.equal(revised.requirements.length,2);
  selected='other';assert.equal((await call('task.context',{context})).world.id,'first');
  assert.equal((await call('selection.read',{})).worldId,'other');
  await assert.rejects(call('task.context',{context,request:{id:'r2',text:'伪造重试'}}),/REPLAY_MISMATCH/);
  const longText='树的要求。'.repeat(400);
  const long=await call('task.context',{context,request:{id:'long',text:longText}});
  assert.equal(long.requirements.find(row=>row.id==='long').truncated,true);
  assert.equal((await call('task.context',{context,request:{id:'long',text:longText}})).world.id,'first');
  const owned={context,binding:start.binding,generation:start.generation};
  const reserve={...owned,requestId:'model-1',purpose:'creation',estimatedInputTokens:100,maxOutputTokens:50};
  await assert.rejects(call('budget.reserve',{...reserve,generation:999}),/BINDING_MISMATCH/);
  await assert.rejects(call('budget.reserve',{...reserve,limits:{maxTokens:90000000}}));
  await call('budget.reserve',reserve);
  await core.call('workspace.endTurn',{sessionId:'s',turnId:'t',status:'aborted'});
  await assert.rejects(call('budget.reserve',{...reserve,requestId:'after-stop'}),/TASK_INACTIVE/);
  const settled=await call('budget.settle',{...owned,requestId:'model-1',status:'known',usage:{inputTokens:80,outputTokens:10,totalTokens:90}});
  assert.equal(settled.budget.actualTokens,90);assert.equal(settled.budget.requestCount,1);
  assert.equal(settled.budget.reservedTokens,0);
  await assert.rejects(call('budget.settle',{...owned,requestId:'never-sent',status:'unknown'}),/RESERVATION_NOT_FOUND/);
  await assert.rejects(call('providers.getSecret',{}),/UNSUPPORTED_HOST_OPERATION/);
});
